Fixups and nit from __future__:
Fixup for stores being None in data_tracking_stores:

AttributeError: 'NoneType' object has no attribute 'data_path_to_key' -
screenshot tab was disabled

That's really #336

Fixup for double calling save list RUI - this also will be addressed as
part of refresh refactoring.

Infinit nit radiating from future

Nit in irefresh

Mopy/bash/ScriptParser.py: fdust

'deleted' renames

Mopy/bash/basher/installer_links.py: _selected seems unused see
827861d0fef45625fe68a8f87abe3c565413bbd4 - I also removed the comment
on asterisks - does not apply since that commit