Move not_playable_flag to records:
Still hacky but less (by at least some imports and a PatchGame
variable) - this permitted me to un-nest MultiTweakItem.

Mopy/bash/basher/gui_patchers.py: base.AMultiTweaker didn't exist
Mopy/bash/basher/mod_links.py: regression fixup - no setChanged anymore

Traceback (most recent call last):
  File "bash\balt.py", line 1943, in __Execute
  File "bash\basher\mod_links.py", line 1412, in Execute
AttributeError: 'TopGrup' object has no attribute 'setChanged'