Monkey patches for BAIN bugs:
Installing a mod with Korean folder names inside meshes:

Traceback (most recent call last):
  File "bash\balt.py", line 2495, in __Execute
    self.Execute()
  File "bash\balt.py", line 1605, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\installer_links.py", line 504, in Execute
    ui_refresh, progress, last, override)
  File "bash\bosh\bain.py", line 2269, in bain_install
    override)
  File "bash\bosh\bain.py", line 2209, in _install
    progress, refresh_ui)
  File "bash\bosh\bain.py", line 2225, in __installer_install
    sub_progress)
  File "bash\bosh\bain.py", line 990, in install
    return self._install(dest_src, progress)
  File "bash\bosh\bain.py", line 1383, in _install
    None)
  File "bash\bosh\bain.py", line 1021, in _fs_install
    fs_operation(srcs, dests, progress.getParent())
  File "bash\env.py", line 579, in shellCopy
    silent=False, parent=parent)
  File "bash\env.py", line 522, in _fileOperation
    target.replace(u'\x00', u'\n'))
bash.exception.InvalidPathsError: <exception str() failed>

https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=170834

Those filenames mean New folder btw - see below post linked above - mod:
https://www.nexusmods.com/skyrimspecialedition/mods/1134
inside 00 Core Files\meshes\KHair\

TWO bugs - stdout fails to print exc as seen above plus the fail per se.
The stdout <exception str() failed> we can't do much about, I added
debug prints for the Bugdump that work correctly.

This is introduced in 2412203d1efd6c4e4f4bdbc81952ec7b98656797, but
copying the files around just to avoid blowing for the 0.00001% mods
that have funny folder names (are those read by the game ?) is still a
nono. Correct way would probably be to switch to SHFileOperationW - but
I don't think this is supported by pywin32 - time to bug them I guess.
Meanwhile monkey patched to fall back to shutil.

Mopy/bash/archives.py: unverified attempt to fix listing of BAIN files,
see:

https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=171028

Mopy/bash/basher/installers_links.py: IIUC bsls are for SEE too - last
minute change...