Fixups in status bar buttons:
As reported in a PM by @Sharlikran "Settings -> Status Bar ->
Show App Version" was broken since
f18a6358b3fb2dadb485b7b489447b05d3ffebb6 :

Traceback (most recent call last):
  File "bash\balt.py", line 2439, in __Execute
    self.Execute()
  File "bash\basher\settings_links.py", line 258, in Execute
    if bass.settings['bash.obse.on']:
  File "bash\bolt.py", line 1188, in __getitem__
    return self.data[key]
KeyError: 'bash.obse.on'

Of course the previous behavior was a full time bug:

>  Anyway this makes no sense at all and I rather see some (patcher ?)
>  blow and patch that, than have this nonsense in the code.

Only it was not the patcher that blew.

Took the opportunity to factor out common code and fix various design
bugs - amongst which some behavior bugs, Execute was never overwritten
for laa button and default handling was haphazard. Notes:

- not sure why `not bass.settings.get('bash.obse.on',False)` while the
default is True, seems another bug to me (just wouldn't show as Execute
would only call SetState(-1) after SetState had set default value). Note
laa same behavior while autoquit not.
- AppButton code is heavily not OO - this has annoyed me since forever
and is a constant source of bugs, but no time to properly rewrite, using
inheritance instead of isinstance, for instance
- namespacing balt.images due to shadowing warns on method params
- Mopy/bash/balt.py: renaming local to differentiate from (unresolved!)
imageKey attribute.

Squashed in:

Encapsulate access to obse/laa state via the buttons:

Chops off some bush.game uses - always more than welcome.

Under #174 - obseButton version may be addressed now

Signed-off-by: MrD <the.ubik@gmail.com>