TableFileInfos.refresh:
...plus table must go for #336 of whose end this commit is the
beginning:

- common code in refresh is moved to base
- adds corrupted to IniInfos
- _initDB override gone

_diff_dir -> del_infos should contain all infos that need be removed so
no need for

-        for k in list(self): # fixme drop??
-            if k not in new_or_present: del self[k]

new_info is in the Monsters Manual - on to delete_refresh

Zero size inis

__init__.py 1650 refresh: Failed to load Refraction Shader, Disabled [Oblivion].ini from D:\GAMES\TESIV\Oblivion\Data\INI Tweaks\Refraction Shader, Disabled [Oblivion].ini: Failed to infer INI type
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bosh\__init__.py", line 1639, in refresh
    self.new_info(new, _in_refresh=True,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bosh\__init__.py", line 1667, in new_info
    info = self[fileName] = self.factory(self.store_dir.join(fileName),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bosh\__init__.py", line 1915, in ini_info_factory
    inferred_ini_type, detected_encoding = get_ini_type_and_encoding(fullpath)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\ini_files.py", line 85, in get_ini_type_and_encoding
    raise FailedIniInferError(abs_ini_path)
bash.exception.FailedIniInferError: D:\GAMES\TESIV\Oblivion\Data\INI Tweaks\Refraction Shader, Disabled [Oblivion].ini: Failed to infer INI type

TODO: Add deprint not tb (but let the dust settle)

Inline _update_deleted_paths:

- now that IniInfos gained a corrupted attribute we don't need a
delete_refresh override - this permitted inlining _update_deleted_paths

- move lo_deactivate after the deletion - it's internal cache
manipulation so correct seems doing it once we know files were deleted.
This dropped files_to_delete override