Regression: Fix extracting OMODs when placed in BAIN dir
Probably broke in 76593442990ce52ed055a44dd44f6358c9140429.

Mopy/bash/bosh/loot_parser.py:
Don't blow up on empty {user,master}lists

Reported on Discord, probably due to a userlist that was created via
LOOT, but then all entries got removed via LOOT too. That leaves it
empty, which makes pyyaml spit out None as the parse result.

Mopy/bash/game/skyrim/records.py:
Fix MreDial erroring on dump with missing SNAM

As far as I can tell, this has always been broken. Another struct gotcha
to watch out for, I guess:

PS C:\Users\Infernio> py -2
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> struct.pack('4s', 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: argument for 's' must be a string
PS C:\Users\Infernio> py -3
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> struct.pack('4s', 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: argument for 's' must be a bytes object