Regression in Save tab rename + ModInfos rename performance fixes:
Traceback (most recent call last):
  File "bash\basher\__init__.py", line 2004, in DoSave
    bosh.saveInfos.rename(oldName,newName)
  File "bash\bosh.py", line 4936, in rename
    def rename(self,oldName,newName):
  File "bash\bosh.py", line 4052, in rename
    try:
AttributeError: SaveInfo instance has no attribute 'isGhost'

Most likely introduced in 9d302a803a5732dcfdb5c793cdcfd105382e82fa

ModInfos rename - avoid unnecessary saves:

	 #self.plugins.LoadOrder.insert(oldIndex, newName)
-        self.plugins.saveLoadOrder()
+        # self.plugins.saveLoadOrder() # JUST DONE IN addMods()

Took the opportunity to rename refresh parameter to savePlugins -
Plugins.refresh() _loads_, how very confusing.