Backwards-compatible changes from lojack-py3
Infernio: consists of the following:

[py3] types.ClassType no longer exists

Traceback (most recent call last):
  File "..\Mopy\bash\bash.py", line 282, in _main
    from . import basher, balt
  File "..\Mopy\bash\basher\__init__.py", line 64, in <module>
    from types import ClassType
ImportError: cannot import name 'ClassType' from 'types' (C:\Code\Python\3.8\lib\types.py)

Fix:
https://stackoverflow.com/questions/529240/what-happened-to-types-classtype-in-python-3

[py3] Issue with slots and multiple inheritance

Traceback (most recent call last):
  File "..\Mopy\bash\bash.py", line 185, in main
    _main(opts)
  File "..\Mopy\bash\bash.py", line 282, in _main
    from . import basher, balt
  File "..\Mopy\bash\basher\__init__.py", line 3427, in <module>
    class BashNotebook(wx.Notebook, balt.TabDragMixin):
TypeError: multiple bases have instance lay-out conflict

TODO: See if there's a better fix other than just dropping slots?

Infernio: edited to only comment out the slots, no need to drop the
new-style class. Also added a PY3 note.

[py3] `types.IntType` and `types.LongType` no longer exist

Infernio: added a PY3: note for gettext install method, no longer takes
a unicode kwarg in py3

[wx] Only attempt to bind/unbind if the window still exists

Traceback (most recent call last):
  File "..\Mopy\bash\balt.py", line 1697, in _conversation_wrapper
    if not _depth: Link.Frame.BindRefresh(bind=True)
  File "..\Mopy\bash\basher\__init__.py", line 3738, in BindRefresh
    self.Bind(__event, self.RefreshData)
  File "..\.venv\lib\site-packages\wx\core.py", line 1406, in _EvtHandler_Bind
    event.Bind(self, id, id2, handler)
  File "..\.venv\lib\site-packages\wx\core.py", line 1477, in Bind
    target.Connect(id1, id2, et, function)
RuntimeError: wrapped C/C++ object of type BashFrame has been deleted

[wx] `wx.App.Exit` removed

Traceback (most recent call last):
  File "..\Mopy\bash\bash.py", line 448, in _show_wx_error
    app.Exit()
AttributeError: 'BashApp' object has no attribute 'Exit'

Under #460