Add string prefixes to windows
Utumno: formatting and propagating prefixing to calling code

To achieve this I had to follow callers and **kwargs stood on the way.
Simplification will help with eventual move to gui but also tracking .s
used in links show*** methods.
Dropped _askOk Link method - single use and this comes from a time I
wanted to reduce 'window' occurrences - now we need to rethink those
APIs.

Note:

@@ -481,3 +477,3 @@ def __configure(self, c_links, centered, close, minimize, h_links,

-        if c_links and len(getattr(self, '_buttons', [])) > 0:
+        if c_links and getattr(self, u'_buttons', []):
             additional_flags |= USE_COMMAND_LINKS

I see no reason for the len check

Some tests:

PS C:\Users\Infernio> py -3
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from uuid import UUID
>>> AccountPictures         = UUID(u'{008ca0b1-55b4-4c56-b8a8-4de4b299d3be}')
>>> AccountPictures         = UUID(b'{008ca0b1-55b4-4c56-b8a8-4de4b299d3be}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\uuid.py", line 174, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
TypeError: a bytes-like object is required, not 'str'

PS C:\Users\Infernio> py -3
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import Structure, c_int, c_wchar_p
>>> class TASKDIALOG_BUTTON(Structure):
...     _fields_ = [(u'nButtonID', c_int),
...                 (u'pszButtonText', c_wchar_p)]
...
>>> class TASKDIALOG_BUTTON(Structure):
...     _fields_ = [(b'nButtonID', c_int),
...                 (b'pszButtonText', c_wchar_p)]
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '_fields_' must be a sequence of (name, C type) pairs

Under #460
Under #174, yep

Co-authored-by: MrD <the.ubik@gmail.com>