BSAError(FileError)
Otherwise blows on a wrong Bsa magic - we catch FileError in refresh

Wrye Bash encountered an error.
Please post the information below to the official thread at
https://afkmods.com/index.php?/topic/4966-wrye-bash-all-games
or to the Wrye Bash Discord at
https://discord.gg/NwWvAFR

Traceback (most recent call last):
  File "bash\bash.py", line 206, in main
    _main(opts, wx_locale)
  File "bash\bash.py", line 369, in _main
    frame = app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4063, in Init
    self.InitData(progress)
  File "bash\basher\__init__.py", line 4097, in InitData
    bosh.bsaInfos.refresh(booting=True)
  File "bash\bosh\__init__.py", line 1387, in refresh
    notify_bain=not booting)
  File "bash\bosh\__init__.py", line 2973, in new_info
    if new_bsa.inspect_version() not in bush.game.bsa.valid_versions:
  File "bash\bosh\bsa_files.py", line 431, in inspect_version
    self.bsa_header.load_header(ins)
  File "bash\bosh\bsa_files.py", line 150, in load_header
    super(BsaHeader, self).load_header(ins)
  File "bash\bosh\bsa_files.py", line 139, in load_header
    self.file_id, self.__class__.bsa_magic))
BSAError: Magic wrong: got 'del ', expected 'BSA\x00'

Infernio: properly reworked it to be non-hacky and display the filename
when displaying the error :)
Also included a refactoring to use bolt.Flags for the archive flags.

Mopy/bash/bosh/__init__.py:
The __init__ can't actually throw DDSErrors - nothing except the Extract
function of the BSA tab can, and that's currently disabled.

Mopy/bash/balt.py:
GUI nitpick - improve tags menu splitting

Somewhat accounts for the 'extra items' added to a choice menu. Can't
fully compensate since a separator does not have the full width of a
link, but this does look better.

Mopy/bash/_games_lo.py:
_games_lo: Silence silly warnings

Use AbstractError since only timestamp games need to implement
get_free_time.

Mopy/bash/game/oblivion/records.py:
TES4: Default directional fade to 1.0

To mirror CBash and xEdit.

Co-authored-by: MrD <the.ubik@gmail.com>