Nitpick in UIList subclasses:
Binned Tank.colReverse variation
SetStatusCount: I eliminated overrides - sublclasses provide just the text.
MessagePanel.ClosePanel() should be absorbed in the
`if hasattr(self, 'listData'):` case - if the Panel is not binned
completely. At least now ClosePanel and OnShow encapsulate the common Panel
logic.

Fon now if I let it I get:

__init__.py 4773 SaveSettings: An error occurred while trying to save settings:
Traceback (most recent call last):
  File "bash\basher\__init__.py", line 4770, in SaveSettings
    self.notebook.GetPage(index).ClosePanel()
  File "bash\basher\__init__.py", line 3988, in ClosePanel
    super(MessagePanel, self).ClosePanel()
  File "bash\basher\__init__.py", line 318, in ClosePanel
    super(SashPanel, self).ClosePanel()
  File "bash\basher\__init__.py", line 270, in ClosePanel
    table = self.listData.table
AttributeError: Messages instance has no attribute 'table'

This is due to not centralizing data initialization
Line numbers may be slightly different - got it from another revision

Slight de-wx'ing (combobox) + rearranging callbacks in UIList -
the ones that event.Skip() may need to be optional