FO4: Stop decoding date in saves
6bf66ca898dfd159b166acb132fbd63cc4cc2d48 fixed this for Russian, but now
breaks it for other languages that don't seem to use UTF-8 here. This
commit stops decoding here altogether in favor of reading characters
until we hit a non-digit character and then just parsing the result as
an int.

Triggered by this traceback, looks like it broke with Japanese:

Traceback (most recent call last):
  File "bash\bash.pyo", line 249, in main
  File "bash\bash.pyo", line 412, in _main
  File "bash\basher__init.pyo", line 4239, in Init
  File "bash\basher__init.pyo", line 4278, in InitData
  File "bash\bosh__init.pyo", line 2899, in refresh
  File "bash\bosh__init.pyo", line 1445, in refresh
  File "bash\bosh__init.pyo", line 1421, in new_info
  File "bash\bosh__init.pyo", line 1330, in new_info
  File "bash\bosh__init.pyo", line 1041, in init
  File "bash\bosh__init.pyo", line 175, in init
  File "bash\bolt.pyo", line 1164, in init
  File "bash\bosh__init.pyo", line 187, in _reset_cache
  File "bash\bosh__init.pyo", line 1064, in readHeader
  File "bash\bosh\save_headers.pyo", line 68, in init
  File "bash\bosh\save_headers.pyo", line 87, in load_header
  File "bash\bosh\save_headers.pyo", line 489, in calc_time
UnicodeEncodeError: 'decimal' codec can't encode character u'\uc2dc' in position 2: invalid decimal Unicode string

Tested with saves in various languages from Nexus, seems to work fine
with all of them now.

Mopy/bash/bolt.py:
OrderedSet fixups

Randomly stumbled across some PyCharm warnings here. Not sure how
relevant this really is, since it's only used for MemorySet, which is
only used in CBash, which we're dropping soon...

Also a minor docstring fixup - that's not an invariant, that's a
precondition.

Mopy/bash/bolt.py:
Avoid EUC-TW encoding entirely

We used to modify chardet to avoid it spitting this one out, let's try
just skipping it when it's detected.