Nightly squash:
.gitignore: add commonly used virtual environments

TTT setGhost accepts itsa_ghost:

Actually this makes the _refresh_ghost_state in there unneeded - the
difficulty is tracing the _lo_cache decorator the rest of the uses seem
safe

Drop MelObject hash: TTT

As discussed - MelObject is mutable so should *not* be used in sets -
went for TypeError as:

>>> {}[[]]
Traceback (most recent call last):
  File "C:\_\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: unhashable type: 'list'

EAFP TODOs EEE TTT

Mopy/bash/bosh/converters.py: do the stat if wrapPopenOut fails - TTT,
does it fail for a missing file?

Mopy/bash/brec/common_subrecords.py - skills default should be a list?

localize.py  103 setup_locale: cli_lang='' - cli_target='' - falling back to (en_US, cp1252) from getdefaultlocale
localize.py  107 setup_locale: wx gave back en_US
localize.py  154 setup_locale: Set wxPython locale to 'en_US'
loot_parser.py   48 <module>: Using LibYAML-based parser
doc_viewer.py   42 <module>: pdfviewer using PyMuPDF (GPL)
bash.py  254 dump_environment: Using Wrye Bash Version 310.202205201421 (Standalone)
	OS info: Windows-10-10.0.19044-SP0, running on Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
	Python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
	Dependency versions:
	 - chardet: 4.0.0
	 - lxml: 4.8.0
	 - PyMuPDF: 1.19.6; bundled MuPDF version: 1.19.0
	 - python-lz4: 4.0.0; bundled LZ4 version: 1.9.3
	 - PyYAML: 6.0
	 - wxPython: 4.1.1 msw (phoenix) wxWidgets 3.1.5
	Input encoding: None; output encoding: utf-8
	Filesystem encoding: utf-8
	Command line: ['D:\\Skyrim programs\\Mopy\\Wrye Bash.exe']
bash.py  502 _import_bush_and_set_game: Searching for game to manage:
bush.py  144 _supportedGames: The following games are supported by this version of Wrye Bash:
  Enderal, Enderal Special Edition, Fallout 3, Fallout 3 (WS), Fallout
  4, Fallout 4 (WS), Fallout 4 VR, Fallout New Vegas, Fallout New Vegas
  (WS), Morrowind, Morrowind (WS), Nehrim, Oblivion, Oblivion (WS),
  Skyrim, Skyrim Special Edition, Skyrim Special Edition (WS), Skyrim VR
Wrye Bash looked for games in the following places:
 1. Windows Registry:
  The following installed games were found via the registry:
   - Skyrim Special Edition: D:\Steam\steamapps\common\Skyrim Special Edition
  Make sure to run the launcher of each game you installed through Steam
  once, otherwise Wrye Bash will not be able to find it.
 2. Windows Store:
  No installed games with modding enabled were found via the Windows Store.
  Make sure to enable mods for each Windows Store game you have
  installed, otherwise Wrye Bash will not be able to find it.
bush.py  205 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  215 _detectGames: No known game in parent directory of Mopy: D:\Skyrim programs
bush.py  227 __setGame: Using Skyrim Special Edition game: D:\Steam\steamapps\common\Skyrim Special Edition
initialization.py  166 init_dirs: My Games location set to C:\Users\peper\Documents\My Games\Skyrim Special Edition
initialization.py  179 init_dirs: LocalAppData location set to C:\Users\peper\AppData\Local\Skyrim Special Edition
initialization.py  227 init_dirs: Game Mods location set to D:\Steam\steamapps\common\Skyrim Special Edition Mods
initialization.py  232 init_dirs: Bash Mod Data location set to D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data
initialization.py  236 init_dirs: Installers location set to D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Installers
initialization.py  238 init_dirs: Installers bash data location set to D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bash
initialization.py  246 init_dirs: Checking if WB directories exist and creating them if needed:
initialization.py  250 init_dirs:  - D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data
initialization.py  250 init_dirs:  - D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Installers
initialization.py  250 init_dirs:  - D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bain Converters
initialization.py  250 init_dirs:  - D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bain Converters\--Duplicates
initialization.py  250 init_dirs:  - D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bain Converters\--Corrupt
initialization.py  250 init_dirs:  - D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bash
initialization.py  250 init_dirs:  - D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bash\BSA Cache
loot_parser.py   83 __init__: Using these LOOT paths:
loot_parser.py   84 __init__:  Masterlist: C:\Users\peper\AppData\Local\LOOT\games\Skyrim Special Edition\masterlist.yaml
loot_parser.py   85 __init__:  Userlist: C:\Users\peper\AppData\Local\LOOT\games\Skyrim Special Edition\userlist.yaml
loot_parser.py   86 __init__:  Taglist (fallback): D:\Skyrim programs\Mopy\taglists\SkyrimSE\taglist.yaml
loot_parser.py   93 __init__: Initialized loot_parser, compatible with libloot v0.18.x
__init__.py 3739 initBosh: Looking for main game INI at C:\Users\peper\Documents\My Games\Skyrim Special Edition\Skyrim.ini
windows.py  967 testUAC: Testing if game folder is UAC-protected
__init__.py 1581 _initDB: Initializing BSAInfos
__init__.py 1582 _initDB:  store_dir: D:\Steam\steamapps\common\Skyrim Special Edition\Data
__init__.py 1583 _initDB:  bash_dir: D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data\BSA Data
__init__.py 1581 _initDB: Initializing ModInfos
__init__.py 1582 _initDB:  store_dir: D:\Steam\steamapps\common\Skyrim Special Edition\Data
__init__.py 1583 _initDB:  bash_dir: D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data
_games_lo.py  665 print_lo_paths: Using the following load order files:
_games_lo.py  667 print_lo_paths:  - Load order and active plugins: C:\Users\peper\AppData\Local\Skyrim Special Edition\plugins.txt
__init__.py 1581 _initDB: Initializing SaveInfos
__init__.py 1582 _initDB:  store_dir: C:\Users\peper\Documents\My Games\Skyrim Special Edition\Saves
__init__.py 1583 _initDB:  bash_dir: C:\Users\peper\Documents\My Games\Skyrim Special Edition\Saves\Bash
__init__.py 1581 _initDB: Initializing INIInfos
__init__.py 1582 _initDB:  store_dir: D:\Steam\steamapps\common\Skyrim Special Edition\Data\INI Tweaks
__init__.py 1583 _initDB:  bash_dir: D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data\INI Data
__init__.py 3684 __init__: Constructing panel 'Installers'
__init__.py 3694 __init__: Panel 'Installers' constructed successfully
__init__.py 3684 __init__: Constructing panel 'Mods'
__init__.py 3694 __init__: Panel 'Mods' constructed successfully
__init__.py 3684 __init__: Constructing panel 'Saves'
__init__.py 3694 __init__: Panel 'Saves' constructed successfully
__init__.py 3684 __init__: Constructing panel 'INI Edits'
__init__.py 3694 __init__: Panel 'INI Edits' constructed successfully
__init__.py 3684 __init__: Constructing panel 'Screenshots'
__init__.py 1581 _initDB: Initializing ScreenInfos
__init__.py 1582 _initDB:  store_dir: D:\Steam\steamapps\common\Skyrim Special Edition
__init__.py 1583 _initDB:  bash_dir: D:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data\Screenshot Data
__init__.py 3694 __init__: Panel 'Screenshots' constructed successfully
mod_files.py  241 load: Skyrim.esm: Duplicate top-level b'HAZD' group, merging
mod_files.py  241 load: Skyrim.esm: Duplicate top-level b'HAZD' group, merging
mod_files.py  241 load: Skyrim.esm: Duplicate top-level b'HAZD' group, merging
mod_files.py  241 load: Skyrim.esm: Duplicate top-level b'HAZD' group, merging
record_structs.py  196 dumpData: Error dumping data:
Traceback (most recent call last):
  File "bash\brec\record_structs.py", line 194, in dumpData
  File "bash\brec\basic_elements.py", line 194, in dumpData
  File "bash\brec\common_subrecords.py", line 455, in pack_subrecord_data
TypeError: 'int' object is not iterable

record_structs.py  197 dumpData: Occurred while dumping <HareRace [RACE:0006DC99]>
record_structs.py  207 dumpData: > starting_stamina: Rounder(0.0)
record_structs.py  207 dumpData: > stamina_regen: Rounder(0.0)
record_structs.py  207 dumpData: > race_size: 0
record_structs.py  207 dumpData: > hair_biped_object: 0
record_structs.py  207 dumpData: > keywords: [79768, 285248343]
record_structs.py  207 dumpData: > mount_offset_z: Rounder(0.0)
record_structs.py  207 dumpData: > skills: 0
record_structs.py  207 dumpData: > unarmed_damage: Rounder(0.0)
record_structs.py  207 dumpData: > shield_biped_object: 0
record_structs.py  207 dumpData: > keyword_count: 2
record_structs.py  207 dumpData: > magicka_regen: Rounder(0.0)
record_structs.py  207 dumpData: > male_face_texture_sets: []
record_structs.py  207 dumpData: > angular_tolerance: Rounder(0.0)
record_structs.py  207 dumpData: > biped_flags: 0x00000000 (None)
record_structs.py  207 dumpData: > female_data_marker: b''
record_structs.py  207 dumpData: > male_race_presets: []
record_structs.py  207 dumpData: > male_available_hair_colors: []
record_structs.py  207 dumpData: > mount_offset_x: Rounder(-63.479)
record_structs.py  207 dumpData: > dismount_offset_y: Rounder(0.0)
record_structs.py  207 dumpData: > female_face_texture_sets: []
record_structs.py  207 dumpData: > base_carry_weight: Rounder(5.0)
record_structs.py  207 dumpData: > female_tint_masks: []
record_structs.py  207 dumpData: > dismount_offset_x: Rounder(-50.0)
record_structs.py  207 dumpData: > femaleVoice: 0
record_structs.py  207 dumpData: > female_body_data: []
record_structs.py  207 dumpData: > facefx_phonemes: []
record_structs.py  207 dumpData: > female_marker: b''
record_structs.py  207 dumpData: > mount_camera_offset_x: Rounder(0.0)
record_structs.py  207 dumpData: > male_tint_masks: []
record_structs.py  207 dumpData: > male_body_data: []
record_structs.py  207 dumpData: > male_graph_marker: b''
record_structs.py  207 dumpData: > male_decapitate_armor: 0
record_structs.py  207 dumpData: > starting_magicka: Rounder(0.0)
record_structs.py  207 dumpData: > maleWeight: Rounder(0.0)
record_structs.py  207 dumpData: > description: ''
record_structs.py  207 dumpData: > data_flags_2: 0x00000000 (None)
record_structs.py  207 dumpData: > eid: 'HareRace'
record_structs.py  207 dumpData: > full: 'Rabbit'
record_structs.py  207 dumpData: > unknown1: b'\x00\x00'
record_structs.py  207 dumpData: > mount_camera_offset_z: Rounder(0.0)
record_structs.py  207 dumpData: > head_biped_object: 0
record_structs.py  207 dumpData: > movement_type_names: []
record_structs.py  207 dumpData: > equip_slots: []
record_structs.py  207 dumpData: > female_head_parts: []
record_structs.py  207 dumpData: > _loader_state: []
record_structs.py  207 dumpData: > phoneme_target_names: []
record_structs.py  207 dumpData: > injured_health_percentage: Rounder(0.0)
record_structs.py  207 dumpData: > angular_acceleration_tolerance: Rounder(0.0)
record_structs.py  207 dumpData: > male_default_hair_color: 0
record_structs.py  207 dumpData: > body_data_marker: b''
record_structs.py  207 dumpData: > behavior_graph_marker: b''
record_structs.py  207 dumpData: > female_default_hair_color: 0
record_structs.py  207 dumpData: > mount_offset_y: Rounder(0.0)
record_structs.py  207 dumpData: > maleVoice: 0
record_structs.py  207 dumpData: > starting_health: Rounder(0.0)
record_structs.py  207 dumpData: > movement_types: []
record_structs.py  207 dumpData: > biped_object_names: []
record_structs.py  207 dumpData: > mount_camera_offset_y: Rounder(-300.0)
record_structs.py  207 dumpData: > armor_type: 0
record_structs.py  207 dumpData: > base_mass: Rounder(0.0)
record_structs.py  207 dumpData: > flight_radius: Rounder(0.0)
record_structs.py  207 dumpData: > male_marker: b''
record_structs.py  207 dumpData: > hairs: []
record_structs.py  207 dumpData: > attacks: []
record_structs.py  207 dumpData: > spell_count: 2
record_structs.py  207 dumpData: > male_head_parts: []
record_structs.py  207 dumpData: > acceleration_rate: Rounder(0.0)
record_structs.py  207 dumpData: > aim_angle_tolerance: Rounder(0.0)
record_structs.py  207 dumpData: > data_flags_1: 0x00000000 (None)
record_structs.py  207 dumpData: > female_race_presets: []
record_structs.py  207 dumpData: > female_graph_marker: b''
record_structs.py  207 dumpData: > spells: [285389410, 285504276]
record_structs.py  207 dumpData: > femaleHeight: Rounder(0.0)
record_structs.py  207 dumpData: > femaleWeight: Rounder(0.0)
record_structs.py  207 dumpData: > body_biped_object: 0
record_structs.py  207 dumpData: > dismount_offset_z: Rounder(65.0)
record_structs.py  207 dumpData: > unarmed_reach: Rounder(0.0)
record_structs.py  207 dumpData: > male_data_marker: b''
record_structs.py  207 dumpData: > eyes: []
record_structs.py  207 dumpData: > female_available_hair_colors: []
record_structs.py  207 dumpData: > female_decapitate_armor: 0
record_structs.py  207 dumpData: > deceleration_rate: Rounder(0.0)
record_structs.py  207 dumpData: > maleHeight: Rounder(0.0)
record_structs.py  207 dumpData: > health_regen: Rounder(0.0)
record_structs.py  207 dumpData: > equip_type_flags: 0x00000000 (None)
patcher_dialog.py  265 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 183, in PatchExecute
  File "bash\basher\patcher_dialog.py", line 274, in _save_pbash
  File "bash\mod_files.py", line 287, in safeSave
  File "bash\mod_files.py", line 320, in save
  File "bash\brec\record_groups.py", line 260, in dump
  File "bash\brec\record_groups.py", line 249, in getSize
  File "bash\brec\record_groups.py", line 250, in <genexpr>
  File "bash\brec\record_structs.py", line 474, in getSize
  File "bash\brec\record_structs.py", line 609, in dumpData
  File "bash\brec\record_structs.py", line 194, in dumpData
  File "bash\brec\basic_elements.py", line 194, in dumpData
  File "bash\brec\common_subrecords.py", line 455, in pack_subrecord_data
TypeError: 'int' object is not iterable

Traceback (most recent call last):
  File "bash\gui\events.py", line 178, in _post
  File "bash\balt.py", line 815, in _conversation_wrapper
  File "bash\basher\patcher_dialog.py", line 183, in PatchExecute
  File "bash\basher\patcher_dialog.py", line 274, in _save_pbash
  File "bash\mod_files.py", line 287, in safeSave
  File "bash\mod_files.py", line 320, in save
  File "bash\brec\record_groups.py", line 260, in dump
  File "bash\brec\record_groups.py", line 249, in getSize
  File "bash\brec\record_groups.py", line 250, in <genexpr>
  File "bash\brec\record_structs.py", line 474, in getSize
  File "bash\brec\record_structs.py", line 609, in dumpData
  File "bash\brec\record_structs.py", line 194, in dumpData
  File "bash\brec\basic_elements.py", line 194, in dumpData
  File "bash\brec\common_subrecords.py", line 455, in pack_subrecord_data
TypeError: 'int' object is not iterable

XXX deprint

Drop later, a try here will be too expensive.