Ensure various arguments are integers
Python 3.10 no longer implicitly converts floats to ints when calling
stdlib methods or C extension methods, which causes calls that were
expecting its to fail.

Example traceback:

Traceback (most recent call last):
  File "c:\Users\Lojack\Desktop\wrye-bash\Mopy\bash\bash.py", line 292, in main
    _main(opts, wx_locale, wxver)
  File "c:\Users\Lojack\Desktop\wrye-bash\Mopy\bash\bash.py", line 363, in _main
    bashIni, bush_game, game_ini_path = _detect_game(opts, bash_ini_path)
  File "c:\Users\Lojack\Desktop\wrye-bash\Mopy\bash\bash.py", line 478, in _detect_game
    bush_game = _import_bush_and_set_game(opts, bashIni)
  File "c:\Users\Lojack\Desktop\wrye-bash\Mopy\bash\bash.py", line 508, in _import_bush_and_set_game
    retCode = _select_game_popup(game_infos)
  File "c:\Users\Lojack\Desktop\wrye-bash\Mopy\bash\bash.py", line 727, in _select_game_popup
    frame = SelectGamePopup(game_infos, retCode.set)
  File "c:\Users\Lojack\Desktop\wrye-bash\Mopy\bash\bash.py", line 639, in __init__
    HLayout(spacing=6, items=[
  File "c:\Users\Lojack\Desktop\wrye-bash\Mopy\bash\gui\layouts.py", line 228, in __init__
    super(HLayout, self).__init__(_wx.BoxSizer(_wx.HORIZONTAL), *args,
  File "c:\Users\Lojack\Desktop\wrye-bash\Mopy\bash\gui\layouts.py", line 186, in __init__
    self.add(item)
  File "c:\Users\Lojack\Desktop\wrye-bash\Mopy\bash\gui\layouts.py", line 208, in add
    self._sizer.Add(item, proportion=options.weight * csf(),
TypeError: Sizer.Add(): arguments did not match any overloaded call:
  overload 1: 'proportion' is not a valid keyword argument
  overload 2: argument 'proportion' has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'StaticText'
  overload 4: argument 1 has unexpected type 'StaticText'
  overload 5: argument 1 has unexpected type 'StaticText'
  overload 6: argument 1 has unexpected type 'StaticText'
  overload 7: argument 1 has unexpected type 'StaticText'
  overload 8: argument 1 has unexpected type 'StaticText'
  overload 9: argument 1 has unexpected type 'StaticText'

Under #619