Wrap accesses to MasterInfo.mod_info:
All fine and dandy - positive line count but the repetitive logic was
annoying to read everytime - reducing method occurrences also.
The rest is some nit from the launchers work, past and future, including
dropping unused imports.

Regression in merge patcher validation:

Traceback (most recent call last):
  File "bash\balt.py", line 1684, in __Execute
  File "bash\balt.py", line 515, in _conversation_wrapper
  File "bash\basher\mod_links.py", line 1020, in Execute
  File "bash\basher\mod_links.py", line 1101, in _execute_bp
  File "bash\gui\top_level_windows.py", line 196, in display_dialog
  File "bash\basher\patcher_dialog.py", line 143, in __init__
  File "bash\basher\gui_patchers.py", line 299, in GetConfigPanel
  File "bash\basher\gui_patchers.py", line 522, in _get_auto_items
  File "bash\patcher\base.py", line 121, in get_sources
  File "bash\patcher\base.py", line 126, in _validate_src
  File "bash\patcher\patchers\base.py", line 176, in _validate_mod
RuntimeError: MergePatchesPatcher: Oblivion.esm is not mergeable

From 4411d9860df311c6283df50cb45e7056d9441d0d

Mopy/bash/basher/__init__.py: regression in printing missing mods

More random nit:

Included is also some nit from launchers settings tab.