Decouple constants.py from wx
Very nasty bit of coupling laid bare by
f707b59c4036f90e8696565ad4253eceb41b7a93. While we were never saving
these constants into settings files (since they're only the default),
having our defaults dependent on wx constants that could change at any
time is not a good idea. The value I picked for the constant is
compatible with the one wx currently uses (wx.Point(-1, -1)), but that's
just an implementation detail. The real win is having this constant
under our control, so that we can decide if/when to break backwards
compat with it.

Under #190

Mopy/bash/game/skyrim/records.py:
TES5: Fix SOPM blowing up on dump

It's the darn 'Xs' syntax in structs again. That requires a default of a
bytestring, an integer will not do:

mod_io.pyo  377 packSub: <bash.brec.mod_io.ModWriter object at 0x000000001BF16F08>: Failed packing: NAM1, B2sB, (0, 0, 50)
record_structs.pyo  127 dumpData: Error dumping data:
Traceback (most recent call last):
  File "bash\brec\record_structs.pyo", line 125, in dumpData
  File "bash\brec\basic_elements.pyo", line 594, in dumpData
  File "bash\brec\mod_io.pyo", line 364, in packSub
error: argument for 's' must be a string

Took the opportunity to prefix and clean up, PEP8 where safe, etc.