Nit from load order refactoring and couple random fixups:
ret is a WizardReturn attribute (duh) - rest is random nit

Mopy/bash/wbtemp.py: Hacky fix for missing drive on WB boot - from:

https://discord.com/channels/537706885965676554/537710082755133460/1282857610550317237

I'm having an issue where Wrye Bash is looking at the wrong drive for a
file, and thus won't open [...] When I installed windows 10, Windows
assigned the E: letter to my storage drive, but I later changed it S:

Traceback (most recent call last):
  File "bash\bash.py", line 524, in main
  File "bash\bash.py", line 677, in main
  File "bash\barb.py", line 154, in backupsettings
  File "bash\wbtemp.py", line 176, in __enter
  File "bash\wbtemp.py", line 137, in new_temp_dir
  File "bash\wbtemp.py", line 92, in _get_global_dir
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\'

Mopy/bash/bush.py:
I think this is the intended behavior - I run across this while revising
boot for absorbing GameInfo.post_init in __init__ - probably from
c39d5d3a67df881a01c1213ac9277c9a6ded970f