Use scandir instead of walk in _list_store_dir:
So we cache the stat result and use it in creating new infos/calling
do_update on existing ones. Function calls went down on Windows:

Before: __init__.py 3537 init_stores: 1832896 function calls (1829087 primitive calls) in 0.986 seconds
After : __init__.py 3546 init_stores: 1825479 function calls (1822747 primitive calls) in 0.949 seconds

Note we expand on the use of dict introduced in
b341234be74c6f7910b3c3123e650c56cc122741 - solid #353 (#241 territory).

Changed to:

@@ -1659,4 +1659,11 @@ def _list_store_dir(self): # performance intensive
         file_matches_store = self.rightFileType
-        inodes = FNDict((n, {'cached_stat': x.stat()}) for x in os.scandir(
-            self.store_dir) if x.is_file() and file_matches_store(n := x.name))
+        inodes = FNDict()
+        with os.scandir(self.store_dir) as it:
+            for x in it:
+                try:
+                    if x.is_file() and file_matches_store(n := x.name):
+                        inodes[n] = {'cached_stat': x.stat()}
+                except OSError:
+                    deprint(f'Failed to stat {n} in {self.store_dir}', #XXX debug
+                            traceback=True)
         return self._diff_dir(inodes)

in hopes of addressing the 'description' bug (#689):

Traceback (most recent call last):
  File "bash\bash.py", line 524, in main
  File "bash\bash.py", line 692, in _main
  File "bash\basher\__init__.py", line 4193, in Init
  File "bash\bosh\__init__.py", line 3515, in init_stores
  File "bash\bosh\__init__.py", line 2095, in __init__
  File "bash\bosh\__init__.py", line 1571, in __init__
  File "bash\bosh\__init__.py", line 2260, in refresh
  File "bash\bosh\__init__.py", line 2466, in _refresh_bash_tags
  File "bash\bosh\__init__.py", line 671, in reloadBashTags
  File "bash\bosh\__init__.py", line 657, in getBashTagsDesc
AttributeError: 'NoneType' object has no attribute 'description'

but no error is thrown (what I suspect is scandir returns entries for
virtual files but then when we try to read the header we fail
(silently), header is left to None then boom).

hidden_dir should be hide dir - regression from parent.