Now it's CSME/CSFL:
record_structs.py  609 loadData: Error loading CSTY record and/or subrecord: (Skyrim.esm, 00003D)
  eid = DefaultCombatstyle
  subrecord = CSME
  subrecord size = 28
  file pos = 243863515
mod_links.py  114 Execute: Exception loading Skyrim.esm:
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 599, in loadData
    loader.load_mel(self, ins, sub_type, sub_size,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 664, in load_mel
    unpacked = ins.unpack(self._unpacker, size_, *debug_strs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\mod_io.py", line 374, in unpack
    return struct_unpacker(self.ins.read(size))
struct.error: unpack requires a buffer of 32 bytes
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 105, in Execute
    self._load_mod(dbg_inf, keepAll=False,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 86, in _load_mod
    modFile.load(True, **kwargs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 199, in load
    new_top = topClass(header, self.loadFactory, ins,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 675, in __init__
    super().__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 213, in __init__
    super().__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 160, in __init__
    super().__init__(loadFactory, ins, self._end_pos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 50, in __init__
    self._load_rec_group(ins, endPos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 226, in _load_rec_group
    grel = self._group_element(header, ins)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 233, in _group_element
    return None if rec_class is None else rec_class(header, ins,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 567, in __init__
    MreRecord.__init__(self, header, ins, do_unpack=do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 400, in __init__
    self.loadData(ins, ins.size, file_offset=file_offset)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 613, in loadData
    raise exception.ModError(ins.inName, f'{error!r}') from error
bash.exception.ModError: Skyrim.esm: error('unpack requires a buffer of 32 bytes')

See:
https://github.com/wrye-bash/wrye-bash/commit/42929b294b8146c8de2966453fdef13363d951df#commitcomment-89968612

> xEdit automatically truncates everything unless you explicitly tell it otherwise, e.g. like here: TES5Edit/TES5Edit#1039

https://github.com/TES5Edit/TES5Edit/blob/d971eb7112d8758b6327696754a61536ebb2a9d7/Core/wbDefinitionsTES5.pas#L7430-L7439

I meltruncated the last float but may need another solution.

record_structs.py  609 loadData: Error loading CSTY record and/or subrecord: (Skyrim.esm, 00003D)
  eid = DefaultCombatstyle
  subrecord = CSFL
  subrecord size = 20
  file pos = 243863573
mod_links.py  114 Execute: Exception loading Skyrim.esm:
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 599, in loadData
    loader.load_mel(self, ins, sub_type, sub_size,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 664, in load_mel
    unpacked = ins.unpack(self._unpacker, size_, *debug_strs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\mod_io.py", line 374, in unpack
    return struct_unpacker(self.ins.read(size))
struct.error: unpack requires a buffer of 32 bytes
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 105, in Execute
    @balt.conversation
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 86, in _load_mod
    modFile.load(True, **kwargs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 199, in load
    new_top = topClass(header, self.loadFactory, ins,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 675, in __init__
    super().__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 213, in __init__
    super().__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 160, in __init__
    super().__init__(loadFactory, ins, self._end_pos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 50, in __init__
    self._load_rec_group(ins, endPos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 226, in _load_rec_group
    grel = self._group_element(header, ins)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 233, in _group_element
    return None if rec_class is None else rec_class(header, ins,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 567, in __init__
    MreRecord.__init__(self, header, ins, do_unpack=do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 400, in __init__
    self.loadData(ins, ins.size, file_offset=file_offset)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 613, in loadData
    raise exception.ModError(ins.inName, f'{error!r}') from error
bash.exception.ModError: Skyrim.esm: error('unpack requires a buffer of 32 bytes')

same drill - 5f?