Installer.do_update:
One of the hardest things to grok in BAIN refresh was the decorator
projects_walk_cache. It was necessary in order not to re-walk the
project dir in case we just walked it in scan_installers_dir. Looking
at it now we should have been caching also the stat calls in that case,
but when this was introduced BAIN internals were so complicated that
this was not so obvious (performance here is anyway still WIP). Turns
out it is much simpler and probably just as 'fast' to call do_update
rather than trying to pass needs_update caches to refreshBasic. See
discussion in 8858cb7fb5955b46caad5ec6b1cdf44ff7e0d93d, but unlike
what I said there the pleasant surprise is that AFile can handle
folders alright - do_update is powerful enough and can be further
refactored to cater for fullRefresh. Note:

- the ancient fixme. What this was trying to convey is that actually
if you went ahead and renamed a file in a project containing another
file with large modification time the change would not be detected. The
workaround was to manually refresh the project. This was done for
efficiency, as the vast majority of the changes would be detected,
but now that computers are faster let's make this correct. For big
src_sizeCrcDate this would be slower but hey the system calls should
dwarf that (for big src_sCD) and anyway that's what the skipRefresh
flag is for. Now that we do the full check (should be more than enough
but can still give a false negative if we flip a byte on a file without
changing the modification time - hey, caching) we might as well drop the
calculations from _stat_tuple (or not, rather not).
- the common data structure format for cacl_crcs included the old crc -
cf (siz, _crc, date, asFile). I changed this to pass the asFile, and I
am still debugging it, but the benefits should be obvious.
- I reassign src_sizeCrcDate instead of clean/update - faster and
cleaner (also done for data_sizeCrcDate).

Fix for fullRefresh not getting the paths to ghosts

I had to treat plugins separately - no harm done on average and
fullRefresh will calculate their CRCs once at last.

Progress does not work correctly (never gives focus back to Bash) XXX???

@@ -3460,5 +3460,5 @@ def ShowPanel(self, canCancel=True, fullRefresh=False, scan_data_dir=False,
                 if not do_refresh:
-                    with balt.Progress(_('Scanning Packages...')) as progress:
-                        refresh_info = self.listData.scan_installers_dir(
-                            folders, files, fullRefresh, progress)
+                    #with balt.Progress(_('Scanning Packages...')) as progress:
+                    refresh_info = self.listData.scan_installers_dir(
+                        folders, files, fullRefresh, progress=bolt.Progress())
                     do_refresh = refresh_info.refresh_needed()

__init__.py 4271 RefreshData boot:
Rename Installer.modified attribute: 13379068 function calls (13352287 primitive calls) in 11.719 seconds
this                               : 13179209 function calls (13152391 primitive calls) in 11.780 seconds

__init__.py 4271 RefreshData tab in:
Rename Installer.modified attribute: 283719 function calls (274935 primitive calls) in 0.697 seconds
this                               : 496795 function calls (487975 primitive calls) in 0.580 seconds

Note that although calls went up for 'tab in' times are consistently
lower, and will become even more so with the scandir commit. Note also
that due to the fix for failed crcs calculations below the timimings
here should be even faster as I dropped the loop and append calls in
InstallerProject._refreshSource and used sum() instead of adding the
crcs - I just couldn't afford to repeat all the timings.

Fixup for failure of calc_crc:

...
bain.py  167 calc_crcs: Failed to calculate crc for M:\Steam\steamapps\common\Skyrim Special Edition Mods\Bash Installers\The really high-heeled Vanilla shoes and boots-27527-1-0-1563643115\01 Original TRHHVS\CalienteTools\BodySlide\ShapeData\Real high heels VampClothesBoots\Real high heels VampClothesBoots.osd - please report this, and the following traceback:
Traceback (most recent call last):
  File "bash\bosh\bain.py", line 163, in calc_crcs
FileNotFoundError: [Errno 2] No such file or directory: 'M:\\Steam\\steamapps\\common\\Skyrim Special Edition Mods\\Bash Installers\\The really high-heeled Vanilla shoes and boots-27527-1-0-1563643115\\01 Original TRHHVS\\CalienteTools\\BodySlide\\ShapeData\\Real high heels VampClothesBoots\\Real high heels VampClothesBoots.osd'

then:

Traceback (most recent call last):
  File "bash\gui\events.py", line 180, in _post
  File "bash\balt.py", line 705, in _conversation_wrapper
  File "bash\basher\__init__.py", line 4259, in RefreshData
  File "bash\balt.py", line 705, in _conversation_wrapper
  File "bash\basher\__init__.py", line 3463, in ShowPanel
  File "bash\bosh\bain.py", line 2093, in scan_installers_dir
  File "bash\bosh\bain.py", line 1553, in do_update
  File "bash\bolt.py", line 1660, in do_update
  File "bash\bosh\bain.py", line 1193, in _reset_cache
  File "bash\bosh\bain.py", line 1620, in _fs_refresh
TypeError: unsupported operand type(s) for +=: 'int' and 'str'

Under #336, #219, #353