Regression fixes - pytest 7.0.1:
Fix regression in List Plugins

Broke in fd791769caadbe56a82e43bc895dd22215f90c33:

Traceback (most recent call last):
  File "bash\balt.py", line 1786, in __Execute
  File "bash\basher\installer_links.py", line 950, in Execute
TypeError: can only concatenate str (not "Path") to str

TES4: Fix regression in Sort: Ingestibles

Broke in 802423a474da3e16631718de2ade72e3ed38383f.

ci: Bump pytest to 7.0.1

Just some minor bugfixes.

Utumno:

Mopy/bash/balt.py: Fixup for delinquent masters dialog:

Introduced in 94c8ba1d7e97c677109f00afaff70e257b259c3b - 'Continue
Despite Errors' would return an empty tuple instead of True - some
whitespace fixes also - I think I prefer the star here. Compliments
of 543 testing.

Co-authored-by: MrD <the.ubik@gmail.com>