Ghosting fixups in Oblivion esm swap:
So Oblivion.esm active, Oblivion_1.1.esm inactive and ghosted - on
calling file_info_rename_op(*args_dict) to rename Oblivion_1.1.esm
to Oblivion.esm the ModInfo.get_rename_paths will add .ghost - the
_active_wip cache would be updated correctly but then cached_lo_save_all
would set ghostify = dict.fromkeys(ldiff.act_new, False) - now
Oblivion.esm was already active before, so not in act_new, so it would
never be unghosted. The UI would not reflect that, but on next restart
Bash would crash on boot with:

Traceback (most recent call last):
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bash.py", line 531, in main
    _main(opts, wx_locale, wxver)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bash.py", line 696, in _main
    frame = bapp.Init() # Link.Frame is set here !
            ^^^^^^^^^^^
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\__init__.py", line 4277, in Init
    self.InitData(progress)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\__init__.py", line 4304, in InitData
    bosh.modInfos = bosh.ModInfos()
                    ^^^^^^^^^^^^^^^
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bosh\__init__.py", line 2127, in __init__
    raise FileError(bush.game.master_file,
bash.exception.FileError: Oblivion.esm: File is required, but could not be found

which also means that having the master esm ghosted needs handling (we
should not crash just unghost). To address this correctly we would need
rename refactoring done so wait for next merge - meanwhile I added code
for this particular case. Note that notify_bain would never be fed
the altered path - will have to wait for #353. The solution involves
adding some of the rename_operation machinery to the info. The last time
one failed to notice it was 4dfa03edf4ba925728abfdb554efed8429f0b598 but
the latter seems broken too as setGhost would bypass the master esm even
for ghostify False.