Fix a case in startup error handling
If an exception occurs when importing `bolt`, the code used to give a
bugdump errors when it tries to access `bolt.scandir`, resulting in
the following traceback, which hides the original traceback.

Launching Wrye Bash 307 in debug mode
fail bash\bolt.py
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 89, in <module>
    bash.main(opts)
  File "bash\bash.py", line 181, in main
    _import_bolt(opts)
  File "bash\bash.py", line 57, in _import_bolt
    msg = u'\n'.join([dump_environment(), u'', u'Unable to load bolt:',
  File "bash\bash.py", line 162, in dump_environment
    if bolt.scandir is not None:
AttributeError: 'NoneType' object has no attribute 'scandir'

Infernio: Dropped an unused local import of locale in the vicinity.