[!]Some Path pruning
Last minute hence the !

Mopy/bash/basher/dialogs.py:
Mopy/bash/basher/mod_links.py:
Mopy/bash/basher/saves_links.py:
renames 'data'

Mopy/bash/basher/settings_dialog.py:

Regression in settings dialog

When a language not present in dict would appear it would blow with

Traceback (most recent call last):
  File "bash\balt.py", line 1817, in __Execute
	self.Execute()
  File "bash\basher\misc_links.py", line 409, in Execute
	SettingsDialog.display_dialog()
  File "bash\gui\top_level_windows.py", line 175, in display_dialog
	with cls(*args, **kwargs) as dialog:
  File "bash\basher\settings_dialog.py", line 61, in __init__
	self._tab_tree = TreePanel(self, _settings_pages, _page_descriptions)
  File "bash\gui\combos.py", line 250, in __init__
	u'%s/%s' % (page_name, subpage_name), u''))
  File "bash\basher\settings_dialog.py", line 492, in __init__
	in all_langs]
TypeError: <lambda>() takes exactly 1 argument (0 given)
__init__.py 1453 refresh: Failed to load oblivion2.bsa: Magic wrong: got 'del ', expected 'BSA\x00'
Traceback (most recent call last):
  File "bash\gui\events.py", line 165, in _post
	result = listener(*listener_args)
  File "bash\gui\multi_choices.py", line 76, in _set_tooltip
	if cb.GetClientSize()[0] < cb.GetTextExtent(cb.GetValue())[0] + 30:
RuntimeError: wrapped C/C++ object of type ComboBox has been deleted
Traceback (most recent call last):
  File "bash\gui\events.py", line 165, in _post
	result = listener(*listener_args)
  File "bash\gui\multi_choices.py", line 76, in _set_tooltip
	if cb.GetClientSize()[0] < cb.GetTextExtent(cb.GetValue())[0] + 30:
RuntimeError: wrapped C/C++ object of type ComboBox has been deleted
Traceback (most recent call last):
  File "bash\gui\events.py", line 165, in _post
	result = listener(*listener_args)
  File "bash\gui\multi_choices.py", line 76, in _set_tooltip
	if cb.GetClientSize()[0] < cb.GetTextExtent(cb.GetValue())[0] + 30:
RuntimeError: wrapped C/C++ object of type ComboBox has been deleted
Traceback (most recent call last):
  File "bash\gui\events.py", line 165, in _post
	result = listener(*listener_args)
  File "bash\gui\multi_choices.py", line 76, in _set_tooltip
	if cb.GetClientSize()[0] < cb.GetTextExtent(cb.GetValue())[0] + 30:
RuntimeError: wrapped C/C++ object of type ComboBox has been deleted

as defaultdict needs a no-argument factory
Not sure if the RuntimeError is due to this or not - still was gone now