Nit in Status bar:
One of the things I had to re-understand is that 'buttons' was a class
variable holding all the available links *and* an instance variable
containing the visible buttons - renamed. Also, in the drag event
handling, there is a mouseEvent.EventObject property that points to the
button being dragged - one less use of wx_id_ (yey). Finally in
UnhideButton the logic was complicated - simplified but all these
GetLink calls only mean we need a better data structure here (actually
I started this cause the StatusBar_Button is-not-a Link (menu) - we
should make it an _AComponent, wrapping the button, but this needs quite
some effort) - see next commit. Note also that:

balt.py 2344 OnDragEnd: Exception while handling mouse up on button
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\balt.py", line 2341, in OnDragEnd
    button._native_widget.ReleaseMouse()
wx._core.wxAssertionError: C++ assertion ""!wxMouseCapture::stack.empty()"" failed at ..\..\src\common\wincmn.cpp(3426) in wxWindowBase::ReleaseMouse(): Releasing mouse capture but capture stack empty?

is always raised in a normal DnD operation - still need to keep it for
an abnormal termination?