Regression - Karma menu item raising AbstractError:
Introduced in eba53f93bea72445a9fdac56c82172baeb2ab837.
The PeopleLink.AppendToMenu() appended to menu the ChoiceLink which does
not override ItemLink.Execute():

Traceback (most recent call last):
  File "bash\balt.py", line 2375, in Execute
    raise AbstractError
bash.bolt.AbstractError: Abstract section called.

Reversing the order just appended the CL first instead of last - plus
the `subMenu = super(...)` call returned not wx.Menu but a wx.MenuItem:

Traceback (most recent call last):
  File "bash\balt.py", line 1836, in DoItemMenu
    self.itemMenu.PopupMenu(self,Link.Frame,selected)
  File "bash\balt.py", line 2293, in PopupMenu
    link.AppendToMenu(menu,parent,*args)
  File "bash\balt.py", line 2512, in AppendToMenu
    link.AppendToMenu(menu, window, data)
  File "bash\balt.py", line 2442, in AppendToMenu
    self.__class__.kind)
  File "C:\_\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 11490, in __init__
    _core_.MenuItem_swiginit(self,_core_.new_MenuItem(*args, **kwargs))
TypeError: in method 'new_MenuItem', expected argument 1 of type 'wxMenu *'

Solved by bringing People_Link closer to object - this resulted in
having to use MI with ItemLink in its subclasses.

Also People_Karma was made again to submenu. This was introduced in
6fbec32fbecbc72f72c5dd908e8d12a503fde502
but you can't see it till c84db2ca948a0011599ce0e52ddedbdb9714a29f
wheere People List Add... works again.

Consider those mixins deprecated.