List.RefreshUI():
Under #163.
After 4 months of work I am finally able to move this beast to base.
This opens the way to control refresh from a central point.
Needless to say this will end up in UIList - but now we are at the heart
of Tank vs List dichotomy and those two won't give up without a fight.

Renamed RefreshUI of other classes - RefreshUI is very central and
ini controls and Panel refreshes must not share the same name.

The Tank UpdateItem(s) win hands down as they really permit more flexible
(read focused) updates (methinks) - check the (naive) attempt to only
refresh renamed saves - blows with:

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 1990, in OnLabelEdited
    self.RefreshUI(renamed) ### (ut)TEST
  File "bash\basher\__init__.py", line 1993, in RefreshUI
    super(SaveList, self).RefreshUI(files, detail)
  File "bash\basher\__init__.py", line 399, in RefreshUI
    self.PopulateItem(file_, selected=selected)
  File "bash\basher\__init__.py", line 2001, in PopulateItem
    itemDex = self.items.index(itemDex)
ValueError: bolt.Path(u'C:\\Users\\MrD\\Documents\\My Games\\Oblivion\\Saves\\SI\\oio___.ess') is not in list

Passing a string _or_ a list _or_ an item is totally non OO and will be
squashed. Replaced all instances passing with single items lists.
RefreshUI is ugly - better to be reminded of this fact when using it.

EDIT: notice I needed to call SortItems() separately - this is to be
amended.

Signed-off-by: MrD <the.ubik@gmail.com>