Downgrade pyinstaller to 6.9.0 and various regression fixups:
6.10.0+ cause the following traceback on startup when restoring a backup
(on Windows at least):

```
Traceback (most recent call last):
  File "bash\bash.py", line 616, in _main
  File "PyInstaller\loader\pyimod02_importers.py", line 457, in exec_module
  File "bash\bosh\__init__.py", line 42, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 457, in exec_module
  File "bash\bosh\bsa_files.py", line 43, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 457, in exec_module
  File "lz4\block\__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'lz4.block._block'
```

Try upgrading it again when we move to a newer version of Python.

Co-authored-by: sibir <ine.sibir@gmail.com>

Fix regression in getModList

Introduced in f946908162f153a295854fb3078f446684f2f295.
Unsure if this is the best way to fix it, it looks kind of ugly...

Utumno:

Use the dictionary to get the active mods - looks less ugly :P (this
is in preparation of __setUI removal - plus magic number pruning - we
should be using constants for these like ACTIVE = 0 etc - note also in
belt.WryeParser.fn_get_plugin_status those magic numbers have different
meaning - later)

Fix installation of packages containing default Bash tweaks:

Should be - could be made less hacky - the deeper reason we do this is,
of course, ghosts - cf @sibir's investigation (thanks!):

I was able to replicate the default INI tweaks bug by attempting to
install an INI tweak with the same name as a default INI tweak, the
source is b8d9e0afd84a29bc473582063b87523f46b57ae5. However, the parent
commit produces a different traceback that originates from
70fe06101ad20086c73dfcbdb7025ce5cb557951 -> yep that one.

Fix regression in MasterLists._sort_masters_first:

Items are integers here so this blew with:

 ValueError: 0 type is <class 'int'> - a str is required

on accessing minfs[fn] - I passed the store in in this case. Regressed
in cb2cdea86dcb25666142d1856fed0abdfcb1ee99 (thanks @sibir), which
made sort_masters_key single use - noted that here and changed the param
name to minf which is reserved for Master/ModInfo inputs. Note that
.cached_type is final, so this hacky double type handling is as centralized
as possible.

Move RUI arguments logic from refresh_and_warn to propagate_refresh:

Fixes a bug introduced or rather revealed by
73a69314311b61575d6240bf51a101bd6e13127d - propagate_refresh is used
for real now and I did not take into account the empty RefrData values
of ui_refresh. This commit finalizes the interaction of Frame and UIList
in propagate_refresh. We should flip the RUI rdata default to True from
None - later.

Mopy/bash/basher/settings_dialog.py:
stray import probably from d83b570abe9ccd2c0a098db7ce9fe4510c9f9b90

Co-authored-by: MrD <the.ubik@gmail.com>
Co-authored-by: sibir <ine.sibir@gmail.com>