[!]Screen_ConvertTo drop refresh(True):
This seemingly straightforward pruning of another refresh(True) kept
raising (not every time at that):

Traceback (most recent call last):
  File "C:\...\Mopy\bash\balt.py", line 1718, in __Execute
    self.Execute()
  File "C:\...\Mopy\bash\basher\misc_links.py", line 124, in Execute
    self.window.RefreshUI(bosh.screen_infos.refresh(rinf))
  File "C:\...\Mopy\bash\balt.py", line 789, in RefreshUI
    self.__gList.RemoveItemAt(self._get_uil_index(d))
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Mopy\bash\balt.py", line 1325, in _get_uil_index
    return self.__gList.FindIndexOf(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Mopy\bash\gui\list_ctrl.py", line 279, in FindIndexOf
    return self._native_widget.FindItem(-1, self._item_itemId[item])
                                            ~~~~~~~~~~~~~~~~~^^^^^^
KeyError: FName('dd-08.png')

Turns out a `@conversation` was needed - stashing a [!] just to draw
attention as the fix was not obvious, and might bite us again now we
don't issue refresh(True)/RUI(None), which would be immune to that.

Move unhide_wildcard to the stores:

Was static now a classmethod, so belongs here - absorbed plugin_wildcard.