WIP nit around bug reports:
games_lo:
Traceback (most recent call last):
  File "bash\bash.py", line 470, in main
  File "bash\bash.py", line 643, in _main
  File "bash\basher\__init__.py", line 3758, in Init
  File "bash\bosh\__init__.py", line 3598, in init_stores
  File "bash\bosh\__init__.py", line 2305, in __init__
  File "bash\bosh\__init__.py", line 1533, in __init__
  File "bash\bosh\__init__.py", line 2346, in refresh
  File "bash\bosh\__init__.py", line 2173, in _modinfos_cache_wrapper
  File "bash\bosh\__init__.py", line 2672, in refreshLoadOrder
  File "bash\load_order.py", line 364, in refresh_lo
  File "bash\load_order.py", line 309, in _update_cache
  File "bash\games_lo.py", line 293, in get_load_order
  File "bash\games_lo.py", line 312, in _cached_or_fetch
  File "bash\games_lo.py", line 880, in _fetch_load_order
ValueError: list.remove(x): x not in list

Turns out the algorithm was correct, but plugins.txt had duplicates
which we did not expect and which caused it to blow up — fixed in the
next merge, as it fired up a thorough review of games_lo. Here we
simplify _fetch_load_order and change parse_modfile to not accept
lines containing just a star.

brec:

> the bashed patch is specifically carrying over the landscape records
> of Unique Landscapes.esp over its respective patches, causing a pretty
> noticeable void within the castle added by Order of the Dragon

https://discord.com/channels/537706885965676554/537710082755133460/1510964426088382534

Unfortunately this is out of scope for now - we need a proper bug report
on github