Skip packages that don't load from Installers.dat:
Note change of behavior - loading of Installers.dat will now proceed.
Added Debug prints for packages that failed to load.

See also - Drop support for older Bash settings files #253. Triggered
by debugging Dubious's report on WF17 Installers.dat not loading in
WB307 - see:

https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=172508

Turns out a single package (Fallschirmjager-49266-1.zip) had
fileSizeCrc[0] was string not unicode and blew as it contained
germnan umlauts:

Traceback (most recent call last):
  File "bash\bosh\bain.py", line 304, in __setstate__
    self.__setstate(values)
  File "bash\bosh\bain.py", line 341, in __setstate
    dest_scr = self.refreshDataSizeCrc()
  File "bash\bosh\bain.py", line 664, in refreshDataSizeCrc
    Installer._silentSkipsStart) or fileLower.endswith(
UnicodeDecodeError: 'ascii' codec can't decode byte 0x84 in position 81: ordinal not in range(128)

('Fallschirmjager\\Meshes\\armor\\headgear\\Fallschirmjager\\ArmorCombat M38 Fallschirmj\x84ger Helmet.nif', 14113, 3943809015L)

See:

https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=172623
https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=172639

I decided not to add code for checking if fileSizeCrc has stings in it.
Patching __setstate__ to not blow Installers.dat loading on a single
package error seems the right thing to do here.

Under #219
Under #376