Regression: Fix Screenshots tab failing to load
Introduced in f1075eab9c78d387e604339c09481c82059e6dbb, due to a bad
cherry-pick.

__init__.py 3484 __init__: Error constructing 'Screenshots' panel.
Traceback (most recent call last):
  File "bash\basher\__init__.py", line 3476, in __init__
    item = panel(self)
  File "bash\basher\__init__.py", line 3161, in __init__
    super(ScreensPanel, self).__init__(parent)
  File "bash\basher\__init__.py", line 251, in __init__
    super(BashTab, self).__init__(parent, isVertical)
  File "bash\basher\__init__.py", line 212, in __init__
    keyPrefix=self.keyPrefix, panel=self)
  File "bash\balt.py", line 1143, in __init__
    self.PopulateItems()
  File "bash\balt.py", line 1257, in PopulateItems
    self.SortItems()
  File "bash\balt.py", line 1492, in SortItems
    items = self._SortItems(column, reverse)
  File "bash\balt.py", line 1538, in _SortItems
    for lamda in self._extra_sortings: lamda(self, items)
  File "bash\basher\__init__.py", line 3051, in _order_by_number
    regex = re.compile(u'(.*?)(\d*)' + self.__ext_group + u'$')
NameError: global name 're' is not defined