Regression in patch log:
Traceback (most recent call last):
  File "bash\balt.py", line 1796, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\patcher_dialog.py", line 211, in Execute
    patchFile.buildPatch(log,SubProgress(progress,0.8,0.9))#no speeding needed/really possible (less than 1/4 second even with large LO)
  File "bash\patcher\patch_files.py", line 335, in buildPatch
    self._log_header(log, self.fileInfo.name.s)
  File "bash\patcher\patch_files.py", line 71, in _log_header
    log.setHeader(u'= ' + patch_name.s + u' ' + u'=' * 30 + u'#', True)
AttributeError: 'unicode' object has no attribute 's'

Introduced in d4b8b99974fde6c436c27fc2c6c672fa87eb737a
I really _hate_ patchName