Squashed version of 15-wx3-upgrade
commit 27e0df58e5d32ed827b721aef224d5b38e43f0c2
Author: MrD <the.ubik@gmail.com>
Date:   Fri Oct 18 23:53:46 2019 +0300

    FFF HtmlCtrl(wx.Window) -> HtmlCtrl(object):

    Maybe not the best names and do we really need that control? Or could we
    attach stuff to `parent`?

    Needs testing - then

    fixup! Rewrite balt.HtmlCtrl, drop iewin

commit 05644111389c54e91ad9042a97840ec342a81fe2
Author: MrD <the.ubik@gmail.com>
Date:   Sat Jun 1 18:01:04 2019 +0300

    Disposing the Progress window

     - Destroy does not do the trick still appears behind the Refreshing
    Installers one... (???)

    Another attempt for a fixup:

    Mopy/bash/bosh/bain.py:
    @@ -1731,2 +1731,3 @@ def refresh_installer(self, package, is_project, progress,
             installer.refreshBasic(progress, recalculate_project_crc=_fullRefresh)
    +        progress(1.0, _(u'Done'))
             if do_refresh:

     - progress window for project did not disappear immediately (??)
    This does not always do the trick either............

    Mopy/bash/bolt.py: Progress(object)

commit 0b605b6ed4db4bd47bee8d9b4a82f8f3554d5d81
Author: Infernio <infernio@icloud.com>
Date:   Wed Oct 9 15:46:23 2019 +0200

    localize: Clean up new methods

    PEP8's the methods and their names, and general cleanup.

    Note that I went a bit ballistic with _findAllBashModules and
    dump_translator. They only have one usage and it's *extremely* rare, so
    I dropped caches, inlines, optional parameters and more - when in doubt,
    leave it out, YAGNI and all that :)

    Also tightens three except: statements, bringing us down to 58 in total.

commit 292a7917e44a91fee63f18ce4bb0a3e9243f2298
Author: Infernio <infernio@icloud.com>
Date:   Wed Oct 9 14:10:17 2019 +0200

    Move l10n-related code from bolt to localize

    Makes bolt a bit less of a kitchen sink. Note that the code is really
    ugly, full of except: pass and does not conform to PEP8 - will tidy up
    in next commit.

commit 3f3bbfbb9fbba7dd9b675f08c7ad9158c35d2c90
Author: Infernio <infernio@icloud.com>
Date:   Sun Oct 6 17:49:43 2019 +0200

    Move localization setup code into new module

    bash.py is starting to get really bloated, so let's break some of that
    complexity out of there. Creates a new top-level module called
    localize.py (localization.py looked too similar to initialization.py).
    Some open TODOs:

    - The _wx param is ugly. Alternative would be a local import of bash,
      also ugly. Another alternative would be moving _import_wx into
      localize.py, but that doesn't really belong here.
    - Potentially moving some other localization-related stuff into this
      module - e.g. bolt.formatDate/unformatDate and bolt.dumpTranslator -
      would also help make bolt less of a kitchen sink.

    Note: Since doing this does not break dev, this can stay a separate
    commit in an eventual wx3 branch merge.

commit b37f28e37a51372bb08f3b49f764e21f503611e0
Author: MrD <the.ubik@gmail.com>
Date:   Sat Jun 1 23:23:28 2019 +0300

    Failing to unpickle settings due to _gdi not being resolved as a module

    See https://stackoverflow.com/a/13398680/281545

commit 8b2fcb3651c5c5bc09937c1d26d4845918a555e4
Author: Infernio <infernio@icloud.com>
Date:   Thu Sep 12 16:36:35 2019 +0200

    [!]Update to wxPython 3.0.2.0, drop comtypes

    Included edit to build.py here.
    Also increased recommended Python version to 2.7.16.

    Hacky workaround for setCancel crash

    Destroys the dialog and creates a similar-looking one with the correct
    PD_CAN_ABORT flag set. This is probably the solution we'll have to end
    up going with if we want to keep the native ProgressDialog (which we
    *really* do, some people have reported *massive* speedups because of it).

    Avoid cmd prompts popping up in standalone build

     # Whoops, forgot to pass in startupinfo.

    [!]Rewrite locale handling entirely

    Extremely dangerous and completely untested commit that reworks nearly
    the entire early boot procedure. Couldn't test it yet since I don't have
    a Windows PC right now. Highlights include:

    - moved initTranslator from bolt into bash and merged it with our
      half-baked wx locale code there
    - bolt no longer does anything scary on import, so dropped
      _import_bolt
    - Moved os.chdir, deprint setup and bugdump creation into new
      _early_setup method
    - Changed a whole bunch of print statements to deprint ones now that
      deprint is set up way earlier in the boot process

    Drop bolt.formatInteger

    We were only using this for aesthetic purposes, and we weren't doing it
    consistently anyways. This allows us to drop setlocale entirely.
    Seems to finally avoid the wx locale crash, based on feedback from
    Discord.

    Co-authored-by: MrD <the.ubik@gmail.com>

commit 6660c52c2a0039a0563daa5f8097786542b0e81a
Author: nycz <pyntix@gmail.com>
Date:   Fri Jun 23 13:29:54 2017 +0200

    Rewrite balt.HtmlCtrl, drop iewin

    Infernio: Squashed commit and edited so that it doesn't break dev,
    consists of the following:

    WIP Replace iewin with webview and rewrite frames.py

    Emphasis on WIP! Still a lot of room for improvements.

    Finally get rid of the comtypes dependency by dumping iewin and using
    wx's webview instead. Also make HtmlCtrl have a fallback non-html mode
    in case the user don't have the Webkit dependencies necessary for
    the webview. (Right now that is handled mostly outside the HtmlCtrl,
    messy)

    frames.py also gets a facelift in the process since it is the only place
    right now that uses HtmlCtrl. Improvements include:
        * DocBrowser not being bugged (couldn't create new readmes before)
        * less unnecessarily confusing interface in ModChecker (eg. buttons that
        depended on other buttons' state yet not showing this to the user)
        * hopefully less incomprehensible code
        * getting rid of most of the wx imports, altho I'm going for all of
        them

    Wrap event binding for frames.py

    Follow-up for 531679d37d6c50cfc030b9c462f44250bcfab7a0, spreads
    set_event_hook throughout frames.py since later commits depend on that.

    Backport my finished HtmlCtrl

    From the inf-wx-begone branch, this is the functional WebView-based
    HtmlCtrl, applied to the doc browser, mod checker and WryeLog - in other
    words, to all places where WB displays HTML.

    Note that this assumes we will migrate to wx 2.9+, since this
    implementation won't work on 2.8 at all.

    HtmlCtrl: support opening new windows and tabs...

    ...by opening them in the user's regular browser instead :P
    Not the nicest solution - see also the TODO in here - but the previous
    behavior was also less than ideal - it just ignored the click on the
    link. Also need to add this to the wx-begone branch.

    Co-authored-by: Infernio <infernio@icloud.com>

commit b4d592c2a0229ba42f9cececbeb155c36797c829
Author: Infernio <infernio@icloud.com>
Date:   Wed Oct 9 22:14:30 2019 +0200

    Some work towards wxPython 3.0.2.0

    Ellipsize overly long messages in progress dialogs

    Needed in wx3, otherwise the progress dialog will keep resizing itself,
    which is *very* ugly to look at. A pretty hacky solution, since this
    won't hide the resizing for displays smaller than 1080p.

    Use pngcrush to avoid iCCP warning

    This implements it for wizards, followup commit does the same for
    FOMODs.
    Also added a licenses.txt file to the Mopy/bash/compiled folder to
    satisfy any requirements for attribution.

    Add pngcrush executable

    This is pngcrush 1.8.11 32 bit from
    https://sourceforge.net/projects/pmt/files/pngcrush-executables

    It's the last version that a windows executable was uploaded for, 1.8.12
    and 1.8.13 do not have official executables so we'd have to build our
    own.

    TODO: Once we upgrade everything to 64 bit (CBash and LOOT are
    stopping us BTW), we should swap this for the 64 bit version as
    well, I guess.

    First implementation for wizards

    - Only wizards
    - Only for archives (projects should be fixed by the author)
    - Runs on all PNGs (seems to be *really* slow)
    - Fixes the issue, however

    Stuck it into archives.py right now, but that's not the right place IMO.

    Skip PNGs that don't have incorrect profiles

    Speeds it up *significantly*, making it pretty much instant for working
    PNGs.

    Delay progress dialog when unpacking to project

    Under wx3, it would shove itself over any warning messages / rename
    dialogs we showed. This wasn't really a *problem*, since the user could
    just move the progress dialog out of the way, but it was annoying. This
    is a fairly painless fix that just asks the questions first and then
    creates the progress dialog.

    Under # 15 <--- RRR
    Closes # 458 <--- RRR

    Co-authored-by: MrD <the.ubik@gmail.com>

commit 48eebdd7a3ac915f461b0d856a16bce1970681e1
Author: MrD <the.ubik@gmail.com>
Date:   Sat Jun 1 18:31:04 2019 +0300

    Hacky half fix for Cancel while refreshing projects not being respected:

    So start on Installers tab > Cancel on loading data> wait for pickle
    to load (can't really cancell this > go to mods tab > go back to Installers
    tab > no refresh triggered !!

    Then this works as expected - interupts the loading then going to another
    tab and back retriggers the refresh

    Arghhh -> time to rewrite progress handling

commit 6f95fe2149c7776f52da3d57eeaeaf872bf73e80
Author: MrD <the.ubik@gmail.com>
Date:   Mon Oct 14 14:35:23 2019 +0300

    Hacky fix for version being None in status bar buttons:

    Wrye Bash encountered an error.
    Please post the information below to the official thread at
    https://afkmods.com/index.php?/topic/4966-wrye-bash-all-games
    or to the Wrye Bash Discord at
    https://discord.gg/NwWvAFR

    Traceback (most recent call last):
      File "bash\bash.py", line 193, in main
        _main(opts)
      File "bash\bash.py", line 377, in _main
        app.Init() # Link.Frame is set here !
      File "bash\basher\__init__.py", line 4030, in Init
        frame = BashFrame() # Link.Frame global set here
      File "bash\basher\__init__.py", line 3684, in __init__
        self.SetStatusBar(BashStatusBar(self))
      File "bash\balt.py", line 2858, in __init__
        self.UpdateIconSizes()
      File "bash\basher\__init__.py", line 3569, in UpdateIconSizes
        self._addButton(link)
      File "bash\balt.py", line 2873, in _addButton
        gButton = link.GetBitmapButton(self)
      File "bash\basher\app_buttons.py", line 203, in GetBitmapButton
        window, self.images[idex].GetBitmap(), onRClick)
      File "bash\basher\app_buttons.py", line 87, in GetBitmapButton
        tooltip=self.sb_button_tip)
      File "bash\basher\app_buttons.py", line 135, in sb_button_tip
        return self._tip + u' ' + self.version
      File "bash\basher\app_buttons.py", line 125, in version
        version = self.exePath.strippedVersion
      File "bash\bolt.py", line 805, in strippedVersion
        version = list(self.version)
    TypeError: 'NoneType' object is not iterable

    Example files from debug print added:

    ------------------------------ Mopy/bash/bolt.py ------------------------------
    index 08ce2862b..1574fec9b 100644
    @@ -600,3 +600,7 @@ def version(self):
             from env import get_file_version
    -        return get_file_version(self._s)
    +        version_ = get_file_version(self._s)
    +        if version_ is None:
    +            print u'%s version is None' % self.s
    +            version_ = ()
    +        return version_

    C:\GAMES\TESIV\Oblivion\Tools\TES4Edit_3_0_15_EXPERIMENTAL-11536\TES4Edit.exe version is None
    C:\GAMES\TESIV\Oblivion\Tools\TES4LODGen_3_0_15_EXPERIMENTAL-15781\Tes4LodGen.exe version is None

    From the discussion in 45ca86ae4e15c850f7225fb19631c702bb8e0a03 turns
    out that pywin 225 blows for me but not for Infernio
    Those dll issues remind the situation with loot that blows for
    some people but not for others - for now let's limit pywin and
    patch the linux method to return an empty tuple instead of None

    Mopy/bash/env.py: remove redundant parentheses warn