Couple regressions from tweak pooling
MERGE/SCAN ERROR: Oblivion.esm
Traceback (most recent call last):
  File "bash\gui\events.pyo", line 165, in _post
  File "bash\balt.pyo", line 871, in _conversation_wrapper
  File "bash\basher\patcher_dialog.pyo", line 176, in PatchExecute
  File "bash\patcher\patch_files.pyo", line 247, in scanLoadMods
  File "bash\patcher\base.pyo", line 79, in scan_mod_file
  File "bash\patcher\patchers\base.pyo", line 127, in scanModFile
  File "bash\patcher\patchers\multitweak_assorted.pyo", line 442, in wants_record
  File "bash\patcher\patchers\multitweak_assorted.pyo", line 365, in wants_record
AttributeError: 'MreWeap' object has no attribute 'obme_record_version'

May also fix one of the potion weight tweaks having changed behavior, I
noticed it had no tweak_read_classes assigned.

Mopy/bash/game/skyrim/records.py:
Minor fixup for xEdit decoding

Purely aesthetic