Added plugin specific INI support
Fix for 'ordered' traceback:

Reported:
http://forums.bethsoft.com/topic/1509287-wipz-wrye-bashexp-skyrim-patcher-update-thread-2/?p=24037188

    Traceback (most recent call last):
      File "Wrye Bash Launcher.pyw", line 88, in <module>
        bash.main()
      File "bash\bash.py", line 465, in main
        frame = app.Init() # Link.Frame is set here !
      File "bash\basher\__init__.py", line 4342, in Init
        self.InitData(progress)
      File "bash\basher\__init__.py", line 4373, in InitData
        bosh.modInfos.refresh()
      File "bash\bosh.py", line 4243, in refresh
        hasMissingStrings = self.refreshMissingStrings()
      File "bash\bosh.py", line 4271, in refreshMissingStrings
        if fileInfo.isMissingStrings():
      File "bash\bosh.py", line 3358, in isMissingStrings
        return modInfos.isMissingStrings(self.name)
      File "bash\bosh.py", line 4676, in isMissingStrings
        iniPaths = [ModInfo(self.dir,name).getIniPath() for name in modInfos.ordered]
    AttributeError: ModInfos instance has no attribute 'ordered'

This commit should be SQUASHED with 77f0963feb2d938ea3210952b7f8e17f8e1d35ea:
    Added plugin specific INI support

so the later does not raise !

@@ -3379,3 +3379,3 @@ def getStringsPaths(self,language=u'English'):
             if bush.game.fsName == u'Skyrim':
-                iniPaths = [ModInfo(self.dir,name).getIniPath() for name in modInfos.ordered]
+                iniPaths = [ModInfo(self.dir,name).getIniPath() for name in modInfos.activeCached]
                 iniFiles = [IniFile(iniPath) for iniPath in iniPaths if iniPath.exists()]
@@ -4669,3 +4669,3 @@ def isMissingStrings(self,modName):
             if bush.game.fsName == u'Skyrim':
-                iniPaths = [ModInfo(self.dir,name).getIniPath() for name in modInfos.ordered]
+                iniPaths = [ModInfo(self.dir,name).getIniPath() for name in modInfos.activeCached]
                 iniFiles = [IniFile(iniPath) for iniPath in iniPaths if iniPath.exists()]