loot_parser: Gracefully fail on invalid lists
E.g. if the masterlist/userlist file contains nothing but a long string
of random characters, that will be parsed as a single, long YAML string
instead of the dict we are expecting, leading to cryptic tracebacks like
this:

Traceback (most recent call last):
  File "bash\bash.py", line 258, in main
  File "bash\bash.py", line 350, in _main
  File "bash\bosh\__init__.py", line 3623, in initBosh
  File "bash\bosh\loot_parser.py", line 90, in __init__
  File "bash\bosh\loot_parser.py", line 102, in _refresh_tags_cache
  File "bash\bosh\loot_parser.py", line 166, in load_lists
  File "bash\bosh\loot_parser.py", line 690, in _parse_list
AttributeError: 'str' object has no attribute 'get'

Closes #604