Regression: restore settings was broken:
Introduced in 3c3658d9517741e79470bff4a9e2a9d9e9487221
bash.extra is no more:

Traceback (most recent call last):
  File "bash\balt.py", line 2346, in __Execute
    self.Execute()
  File "bash\balt.py", line 1574, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\settings_links.py", line 106, in Execute
    with balt.BusyCursor(): backup.Apply()
  File "bash\barb.py", line 282, in Apply
    opts, args = bash.opts, bash.extra
AttributeError: 'module' object has no attribute 'extra'