ModInfo.isMissingStrings WIP - debug prints for bsas:
Note the first thing ModInfos implementation did was getting the
ModInfo.
Took the opportunity to un-nest the if and simplify surrounding code,
in particular the string names generation code probably needs not the
dir_key part (edit: I dropped dir_key from stringsFiles - note
stringsFiles are the same for all games - we do need a GameInfo class,
under #358).

Printing bsa errors - note I use print cause I want users to report bsas
to me (print will pop up a window - error handling must be revisited,
any way to register a handler in wx ?) - under #339. The OverflowError
was reported in the thread:
http://forums.bethsoft.com/topic/1614408-/page-3#entry25295110

Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
  File "bash\bash.pyo", line 439, in main
  File "bash\basher\__init__.pyo", line 4032, in Init
  File "bash\basher\__init__.pyo", line 4074, in InitData
  File "bash\bosh\__init__.pyo", line 2990, in refresh
  File "bash\bosh\__init__.pyo", line 2797, in _modinfos_cache_wrapper
  File "bash\bosh\__init__.pyo", line 3051, in _refreshMissingStrings
  File "bash\bosh\__init__.pyo", line 3052, in <genexpr>
  File "bash\bosh\__init__.pyo", line 3470, in isMissingStrings
  File "bash\bosh\bsa_files.pyo", line 393, in has_asset
  File "bash\bosh\bsa_files.pyo", line 402, in assets
  File "bash\bosh\bsa_files.pyo", line 447, in load_bsa_light
  File "bash\bosh\bsa_files.pyo", line 476, in _read_bsa_file
  File "bash\bosh\bsa_files.pyo", line 491, in _discard_file_records
OverflowError: Python int too large to convert to C long

I need more info on that.

Under #336 - cleaning up ModInfos.