Wip ListBox(_AComponent)/Dialog(_AComponent):
WIP:

- tooltips need more work - for:

    def OnMotion(self, event): return

see 1e2d707eab4e657c32589c33b3bcb686a438a46c

- better way of handling EVT_SIZE
"""https://stackoverflow.com/a/13486171/281545"""
import wx

class Frame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None)
        self.resized = False # the dirty flag
        self.Bind(wx.EVT_SIZE, self.OnSize)
        self.Bind(wx.EVT_IDLE, self.OnIdle)

    def OnSize(self, event):
        self.resized = True # set dirty

    def OnIdle(self, event):
        if self.resized:
            # take action if the dirty flag is set
            print "New size:", self.GetSize()
            self.resized = False # reset the flag

app = wx.PySimpleApp()
frame = Frame().Show()
app.MainLoop()

- Are those return EventResult.FINISH ##: needed? -> untested
- consider reworking the ListBox wrappers to get rid of index handling
in clients. Direct index handling is a python anti pattern
- maybe the time of the ListDataEditor has come - replace with a dict
that also takes care of the indices (OrderedDict that is) -> hmm nope
it is useful to decouple data and UI handling

Done later on this branch:

- this class should be moved to gui/
- some events need wrapping (like the mouse one) pass a wrapper of the
event with properties like is_moving etc:

- @@ -588,11 +580,8 @@ def OnMouse(self, event):
					 self.gTipText.label_text = u''
-            event.Skip()
		 else:
-            super(_TweakPatcherPanel, self).OnMouse(event)
+            super(_TweakPatcherPanel, self).OnMouse(pos, is_dragging,
+                                                    is_moving, lb_dex)

else probably not needed -> nope it is

- not sure about this either, we carried this wrapping a bit randomly,
now I centralized it again but we must see how it looks:

@@ -166,4 +166,3 @@ def tooltip(self, new_tooltip): # type: (unicode) -> None
		 else:
-            # TODO(inf) textwrap.fill(text, 50)?
-            self._native_widget.SetToolTipString(new_tooltip)
+            self._native_widget.SetToolTip(wrapped_tooltip(new_tooltip))

All in all, however, new API is a pleasure to use and get us rid of a
lot of WxUgliness:

@@ -2830,29 +2831,23 @@ def OnCheckSubItem(self,event):

-    def SelectionMenu(self,event):
+    def _selection_menu(self, lb_selection_dex):
         """Handle right click in espm list."""
-        x = event.GetX()
-        y = event.GetY()
-        selected = self.gEspmList.HitTest((x,y))
-        self.gEspmList.SetSelection(selected)
+        self.gEspmList.lb_select_index(lb_selection_dex)

Mopy/bash/gui/top_level_windows.py WIP!

Note subtle differences between WindowFrame.on_window_closing and
DialogWindow.OnCloseWindow should be unified note also _Log override

- dialogs.py :note we need to modify apply_to to accept AComponents ->
done by Inf
- balt.ask*** same goes here double (need to rewrite this API to a
class?)

Mopy/bash/basher/dialogs.py:

Note we were unbinding the ColorDialog combo two times OnOk - turns out
on_closing run first !

Traceback (most recent call last):
  File "bash\gui\events.py", line 170, in _post
    result = listener(*listener_args)
  File "bash\basher\dialogs.py", line 178, in OnOK
    self._unbind_combobox()
  File "bash\basher\dialogs.py", line 144, in _unbind_combobox
    def _unbind_combobox(self): self.comboBox.unsubscribe_handler_()
  File "bash\gui\misc_components.py", line 106, in unsubscribe_handler_
    self._on_size_changed.unsubscribe(self._set_tooltip)
  File "bash\gui\events.py", line 210, in unsubscribe
    u'Listener %s not subscribed on %r' % (listener, self))
bash.gui.events.UnknownListener: Listener <bound method ComboBox._set_tooltip of <bash.gui.misc_components.ComboBox object at 0x187C1C50>> not subscribed on EventHandler(<wx._controls.ComboBox; proxy of <Swig Object of type 'wxComboBox *' at 0x4a32c90> >, <wx._core.PyEventBinder object at 0x0439EA70>)

The UnknownListener is from future commits - it would just blow with a
ValueError. Fixed by calling on_closing from OnOk as we should. But then
turned out closing the dialog would fire OnOk handler - cause Ok button
is the default? I had to unsubscribe the OnOk.
This is another limit of the API - events that are fired internally.

Mopy/bash/basher/mod_links.py: removed the size=(400, 180) - follow up
from apply_to(..., fit=True) - was ignored

Infernio:

Move top_level_windows imports into __init__

Gives all the usual advantages of better git diffs, ability to move
internals around, etc.

Mopy/bash/gui/layouts.py:
Support components as parents in more places
Dropped unused _parent attr

Noisy comments, wrapping, renames

Note Display -> display_dialog rename

Drop a ton of external _native_widget's and added a bunch of fixups
(specifically for the patcher dialog, the colors dialog and the
Move/Copy dialog).

Drop now unused Events constants

Obsolete since we now use EventHandlers for these

Mopy/bash/basher/installer_links.py: Fix for CreateNewProject

Traceback (most recent call last):
  File "bash\balt.py", line 2477, in __Execute
    self.Execute()
  File "bash\balt.py", line 1582, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\installers_links.py", line 572, in Execute
    def Execute(self): CreateNewProject.display_dialog()
  File "bash\gui\top_level_windows.py", line 137, in display_dialog
    with cls(*args, **kwargs) as dialog:
  File "bash\basher\dialogs.py", line 352, in __init__
    super(CreateNewProject, self).__init__(parent)
  File "bash\gui\top_level_windows.py", line 123, in __init__
    style=style, **kwargs)
  File "bash\gui\top_level_windows.py", line 52, in __init__
    **kwargs)
  File "bash\gui\base_components.py", line 83, in __init__
    self._native_widget = wx_window_type(self._resolve(parent), *args,
  File "bash\gui\base_components.py", line 103, in _resolve
    obj)
RuntimeError: Failed to resolve object 'None' to wx object.

More fixups

Note the self.window TODO, that abstraction leak is really bad :/ (and
fixed later)

Move ask* parent resolution into methods:

Centralizing this will make ripping them out easier - plus some were
missed ;)
Also work on Progress parents - TODO change None default parent?

Drops a whole bunch more _native_widgets and _resolve calls

Co-authored-by: Infernio <infernio@icloud.com>