[!]Fix for str_bsas_sorted missing from bsa load order:
patcher_dialog.py  310 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 190, in PatchExecute
  File "bash\patcher\patch_files.py", line 260, in scanLoadMods
  File "bash\mod_files.py", line 184, in load_plugin
  File "bash\mod_files.py", line 240, in __load_strs
  File "bash\bosh\__init__.py", line 925, in getStringsPaths
KeyError: BSAInfo<kinggathcreations_eastempirecompany - textures.bsa>

when kinggathcreations_eastempirecompany.esp is not active - there are
some questions on the spec here. I added a couple TODOs [!] - it's
unclear if this sorting makes sense and if we can skip loading the
strings in other cases we use load_plugin. See
0a1e1f43e0e5b468b07612bf007fabf70f1176a2 and the merge in
eea41fa216459d98aa8d8b6c129cd05e1d8d8cd6.

Under #480