Fix TypeError(s) on uninstalling FOMOD assets:
Traceback (most recent call last):
  File "*****\Mopy\bash\bosh\bain.py", line 1921, in _modify_data_dir
    par = p.getParent() if (p := kwargs['progress']) else None
          ^^^^^^^^^^^^^
TypeError: Progress.getParent() missing 1 required positional argument: 'self'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "*****\Mopy\bash\balt.py", line 1572, in __Execute
    self.Execute()
  File "*****\Mopy\bash\basher\installer_links.py", line 659, in Execute
    if self._try_installer(sel_package, inst_fomod): continue
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "*****\Mopy\bash\basher\installer_links.py", line 642, in _try_installer
    link_instance.Execute()
  File "*****\Mopy\bash\balt.py", line 513, in _conversation_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "*****\Mopy\bash\balt.py", line 1940, in Execute
    return self._perform_action(progress=progress, rui_data=rin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "*****\Mopy\bash\basher\installer_links.py", line 216, in _perform_action
    self.idata.bain_wiz_install(to_install, **kwargs)
  File "*****\Mopy\bash\bosh\bain.py", line 1936, in _modify_data_dir
    self.notify_external(removed_untracked if not ex else (
  File "*****\Mopy\bash\bosh\bain.py", line 2585, in notify_external
    cls._externally_updated -= del_set
TypeError: unsupported operand type(s) for -=: 'set' and 'generator'

Thanks @sibir-ine for reporting and tracing this back to
73a69314311b61575d6240bf51a101bd6e13127d

Nit warnings:

bain: make initDefault private resulted in pruning 42 weak warnings
reading:

An instance attribute is defined outside `__init__`

This kind of warnings account for more than half the total weak warnings
emitted.