Regression in Sync Data:
Introduced in 18befdc7bad24749e6267a6a26933f7ac75a27f2:

Traceback (most recent call last):
  File "bash\balt.py", line 2361, in __Execute
    self.Execute()
  File "bash\basher\installer_links.py", line 1057, in Execute
    self._selected_info.s, len(missing), len(mismatched))
AttributeError: 'InstallerProject' object has no attribute 's'

Reported by @saebel:
http://forums.bethsoft.com/topic/1606578-wrye-bash-thread-111/page-2#entry25224674

Took the opportunity to simplify the parameters of Installer methods -
we know our name, don't we now ? Had this be done earlier this
regression would have been avoided. Under #219 for this, more to come
(install, unpackToTemp,...)  - self.archive should maybe be a Path.