Fix unpickling colors:
See
https://discord.com/channels/537706885965676554/537710082755133460/970454279347380306

Traceback (most recent call last):
  File "bash\bash.py", line 298, in main
  File "bash\bash.py", line 403, in _main
  File "bash\basher\__init__.py", line 4392, in InitImages
  File "bash\gui\base_components.py", line 115, in __setitem__
TypeError: __init__() takes from 4 to 5 positional arguments but 6 were given

Turns out those were stored as strings:

base_components.py  118 __setitem__: default.bkgd: 'WHITE' is not a Color
base_components.py  118 __setitem__: mods.text.esm: 'BLUE' is not a Color
base_components.py  118 __setitem__: default.text: 'BLACK' is not a Color
base_components.py  118 __setitem__: installers.text.complex: 'NAVY' is not a Color

Drop Colors wrapper:

I dropped Colors - just __setitem__ had some logic that was only used
twice - explicit is better than implicit dictionary example - plus we
can thus use the full dict machinery (like items).
Note that colors was used in UI update - using a dict directly should
make this faster.

Mopy/bash/basher/__init__.py: the single use where Color(*tuple) was
needed
Mopy/bash/balt.py: not sure if __future__ needed - added for typing
the now explicit colors dict
Mopy/bash/basher/settings_dialog.py: "An error occurred reading from "
was not really translatable
Mopy/bash/gui/base_components.py: note that typing should be confined to
where is needed - so the IDE should be able to tell alpha is an int.
I do find that typing everything makes the code a bit too cluttered.