Wip ModInfos.refresh - regression fixup:
Move _refresh_bash_tags above refreshLoadOrder

Are those used in mergeability checks ? -> Nope, see:

https://github.com/wrye-bash/wrye-bash/commit/cd694cd8f447ce7fe5732834d3587e5c9395c479#commitcomment-132419875

Move _recalc_dependents after refreshLoadOrder - which does that
always so this is still wip

Nit

Flip default for lo_de/activate

Fixup for "Regression" necromancy spell:

Cast by the arch-lich in 70fe06101ad20086c73dfcbdb7025ce5cb557951 -
stunned bain

Traceback (most recent call last):
  File "bash\balt.py", line 1636, in __Execute
  File "bash\basher\installer_links.py", line 681, in Execute
  File "bash\basher\installer_links.py", line 662, in _try_installer
  File "bash\balt.py", line 515, in _conversation_wrapper
  File "bash\basher\installer_links.py", line 575, in Execute
  File "bash\bosh\bain.py", line 2657, in bain_install
  File "bash\bosh\bain.py", line 2625, in _installer_install
  File "bash\bosh\bain.py", line 1275, in install
  File "bash\bosh\bain.py", line 1568, in _install
  File "bash\bosh\bain.py", line 1325, in _fs_install
  File "bash\bosh\__init__.py", line 3649, in new_info
  File "bash\bosh\__init__.py", line 1740, in new_info
  File "bash\bosh\__init__.py", line 1610, in new_info
  File "bash\bolt.py", line 1095, in join
  File "bash\bolt.py", line 1095, in <listcomp>
  File "bash\bolt.py", line 872, in getNorm
  File "<frozen ntpath>", line 540, in normpath
TypeError: expected str, bytes or os.PathLike object, not BSAInfo

I admire you, lord of ghosts.