Regression - applying tweaks could raise RuntimeError:
https://bethesda.net/community/post/351802:

Traceback (most recent call last):
  File "bash\balt.py", line 2485, in __Execute
    self.Execute()
  File "bash\basher\ini_links.py", line 143, in Execute
    if self.window.apply_tweaks(self.iselected_infos()):
  File "bash\basher\__init__.py", line 638, in apply_tweaks
    ini_info.read_ini_lines())
  File "bash\bosh\ini_files.py", line 327, in applyTweakFile
    self.saveSettings(ini_settings,deleted_settings)
  File "bash\bosh\ini_files.py", line 290, in saveSettings
    for section in ini_settings:
RuntimeError: dictionary changed size during iteration

Introduced in 2a49a6f778a61b21eb619c94f9deb431b7c66b39