Fixup for boot errors on missing ini directories:
A funny one here - note the last exception:

Traceback (most recent call last):
  File "C:\...\Mopy\bash\initialization.py", line 275, in init_dirs
    shellMakeDirs([wanted_dir])
  File "C:\...\Mopy\bash\env\__init__.py", line 109, in shellMakeDirs
    raise NotADirectoryError(errorPaths)
NotADirectoryError: [paths.Path('D:\\Dropbox (Personal)\\OBLIVION\\!\\TESIV2\\Bash Mod Data')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\Mopy\bash\bash.py", line 530, in main
    _main(opts, wx_locale, wxver)
  File "C:\...\Mopy\bash\bash.py", line 605, in _main
    bush_game, game_ini_path = _detect_game(opts, bash_ini_path)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Mopy\bash\bash.py", line 720, in _detect_game
    bush_game = _import_bush_and_set_game(opts)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Mopy\bash\bash.py", line 751, in _import_bush_and_set_game
    bush.detect_and_set_game(opts, init_warnings, gname, gm_path)
  File "C:\...\Mopy\bash\bush.py", line 292, in detect_and_set_game
    __setGame(gname, gm_path, 'Using %(gamename)s game:', opts,
  File "C:\...\Mopy\bash\bush.py", line 279, in __setGame
    game = _allGames[gamename](gamePath, opts, init_warnings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Mopy\bash\game\__init__.py", line 452, in __init__
    self.game_ini_path = initialization.init_dirs(self, *args)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Mopy\bash\initialization.py", line 281, in init_dirs
    msg = _dirs_err_msg(e, dir_keys, bainDataSrc, modsBashSrc,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Mopy\bash\initialization.py", line 305, in _dirs_err_msg
    if dirs[dir_key] in e.failed_paths:
                        ^^^^^^^^^^^^^^
AttributeError: 'NotADirectoryError' object has no attribute 'failed_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\Mopy\Wrye Bash Launcher.pyw", line 30, in <module>
    bash.main(opts)
  File "C:\...\Mopy\bash\bash.py", line 561, in main
    _show_boot_popup(err_msg % {
                     ^^^^^^^^^^^
KeyError: 'gamename'

So the AttributeError is from b5bb441163e51a3a6a5f032c6e3278f917aed105
but then when it tried to print the exception the line

    __setGame(gname, gm_path, 'Using %(gamename)s game:', opts,

would be parsed as a string formatting element - boom. Whoa - maybe
there is a way to prevent these (note it happened on the very final
except block, we don't want this) but this quick fix will do - now
prints something helpful:

Please ensure Wrye Bash is correctly installed.

...

  File "C:\...\Mopy\bash\game\__init__.py", line 451, in __init__
    self.game_ini_path = initialization.init_dirs(self, *args)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Mopy\bash\initialization.py", line 282, in init_dirs
    raise BoltError(msg)
bash.exception.BoltError: Error creating required Wrye Bash directories.  Please check the settings for the following paths in your bash.ini, the drive does not exist:

[General] sBashModData
    D:\Dropbox (Personal)\OBLIVION\!\TESIV2\Bash Mod Data

which is True

Mopy/bash/initialization.py: this is no longer True since at least
f339757f8d0d1118cd2878f53b7ac8d9a9e4b610 - initialization.py is very
important to stay bash-imports free as we need to house init stages
enum in there - under #600