Move reference_types to CELL:
This is record type information not game one (this should be mostly
patcher config). Should be pure refactoring apart TODO's to be
addressed - don't mind those btw I will remove them in the final merge
(not a good idea adding TODOs on dev nor indeed in intermediate commits
but most of those will disappear in next one - led to some interesting
feedback). In all we must review reference types are correct for all
games - especially FO3 and FO4.

Record validation for skyrim still breaks with:

mod_links.py  115 Execute: Exception loading Skyrim.esm:
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 105, in Execute
    self._load_mod(dbg_inf, keepAll=False,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 87, in _load_mod
    modFile.load(True, **kwargs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 223, in load
    new_top.load_rec_group(ins, load_fully)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 72, in load_rec_group
    self._load_rec_group(ins, ins.tell() + self.header.blob_size())
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1265, in _load_rec_group
    build_cell_block(unpack_block=unpackCellBlocks,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1233, in build_cell_block
    cellBlock = MobCell(header, selfLoadFactory, cell, ins, True)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 765, in __init__
    super(MobCell, self).__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 63, in __init__
    if ins: self.load_rec_group(ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 72, in load_rec_group
    self._load_rec_group(ins, ins.tell() + self.header.blob_size())
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 793, in _load_rec_group
    raise ModError(self.inName,
bash.exception.ModError: Skyrim.esm: Unexpected NAVM record in cell children group.

But this needs #647 to be fixed (as the Oblivion ref types are hardcoded
in both LoadFactory and Mob* classes).

Mopy/bash/parsers.py: flip keepAll to False - the usual value. Note one
of the Trues was overridden - in all do we need the remaining 2?