Fix several minor regression and nits
Mopy/bash/game/oblivion/records.py:
Regression fix for regression fix

Broke in c966a4830270aef5280bf5f71613bfa992579f23.
This would cause errors if we dumped a new SNDX subrecord.

Mopy/bash/basher/gui_patchers.py:
Mopy/bash/game/fallout3/__init__.py:
Mopy/bash/game/oblivion/__init__.py:
Mopy/bash/game/skyrim/__init__.py:
Fix name of ImportFactions

Forgot to change this one to match its end-user-visible name.

Mopy/bash/brec/advanced_elements.py:
_MelDistributor._load_state to list

No idea why I made this a tuple, completely wrong data structure.

Mopy/bash/basher/__init__.py:
Followup for old compat removal

bash_version variable is unused now.

Mopy/bash/bosh/__init__.py:
Fix regression on unghost

Broke in 6cee9084fe1f4b4aeadd599294ea9f447f764ba1:

Traceback (most recent call last):
  File "bash\bosh\__init__.py", line 506, in setGhost
    self.__mark_unchanged()
AttributeError: 'ModInfo' object has no attribute '_ModInfo__mark_unchanged'

Mopy/bash/patcher/patchers/multitweak_assorted.py:
Noop for correctness

This way the correct functioning of these tweaks no longer depends on
tweak name. Right now they sort correctly because of their tweak names
(e.g. All Armor Playable < Armor Shows Amulets), but this would break if
they're ever changed - or translated into a language where this is no
longer the case!

Mopy/Docs/Wrye Bash Advanced Readme.html:
Mopy/Docs/Wrye Bash General Readme.html:
Mopy/Docs/Wrye Bash Technical Readme.html:
Mopy/Docs/Wrye Bash Version History.html:
Bump docs versions

Forgot to bump those after the 307 release.