Decouple GUI and data model patcher classes:
I spent a lot of time thinking of a common base class for GUI and
business logic patchers till it dawned me: there should be no common
base class. This commit decouples the config phase from the business
logic. GUI is responsible for collecting the patches config and
instantiating the patchers. 'name', 'text' and 'tip' are moved to gui,
where they belong and are renamed to unique per hierarchy identifiers,
at long last. We still have ~400 'name' in core Bash - 'text' is now
down at ~120.

Since now the patchers need not be instantiated once per run we can
finally instantiate the data model patchers as needed - so I replaced
initPatchFile with `__ini__` and I instantiate patchers per patch.

Other pros:

- more straightforward - new patch new patchers
- all config phase in now in a central place where we can further
edit it.
- squash unresolved attributes warnings
- squash attribute defined outside of init warnings
- no MI - not a problem per se but not suitable here, actually the root
of the issue

Cons:

- '__init__' is less searchable than initPatchFile, but modern IDEs
should be (modulo bugs) able to list implementation
(Navigate > Implementation(s))
- Different init signatures in Abstract_Patcher and AListPatcher

TODOs:

- enforce API: calling a "not isActive" patcher could raise an error
(note the doc "All functions are called after this")
- what happens if all enabled patchers are not active - we should return
- UpdateReferences._record_types -> we have to use getReadWriteClasses:
MreRecord.listTypes is not yet set when we import oblivion/patchers
TODO: move to another file that is not imported in game/*/patcher
- allowUnloaded and srcs attributes is a mess:

  - changed allowUnloaded to False in CBash_AliasesPatcher,
  CBash_AlchemicalCatalogs, CBash_ContentsChecker
  - CBash_SEWorldEnforcer: We need to have a srcs attribute as we have
  scanRequiresChecked=True (messy)

  new issue since then (# 495) <-- RRR. We should add sources as a method
  mixin differentiating mod and csv sources there.
- allowUnloaded can't be moved to getAutoItems - allSet is populated in
PatcherMerge init (duh)
- btw note common code in:
Mopy/bash/basher/patcher_dialog.py
Mopy/bash/basher/mod_links.py

I dropped a lot of `if not self.isActive: return`. The processing
is minimal (creating couple empty dicts) and since the patcher init is
only called on enabled patchers chances are they are active too.
Naming: separate names for separate class hierarchies - why can be seen
in this commit. I chose explicitly rough ones for the init hierarchy
as they (wrap better and oh) need to be easily excluded - params in
methods hierarchies are just noise, the attributes are of interest. For
those I have chosen to differentiate between class hierarchies - the
private _patcher_name is inherited from the GUI to be used in logs -
and signals a weak coupling that remains from MI.

SpecialPatcher erosion

Race patcher has its own issue by now (# 494) <-- RRR. Here I unmade it from a
SpecialPatcher subclass as only CBash patchers use scan_more -
RacePatcher just used group/editOrder/scanOrder overrides
- CBash_RacePatcher: revisit allowUnloaded - False?
- isActive for this patcher is set to True - unfortunately we can't just
use AMultiTweaker/AListPatcher inits. Of course if the patcher is not
enabled it shouldn't run.

- SpecialPatcher(CBash_Patcher): yep, this permitted a common base
class for _CBashOnlyRacePatchers. However it also hid some unused
variable warnings. This is CBash patchers API however that does need
work - for one the hasattr calls in CBash_PatchFile.buildPatch

Bye autoRe

The names patcher override was gone since
d9b0c3e446c325337715eb8d809aee7aa4015de5
This whole machinery turns out to be used in one place - I moved it there

Mopy/bash/patcher/base.py: srcs are always present:

     def _srcMods(self,log):
-        """Logs the Source mods for this patcher - patcher must have `srcs`
-        attribute otherwise an AttributeError will be raised."""
+        """Logs the Source mods for this patcher."""

More SpecialPatcher erosion - move more config to gui from special

Mopy/bash/game/oblivion/patcher/special.py:
Special was one of the things that stopped me from common ABC between
GUI and data model - for a good reason, now at least the complexity
is explicit (see get_cls_vars)

Reworked tweaks

- Names - what's the deal with bodyTags - they must be moved to game/
anyway - CBash_NamesTweaker and bodyTags -> done later on this branch
by Infernio

patches_set:

Mopy/bash/patcher/__init__.py: moved patches set here - we need an API
for patchers that have text file sources
Mopy/bash/game/oblivion/patcher/special.py:
- common read from text - note I dropped some GPath calls
- works correctly? Especially: SEFF = MGEFCode('SEFF') - any reason
it should not be in class scope?
- we need a common initData

+                    id_exhaustion[longid] = int(time) may raise VE
+                except (IndexError, ValueError):
+                    pass # too few items, we couldn't unpack or int() failed
+

- belongs to gui (should filter the sources) but oblivion/special are in
the way

On a second thought as patches_set is populated in the GUI
the self.srcs are always in the set if they don't exist
anymore (see Mopy/bash/game/oblivion/patcher/special.py)
in Mopy/bash/patcher/patchers/base.py there were if file checks but
here is a classic application of EAFP:

fields=[1,2,3]
mod,objectIndex,eid,time = fields[:4]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: need more than 3 values to unpack
int('abc')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'abc'

Moved _read_write_records to _Abstract_Patcher - better names needed

Mopy/bash/patcher/patchers/multitweak_names.py
Mopy/bash/patcher/patchers/multitweak_assorted.py:
Some getTypes pruning in tweaks

self.activeTypes is only read so I replaced it with tweak_read_classes

CBash race getTypes - remove class variable races_data

Mopy/bash/patcher/patchers/importers.py: moved tag_attrs out of init,
they are static

SpecialPatcher(CBash_Patcher):

scan_more is only used in CBash and then not in all the previous
subclasses of SpecialPatcher

Threw some prefixing in - Mopy/bash/game/oblivion/patcher/__init__.py:
note type names must be string, check in py3

Infernio:

Refactoring _AListsMerger a bit

Properly passes a defaultdict version of configChoices in instead of
hackily assigning it later and unifies the deflstMasters/delevMasters
variables as de_masters, eliminating some duplicate code.

Note this diff:
-        self.srcMods = set(self.srcs) & p_file.loadSet
+        self.srcs = set(self.srcs) & p_file.loadSet

That's almost certainly what was intended (it mirrors ListsMerger
perfectly), but the srcMods/srcs difference seems to have been missed
during the FO3/FNV merge.

Also dropped some commented out lines from the ListsMerger that were
still in the FidListsMerger and marked mastersScanned with a FIXME -
that was probably intended to avoid duplicate work for the de_masters
calculation, have to check if using it is feasible.

_AListsMerger couple docstring + fixup

Note that I dropped the itemgetter import, found that usage horribly
confusing, IMO the list comprehension is much clearer. Might be slower,
feel free to benchmark

Co-authored-by: Infernio <infernio@icloud.com>