Drop do_unpack/setChanged from Mob*:
Turns out it was always True apart from MobBase of course - see
ee6143128e68c6a57ce25904c319f6a9e810c0a5. Cleaning up this setChanged
logic was one of my goals here - check!

EDIT: below notes are invalid - this will be actually reverted - see
"Drop data from _HeadedGrup" commit - much more refactoring is needed
to be able to lazy load.
- what we really cared about is if we had read in the Mob as a blob -
very wip but attempts to actually be able to do this in more fine
grained level (part of the older code would try do that - see
getUnpackCellBlocks)
- the idea was to unpack the cell references/LAND/ROAD etc only in
keepAll or if they were explicitly specified - now we want to be able
to load the groups as `data` if keepAll is specified but not the CELL
children requested

-----
Note repr is broken - fixed on next commits that assign an
id_records to all MobObjects

@@ -1096,3 +1096,6 @@ class _ExteriorCells(MobCells):
     def __init__(self, grup_header, load_f, *args, **kwargs):
-        kwargs.pop('do_unpack') # yuck - wip
+        if 'do_unpack' in kwargs:
+            kwargs.pop('do_unpack', None) # yuck - wip
+        else:
+            deprint(f'{self!r}')
         self.id_records = {}

mod_files.py  217 load: Error in DLCOrrery.esp
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 191, in load
    new_top = topClass(g_head, self.loadFactory, ins,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1258, in __init__
    super().__init__(grup_header, load_f, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 660, in __init__
    super().__init__(grup_header, load_f, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 202, in __init__
    super().__init__(grup_header, load_f, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 147, in __init__
    super().__init__(load_f, ins, self._end_pos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 48, in __init__
    self._load_rec_group(ins, endPos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 213, in _load_rec_group
    grel = self._group_element(header, ins)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 677, in _group_element
    return self._top_rec_class(self._load_f, ins, **kwargs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 387, in __init__
    super().__init__(load_f, ins, self._end_pos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 48, in __init__
    self._load_rec_group(ins, endPos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 578, in _load_rec_group
    super()._load_rec_group(ins, end_pos, self.master_record)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 481, in _load_rec_group
    self._load_mobs(gt, header, ins, master_rec)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1222, in _load_mobs
    super()._load_mobs(gt, header, ins, master_rec)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 490, in _load_mobs
    self._mob_objects[gt] = self._mob_objects_type[gt](header,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 896, in __init__
    self._set_mob_objects(grup_head.label)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 397, in _set_mob_objects
    self._mob_objects[gt] = mob_type.empty_mob(*args)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 258, in empty_mob
    mob = cls(head, load_f)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1100, in __init__
    deprint(f'{self!r}')
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 348, in __repr__
    return f'<{self}: {len(self.id_records)} {self._accepted_sigs} ' \
AttributeError: '_ExteriorCells' object has no attribute 'id_records'