Fix Import Face in saves
Broke in 1bfea44, fixing revealed another bug from 77ef1bf (or maybe
4964710a8ee797d77805ce5b58916d657fb3eb43).

Traceback (most recent call last):
  File "bash\gui\events.py", line 181, in _post
  File "bash\basher\dialogs.py", line 136, in DoImport
  File "bash\bosh\faces.py", line 205, in save_setFace
  File "bash\bosh\faces.py", line 269, in save_setPlayerFace
TypeError: unsupported operand type(s) for >>: 'FormId' and 'int'

For the actual player reference (00000007), fid appears to always be an
int. However, for the dynamic(?) player references (FFxxxxxx), fid
appears to always be a FormId.

Utumno:

Nit in faces:

I split the slots to ones that are set from the NPC record and ones that
are set manually - inlined one use _save_getCreatedFaces - the whole
thing needs a rewrite. It's ImportFaceDialog that passes the faces in,
start from there.

More EAFP in MasterMap

Mopy/bash/basher/installer_links.py: make "To" translatable

Co-authored-by: MrD <the.ubik@gmail.com>