_initData(), _enable() introduced - InstallerLink(Link->_Link) part I:
_enable(): later moved to a _Link subclass (EnabledLink)
_initData(): it's a hack cause I sometimes need to
customize the Installers (only ?) links text and help based on selected,
data etc attributes. Consider this an implementation detail, ugly at that:

Traceback (most recent call last):
  File "bash\balt.py", line 2030, in DoItemMenu
    self.itemMenu.PopupMenu(self,Link.Frame,selected)
  File "bash\balt.py", line 2085, in PopupMenu
    link.AppendToMenu(menu,parent,*args)
  File "bash\basher.py", line 9170, in AppendToMenu
    self.help = _(u"Duplicate selected %(installername)s.") % ({'installername':self.selected[0]})
AttributeError: Installer_Duplicate instance has no attribute 'selected'