generic_av_effects and co to records:
Four (4) super hacky game attributes dropped:

- bush imports deep inside records code gone - yey!
- int_unpacker(x)[0], part is probably never used (were we ever querying
by int?)
- the eid caching seems a py2 relic too, probably due to ascii bytes
comparing with strings fine - not clear yet how we should patch this.
Other than that this clearly belongs to records - see comments in
6a4b94a6bb4db1559f07f939cb6c3e936dc241cc

Fun fact:

class A:
    x = str
    a = {y: x(y) for y in [1]}

Traceback (most recent call last):
  File "C:\_\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<input>", line 3, in A
  File "<input>", line 3, in <dictcomp>
NameError: name 'x' is not defined

I also get a re-declared without usage warning for a in:

    mgef_name = dict(chain.from_iterable(
        ((int_unpacker(x)[0], z), (x, z)) for x, [y, z, a] in
        _magic_effects.items()))

Anyway I think this patch is safe - tricky part is removing/patching the
mgef_* caches.