Yet another type error in the patcher:
See
https://discord.com/channels/537706885965676554/537710082755133460/962733268820697098

patcher_dialog.py  265 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 170, in PatchExecute
  File "bash\patcher\patch_files.py", line 312, in buildPatch
  File "bash\patcher\patchers\checkers.py", line 306, in buildPatch
TypeError: '<' not supported between instances of 'NoneType' and 'str'

[k for k,v in hairNames.items() if v is None]

[
(bolt.Path('CyrodiilUpgradeResourcePack.esm'), 7075),
(bolt.Path('CyrodiilUpgradeResourcePack.esm'), 7076),
(bolt.Path('CyrodiilUpgradeResourcePack.esm'), 7081)
]

So full is None for those - turned this to a '' but is full optional
(None is the default for MelString so no full was loaded)?

Made the same for eyes proactively.

Infernio:
requirements.txt:
Bump pytest and pygit

Bug fixes and some removals of deprecated stuff in pytest. Nothing that
affects us.