Notify BAIN when ghosting or renaming plugins
To reproduce:
 1. Make sure Auto-Ghosting is on
 2. File.. > New Mod
 3. Switch to Installers tab

You should get something like this:

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 3614, in OnShowPage
    refresh_target=load_order.using_ini_file())
  File "bash\balt.py", line 911, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\__init__.py", line 2962, in ShowPanel
    scan_data_dir)
  File "bash\balt.py", line 911, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\bosh\bain.py", line 1521, in _projects_walk_cache_wrapper
    return func(self, *args, **kwargs)
  File "bash\basher\__init__.py", line 3007, in _refresh_installers_if_needed
    do_refresh = self.listData.refreshTracked()
  File "bash\bosh\bain.py", line 2134, in refreshTracked
    self.data_sizeCrcDate[key] = (apath.size,apath.crc,apath.mtime)
  File "bash\bolt.py", line 629, in size
    return os.path.getsize(self._s)
  File "C:\Python27-32\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
WindowsError: [Error 2] The system cannot find the file specified: u'G:\\steam\\steamapps\\common\\Enderal\\Data\\New Mod.esp'

This fixes it by enhancing our notify_external API to allow us to tell
BAIN about renames. Of course, this isn't really the best place for it -
once again comes down to copyTo/moveTo APIs. Ref #336.

Mopy/bash/basher/__init__.py:
Threw in a fixup for a random crash I got but couldn't reproduce.
Probably wx quirks.

Mopy/bash/bosh/__init__.py:
Some 'renames' renames :P