Fixup for _enable returning None in Oblivion.esm menu:
Traceback (most recent call last):
  File "bash\bash.py", line 471, in main
  File "bash\bash.py", line 653, in _main
  File "bash\bash.py", line 647, in _main
  File "bash\basher\__init__.py", line 3777, in Init
  File "bash\balt.py", line 422, in _conversation_wrapper
  File "bash\basher\__init__.py", line 3582, in RefreshData
  File "bash\basher\__init__.py", line 189, in ShowPanel
  File "bash\basher\__init__.py", line 257, in ShowPanel
  File "bash\balt.py", line 1294, in setup_global_menu
  File "bash\gui\misc_components.py", line 489, in populate_immediately
  File "bash\gui\misc_components.py", line 518, in _populate_menu
  File "bash\balt.py", line 1269, in _populate_category
  File "bash\balt.py", line 1635, in AppendToMenu
  File "bash\balt.py", line 1646, in AppendToMenu
  File "bash\balt.py", line 1527, in AppendToMenu
  File "bash\balt.py", line 1687, in AppendToMenu
  File "bash\balt.py", line 1666, in AppendToMenu
TypeError: MenuItem.Enable(): argument 1 has unexpected type 'NoneType'

It happened for unknown Oblivion.esm size (...)

And some comments for #690

Mopy/bash/games_lo.py: regression fixup (the fix_lo case broke in
a81fe6be06e42b47573b3704693e2fe8e19e4003)