Regression in _CheckList_SelectAll - renaming 'text':
Mopy/bash/balt.py:
Traceback (most recent call last):
  File "bash\balt.py", line 2854, in OnContext
    event.GetEventObject().GetSelections())
  File "bash\balt.py", line 2326, in PopupMenu
    link.AppendToMenu(menu,parent,*args)
  File "bash\balt.py", line 2481, in AppendToMenu
    self.__class__.kind)
  File "C:\_\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 11490, in __init__
    _core_.MenuItem_swiginit(self,_core_.new_MenuItem(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at ..\..\src\common\stockitem.cpp(166) in wxGetStockLabel(): invalid stock item ID
self.text should be self._text - introduced in
a2184a886808b41917d9eb6419dda793e5d1549b, another IDE miss
Took the opportunity to rename more text local variables - see #312

Signed-off-by: MrD <the.ubik@gmail.com>