Fixups and random warnings pruning:
bolt: actually the warning was right

raise UnicodeDecodeError(u'Text could not be decoded using any method')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: function takes exactly 5 arguments (1 given)

raise UnicodeDecodeError
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: function takes exactly 5 arguments (0 given)

Mopy/bash/ini_files.py: note that the UnicodeDecodeError was never
actually raised from read_ini_content - I moved the (hacky) isCorrupted
handling in the latter.

update_wb_status.py: fixup from f993b34a34b494f535f6a04394051e3214f99678

Mopy/bash/brec/basic_elements.py: fix regression from _post_master_sigs
removal.

1c26edae9fa0750b22c8c136da382c8c7e51f766 removed has_overlay_plugins -
1a7ef46349094d3c5b28eefd4c2242dc70edaed3 author date is actually much
older - the duplicated logic hid a bug after all. This triggered a small
refactoring of form ids context managers. Also turns out we can't use
MelObject loading mels here:

bash.exception.ModError: kgcdoom.esm: AttributeError(\
"'MelObject' object has no attribute 'set_form_id_type'")

I created _MelPostMastG override of MelPostMaster to handle this.

Warnings:

Mopy/bash/bosh/faces.py: ~45 unresolved attribute warnings

bass: None costed 96 bogus warnings (out of a total 425 remaining)
reading:

Type alias is not generic or already specialized

Mopy/bash/basher/ini_links.py: drop bass import