Fix GOG, etc. versions causing errors in settings
Reported on AFKMods:

Traceback (most recent call last):
  File "bash\gui\events.py", line 178, in _post
  File "bash\basher\settings_dialog.py", line 118, in _send_apply
  File "bash\basher\settings_dialog.py", line 1226, in on_apply
  File "bash\basher\settings_dialog.py", line 1226, in <dictcomp>
KeyError: '[Mods] Renaming a plugin to something that Skyrim Special Edition'

The issue is we strip off '(' and everything that comes after it, but
these games have a '(GOG)' suffix. They shouldn't (game refactoring),
but they do for now, so just strip it off for the settings dialog
(purely aesthetic anyways).

Also added verification to make sure this doesn't happen again in the
future by raising a SyntaxError when we find such parentheses. Finally,
some minor translatable editing work under #55 is included since I was
in the vicinity anyways.