Fixup for ceding ownership to a newer version of a mod:
See https://discord.com/channels/537706885965676554/537710082755133460/1415990265071669289

Traceback (most recent call last):
  File "bash\balt.py", line 1718, in __Execute
  File "bash\balt.py", line 515, in _conversation_wrapper
  File "bash\balt.py", line 2081, in Execute
  File "bash\basher\installer_links.py", line 864, in _perform_action
  File "bash\bosh\bain.py", line 1883, in _modify_data_dir
AttributeError: 'RefrIn' object has no attribute 'redraw'

> this happened when I had two versions of the mod, one loading later
> than another. I installed an earlier version higher, then uninstalled
> the later version and got that error
Well, rui_data is a defaultdict(RefrIn) and we cannot reassign it (it's
an output param). Introduced in 73a69314311b61575d6240bf51a101bd6e13127d

bain: simplify moveArchives - note that if newPos >= len(self) then
old_ordered[:newPos] == old_ordered[:len(old_ordered)] and
old_ordered[newPos:] must be empty.

Mopy/bash/balt.py: I was doing a DIONSC refresh here - not needed really

Some more nit radiation from next merge