[336]Regression in mark_unchanged and API notes:
Devilish:

__init__.py  666 setGhost: Failed to ghost file C:\Dropbox\eclipse_workspaces\python\wrye-bash\Data\NPC Overhaul.esp
Traceback (most recent call last):
  File "bash\bosh\__init__.py", line 663, in setGhost
    self.mark_unchanged()
  File "bash\bosh\__init__.py", line 305, in mark_unchanged
    AFile._reset_cache(self, self._stat_tuple, load_cache=False)
  File "bash\bosh\__init__.py", line 329, in _reset_cache
    self._file_size, self._file_mod_time = stat_tuple
ValueError: too many values to unpack

Introduced in cc6af2f79dc59901551c767bcc0481650470b882

API is beta - for instance load_cache logic is difficult to follow as
it works sometimes as clear_cache - in particular it's difficult to
follow the IniFile usage (needs_update may need be moved in IniInfo)
and BSAs.
For now I moved mark_unchanged to the FileInfo class as it's there
where file operations may need mark stuff as unchanged - anyway as
noted in commit above mark_unchanged itself needs lots of work (starting
from file operations APIs all around). To make sure I anyway update the
cache even if status/assets is not None/empty I changed _null_stat to
impossible values, so next call to needs_update on _OSError'd_ files
will trigger a _reset_cache with value True. OSError is the only case
where we call _reset_cache with load_cache=False - apart from `__init__`
calls, which need more thought - see above.

Under #336.