Fixup for backup failing to backup dirs:
Probably broke in d12c9ede2125986481de6ed387a3fcd86d82d3c4 - reverted.
Incidentally we get a PermissionError - should be an IsADirectoryError.

Traceback (most recent call last):
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bash.py", line 524, in main
    _main(opts, wx_locale, wxver)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bash.py", line 681, in _main
    bkp_setts.backup_settings(balt)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\barb.py", line 155, in backup_settings
    self._backup_settings(GPath_no_norm(temp_settings_backup_dir))
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\barb.py", line 162, in _backup_settings
    fpath.copyTo(temp_dir.join(tpath))
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bolt.py", line 1244, in copyTo
    copy_or_reflink(self._s, dest_path._s)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bolt.py", line 2752, in copy_or_reflink
    shutil.copyfile(a, b)
  File "C:\Users\MrD\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\Dropbox (Personal)\\GAMES\\TESIV\\Oblivion\\Data\\Bash Patches\\ConjurationTomeOOO-OBSE.esp Exported Scripts'

Nit around Installer __init__:

Keyword arguments are absorbed in Installer.__init__ - I am after
instantiating ListInfos directly - should not happen (use factory/
new_info, go through the store) but it's difficult to track. In
particular that's why I want to get rid of the bosh.Installer***
classes - here I make _inst_types use once - I followed instantiations
manually and I believe InstallerPackage params are always passed as
kwargs.