Removed compatibility for PickleDict using bosh.Paths:
Takes an import wx along - from ___bosh___. Under #190, basically this
whole merge was triggered by this frigging import.

TODO: better error handling - this be better called on boot
We have to add `self.vdata['boltPaths'] = True` by hand cause otherwise
settings created by 307 will blow on 306 - cause it won't find boltPaths
attribute and run the updatePaths() which will blow:

Wrye Bash starting
Using Wrye Bash Version 307
Python version: 2.7.10
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: cp437; output encoding: None; locale: ('en_US', 'cp1252')
filesystem encoding: mbcs
Searching for game to manage:
bush.py   87 _supportedGames: Detected the following supported games via Windows Registry:
bush.py  147 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  153 _detectGames: Set game mode to oblivion specified via -o argument:  \mnt\win\GAMES\TESIV\Oblivion
bush.py  187 setGame: No preferred game specified.
bush.py  168 __setGame:  Using oblivion game: \mnt\win\GAMES\TESIV\Oblivion
testing UAC
bosh.py 5224 __init__: Using libbsa API version: 2.0.0
bosh.py 5230 __init__: Using LOOT API version: 0.6.0
load_order.py  321 <module>: Using libloadorder API version: 7.6.0
# Generating comtypes.gen.SHDocVw
Traceback (most recent call last):
  File "/mnt/win/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 88, in <module>
	bash.main()
  File "Z:\mnt\win\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\bash.py", line 466, in main
	frame = app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4347, in Init
	self.InitData(progress)
  File "bash\basher\__init__.py", line 4379, in InitData
	bosh.modInfos = bosh.ModInfos()
  File "bash\bosh.py", line 4038, in __init__
	FileInfos.__init__(self,dirs['mods'],ModInfo)
  File "bash\bosh.py", line 3818, in __init__
	self._initDB(dir_)
  File "bash\bosh.py", line 3807, in _initDB
	self.bashDir.join(u'Table.pkl')))
  File "Z:\mnt\win\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\bolt.py", line 1748, in __init__
	dictFile.load()
  File "bash\bosh.py", line 200, in load
	self.updatePaths()
  File "bash\bosh.py", line 251, in updatePaths
	update(self.data)
  File "bash\bosh.py", line 232, in update
	xnew = dict((update(key),update(value)) for key,value in x.iteritems())
  File "bash\bosh.py", line 232, in <genexpr>
	xnew = dict((update(key),update(value)) for key,value in x.iteritems())
  File "bash\bosh.py", line 245, in update
	changed.add(x._path)
AttributeError: 'Path' object has no attribute '_path'

So:

@@ -1507,2 +1507,3 @@ def save(self):
         #--Pickle it
+        self.vdata['boltPaths'] = True
         with self.path.temp.open('wb') as out: