Fix backwards compat in NamesTweak_spells
This was causing a traceback when you kept an old setting around (e.g.
%s%d) because the method was incorrectly cleaning up the previous value:

Traceback (most recent call last):
  File "bash\gui\events.py", line 178, in _post
  File "bash\balt.py", line 803, in _conversation_wrapper
  File "bash\basher\patcher_dialog.py", line 169, in PatchExecute
  File "bash\patcher\patch_files.py", line 312, in buildPatch
  File "bash\patcher\patchers\base.py", line 177, in buildPatch
  File "bash\patcher\patchers\multitweak_names.py", line 640, in wants_record
  File "bash\patcher\patchers\multitweak_names.py", line 175, in wants_record
  File "bash\patcher\patchers\multitweak_names.py", line 652, in _exec_rename
TypeError: not enough arguments for format string