Drop eval in Trusted Binaries import
Notably makes it work on py3 as well, since:

    [infernio@inf-desktop ~]$ python3
    Python 3.8.6 (default, Sep 30 2020, 04:00:38)
    [GCC 10.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> eval("[u'foo', 42, 42L]")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "<string>", line 1
        [u'foo', 42, 42L]
                       ^
    SyntaxError: invalid syntax

That's on top of eval being evil and all that.

Also added a full specification for the Trusted Binaries export/import
text format. Need to get around to writing one for the Colors
export/import text format too.

Convert technical readme tabs -> spaces

No idea why PyCharm insists on making these tabs...
Kept separate since it's just noise.

Under #460