Fixes for trying to join Paths as stings and Linux paths:
Mopy/bash/bosh.py:

testing UAC
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
  File "bash\bash.pyo", line 364, in main
  File "bash\bosh.pyo", line 10435, in initBosh
  File "bash\bosh.pyo", line 10227, in initDirs
TypeError: sequence item 0: expected string or Unicode, Path found

Note the nifty `Path.__unicode__()` in action

Mopy/bash/balt.py:

errorPaths was expecting windows absolute paths (starting with drive
name) and would fail on wine displaying a misleading error - just
bash was not prepared to handle linux paths:

testing UAC
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
  File "bash\bash.pyo", line 382, in main
  File "bash\bash.pyo", line 364, in main
  File "bash\bosh.pyo", line 10435, in initBosh
  File "bash\bosh.pyo", line 10228, in initDirs
bash.bolt.BoltError: Error creating required Wrye Bash \
directories.  Please check the settings for the following \
paths in your bash.ini, the drive does not exist:

##: note there are no paths in the ini

A path error was the result of relative paths.  The following paths \
are causing the errors, however usually a relative path should be fine.  \
Check your setup to see if you are using symbolic links or NTFS Junctions:

\mnt\win\GAMES\TESIV\Oblivion Mods\Bash Mod Data
\mnt\win\GAMES\TESIV\Oblivion Mods

Workaround: add to the bash.ini absolute paths to the "C:\" drive
where to create the required Bash dirs:

sOblivionMods=C:\Oblivion Mods
sBashModData=C:\Oblivion Mods\Bash Mod Data

Wine would do the right thing.

Fixed in this commit while still catching non existent drives. Bash
creates needed directories like \mnt\win\GAMES\TESIV\Oblivion Mods
alright - but this is a hack (startswith...) - the whole Path handling
needs revisiting in light of WINE - under #241.

Under #240.