Rework FormIDs handling
FormIDs stand in the way of much of #480, #312 and #525, so it's time to
tackle them. This commit (actually a squashed version of an entire
branch that would have otherwise broken dev) introduces a new system for
handling FormIDs that stores them using a class (brec.FormId) instead of
a tuple. Instances of this class are created by using a FormID context
wrapping a ModReader that injects the master table to let FormIDs
resolve properly JIT.

Advantages:
 - From a design standpoint, this is a lot more elegant.
   - Resulting code is much more readable too.
 - Unblocks removing the setDefault API, which will let us gain some
   performance and fix longstanding bugs.
 - Gives us some nice convenience features for free:
   - FormIDs will always display using hex notation in debug logs.
   - We can create different classmethods to handle different
     construction patterns using nicer APIs.
   - etc.

Disadvantages:
 - We lose some performance. We'll definitely gain that back in the
   course of #480 and #312 though.

Squashed, lightly edited notes follow:

Use DummyFid for defaults and grup parents:

IIUC seems if we try to dump any of those something went wrong

XXX debug (+ todo comment)

Mopy/bash/brec/common_subrecords.py needed?
EEE need context here?

More fixups for SSE

Mopy.bash.brec.common_records.MreHeaderBase.loadData:
Damn :( - ONAM are FIDS we need the masters already on loading
TES4 - what consoles me is that the (single!) loadData override was
there :P

Took a while to get this one right - see also later commit by Inf where
this is made per game as it should

Saves - check rename player - seems bit broken SSS

Note saves use ints internally - we might want to use FormIds but anyway
saves code needs someDusting

More fixups FFF using mod_dex ->> from_tuple TTT

Maybe inline in long fid?

Mopy.bash.brec.advanced_elements.MelTruncatedStruct.mapFids

Docs same as Mopy.bash.brec.basic_elements.MelOptStruct - use
formAttrs here??

any((rec_val := getattr(record, at)

+  +              ) is not None (?) and rec_val is not ZERO_FID
+  +             for at, dflt in zip(self.formAttrs, self.defaults)):

MelOptStruct

GameInfo.master_fid SSS

game.py# you just defined an instance method

Mopy/bash/patcher/patchers/checkers.py: especially welcome the reduction
of module scope bush uses EEE bush.game.master_fid

Mopy/bash/patcher/patchers/multitweak_assorted.py: WIP XXX

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\events.py", line 178, in _post
    result = listener(*listener_args)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\balt.py", line 812, in _conversation_wrapper
    return func(*args, **kwargs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\patcher_dialog.py", line 173, in PatchExecute
    patchFile.buildPatch(log,SubProgress(progress,0.8,0.9))#no speeding needed/really possible (less than 1/4 second even with large LO)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\patcher\patch_files.py", line 319, in buildPatch
    self.tes4.masters = self.getMastersUsed()
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 329, in getMastersUsed
    block.updateMasters(masters_set.add)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 270, in updateMasters
    record.updateMasters(masterset_add)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 596, in updateMasters
    element.mapFids(self, masterset_add)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 602, in mapFids
    result = function(getattr(record, attr))
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 44, in add
    super().add(element.long_fid[0])
AttributeError: 'tuple' object has no attribute 'long_fid'

That was 'castingSound' - then went ahead and replaced all these form id
tuples with FormIds. Compares faster but most importantly we can now trace
the form ids in the codebase!

bolt.fast_cached_property

functools.cached_property features thread safety via locking for some
reason. The Python core devs have acknowledged that this was bad design
(which costs us measurable performance - about 10s on my Skyrim BP which
takes 5min, so ~3%), see CPython bug 87634. The activity on that issue
seems to be going in the direction of adding a kwarg like nolock=True to
avoid this.

We can gain some more performance by avoiding some other features of
cached_property that we don't need.

More GRUP headers:

These are not so common so we can afford the method calls. There were a
couple fids hiding in here - and lots of hacks.

TTT:
@@ -875,3 +875,3 @@ def getBsb(self):
         if cell.flags.isInterior:
-            baseFid = cell.fid & 0x00FFFFFF
+            baseFid = cell.fid.short_fid & 0x00FFFFFF
             return baseFid % 10, baseFid % 100 // 10

Mopy/bash/brec/record_groups.py:

Note I do not invert block anymore - it is only used as a guard (a check
if it's None should suffice).

More header fixups

longFids/convertFids SSS TTT MelUnion EEE mod_fn instead of mod_id?

Turns out that the hack in MelUnion.setDefault is still needed TTT

mod_id vs [0] EEE

- encapsulate long_id -> _long_id ?

WIP plug in XXX needs rest of the branch

API notes:
- _entering_context internal API param - needed when we create an id
outside of a context - use sparingly, it's the "create record" (as
opposed to "load record") feature, which Bash does not fully implement.
It helps us track creation sites (see also do_unpack change in
99a8b277973126332dfa42a85e59fcafe019d1f5)
- ZERO_FID is also under record creation - this is usually before dump
and needs a FormId instance as we can't call int.dump(). Another use
case to track (initial versions of this branch were creating Tes4Ids on
the spot) EEE
- we should probably check that those ZERO_FIDs are overridden - use
DummyFid for testing (will blow on dump)
- StateError moved in Fid - checked exception would be perfect here
- a bit weird super(MelFid, packer - MelFid should be the only class
responsible for un/packing formids
Initially long_fid was a named tuple - overkill both performance and API
weight

Mopy/bash/parsers.py: _coerce_fid returns a FormId TTT

Thanks Infernio for fixups/reviewing :)

WIP fixups deep in setDefaults

patcher_dialog.py  271 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\patcher_dialog.py", line 173, in PatchExecute
    patchFile.buildPatch(log,SubProgress(progress,0.8,0.9))#no speeding needed/really possible (less than 1/4 second even with large LO)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\patcher\patch_files.py", line 312, in buildPatch
    patcher.buildPatch(log, SubProgress(subProgress, i))
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\game\oblivion\patcher\checkers.py", line 227, in buildPatch
    condition = record.getDefault(u'conditions')
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 552, in getDefault
    return cls.melSet.getDefault(attr)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 189, in getDefault
    return self.defaulters[attr].getDefault()
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 366, in getDefault
    element.setDefault(target)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\advanced_elements.py", line 904, in setDefault
    element.setDefault(record)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\common_subrecords.py", line 201, in setDefault
    next(iter(self.element_mapping.values())).setDefault(record)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 576, in setDefault
    if callable(action): value = action(value)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\utils_constants.py", line 194, in <lambda>
    FID = lambda x: FORM_ID(x)
TypeError: 'NoneType' object is not callable

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\events.py", line 178, in _post
    result = listener(*listener_args)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\balt.py", line 812, in _conversation_wrapper
    return func(*args, **kwargs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\patcher_dialog.py", line 173, in PatchExecute
    patchFile.buildPatch(log,SubProgress(progress,0.8,0.9))#no speeding needed/really possible (less than 1/4 second even with large LO)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\patcher\patch_files.py", line 312, in buildPatch
    patcher.buildPatch(log, SubProgress(subProgress, i))
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\game\oblivion\patcher\checkers.py", line 227, in buildPatch
    condition = record.getDefault(u'conditions')
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 552, in getDefault
    return cls.melSet.getDefault(attr)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 189, in getDefault
    return self.defaulters[attr].getDefault()
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 366, in getDefault
    element.setDefault(target)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\advanced_elements.py", line 904, in setDefault
    element.setDefault(record)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\common_subrecords.py", line 201, in setDefault
    next(iter(self.element_mapping.values())).setDefault(record)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 576, in setDefault
    if callable(action): value = action(value)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\utils_constants.py", line 194, in <lambda>
    FID = lambda x: FORM_ID(x)
TypeError: 'NoneType' object is not callable

Drop __new__ XXX getting:

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\utils_constants.py", line 101, in mod_id
    return self.long_fid[0]
TypeError: 'int' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\patcher_dialog.py", line 173, in PatchExecute
    patchFile.buildPatch(log,SubProgress(progress,0.8,0.9))#no speeding needed/really possible (less than 1/4 second even with large LO)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\patcher\patch_files.py", line 322, in buildPatch
    self.tes4.masters = self.getMastersUsed()
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 327, in getMastersUsed
    block.updateMasters(masters_set.add)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 1225, in updateMasters
    cellBlock.updateMasters(masterset_add)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 935, in updateMasters
    record.updateMasters(masterset_add)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 602, in updateMasters
    element.mapFids(self, masterset_add)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 801, in mapFids
    super().mapFids(record, function, save_fids)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 615, in mapFids
    result = function(getattr(record, attr))
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 44, in add
    super().add(element.mod_id)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\utils_constants.py", line 103, in mod_id
    raise StateError(f'{self!r} not in long format')
bash.exception.StateError: DummyFid(00000000) not in long format

Note:
@@ -44,3 +44,5 @@ def __init__(self, int_val):
         if not isinstance(int_val, int):
-            raise TypeError(f'Only int accepted in FormId: {int_val!r}')
+            ##: re add : {int_val!r} when setDefault is gone - huge performance
+            # impact as it run for all _Tes4Fid and blows - repr is expensive!
+            raise TypeError(f'Only int accepted in FormId')
         self.short_fid = int_val

That was ~15 seconds, duh

action is not FID gets us rid of countless failures of FormId.init when
we pass in a FormId

First pass

WIP

Override str/repr

@@ -486,3 +481,3 @@ def dumpData(self,out):
                 f'Dumping empty record. [{self.inName}: {self.rec_str} '
-                f'{self.fid:08X}]')
+                f'{self.fid.short_fid:08X}]')
         for subrecord in self.iterate_subrecords():

i.long_fid[0] -> use a named tuple!

EEE +    def __new__(cls, sfid, *args, **kwargs): Needed for the action API - added some type checks

record.fid.long_fid.mod_id - not so pretty but none of it is

Mopy/bash/brec/basic_elements.py: load_bytes EEE

worldId.long_fid.mod_id,

Drop -_LongId FFF

@@ -37,5 +36,2 @@
 # Form ids --------------------------------------------------------------------
-
-_LongId = namedtuple('LongId', 'mod_id obj_id')
-
 class FormId:
@@ -67,3 +63,3 @@ class __FormId(cls):
                 def long_fid(self):
-                    return _LongId(fid_tuple[0], self.short_fid)
+                    return fid_tuple[0], self.short_fid
             cls.__master_formid_type[fid_tuple[0]] = __FormId
@@ -90,3 +86,3 @@ def long_fid(self, *, __masters_list=augmented_masters,
                     dex = min(self.short_fid >> 24, __max_masters)
-                    return _LongId(__masters_list[dex], self.short_fid & 0xFFFFFF)
+                    return __masters_list[dex], self.short_fid & 0xFFFFFF
             form_id_type = FormId._form_id_classes[augmented_masters] = _FormID

- decide on caching mod_id/object_dex - Are those operations frequent?->no

- went for EAFP in long_fid - HITMEs should be rare, avoid the min - and
have a line to put a breakpoint on

mod_dex does not make sense for from_tuple - which should be checked for
further inconsistencies TTT

Nit + __repr__ for ModReader

Infernio:
Set _post_masters_sigs per game

Fixes FO4 not launching on this branch. Also renamed them to
_post_masters_sigs (instead of *_sig), since it's a set of sigs.

I think this is cleaner than setting some 'base' signatures in brec and
then unioning in extra ones in the games - plus this way no one can
forget to override them when a new game is added.

Mopy/bash/game/fallout4vr/records.py:
Followup for 525-pt1 merge

The TES4 header for FO4VR has to be updated as well, to handle things
like TNAM correctly.

Mopy/bash/bosh/__init__.py:
We should really traceback here

I guess this could cause problems if we then pop up a wxPython dialog on
boot? Let's see if it blows up for any users.

Mark all records as unchanged on load and dump

Without this change, we will discard all changes we make to loaded
records. Should later be dropped, see comment above the method.

637: Fix NVNM's handling of FormIDs

Similar to VMAD, this needs to explictly call FID() and dump().

637: Fix CTDA's handling of FormIDs

Yay, those classes got even more complex now :P

Side note: Skyrim's CTDA handling was a bit wrong there (would always
treat reference as a FormID), but that probably didn't cause issues
because the unused non-FormID reference is pretty much always zero, and
no amount of messing with masters is going to change the NULL FormID.

637: Support remapping FormIDs

By introducing a special write context that lets both FormIDs with the
old and the new masters resolve. We can do this simply by using a
different indices dict that can handle the new and old masters, we just
have to pass the old masters in.

637: Default to ZERO_FID instead of DUMMY_FID

Otherwise we will end up blowing up, e.g. for PACK in Oblivion. Kept
DummyFid itself around for the uses in record_groups.

Mopy/bash/game/oblivion/records.py:
Mark PACK\PLDT as MelOptStruct

We don't want to dump it out if it wasn't present, and since the FormID
is pretty much never going to be NULL, MelOptStruct is fine here.
Notably, the similar PTDT below was already using MelOptStruct.

Wrapped and py3ified affected lines and the rest of the melSet
definition.

Closes #637
Under #312, #480, #525

Co-authored-by: Infernio <infernio@icloud.com>