Fix regression from screens table removal
Noticed when I renamed a package on the Installers tab.

Utumno:

Nice - permits to track ownership tracking, a hacked-in feature for now.

Fix for init_app_links:

Traceback (most recent call last):
  File "bash\bash.py", line 531, in main
  File "bash\bash.py", line 640, in _main
  File "bash\basher\links_init.py", line 142, in InitStatusBar
  File "bash\env\windows.py", line 1128, in init_app_links
AttributeError: 'str' object has no attribute 'exists'

Probably introduced in fc9e19f5447168ea32cc47e273b34cddbbbb0695

Co-authored-by: MrD <the.ubik@gmail.com>