Bsa conflicts Checking also the esm for a given bsa WIP:
Those methods clearly belong to BSAInfo - just the current use pattern
made me make them static BSAInfos methods - WIP.

TODOs (done later):
- catch errors - on a foreign game bsa:

Traceback (most recent call last):
...
  File "bash\bosh\bain.py", line 2495, in getConflictReport
    srcBSAContents = [y.assets for y in src_bsas]
  File "bash\bosh\bsa_files.py", line 399, in assets
    self.__load(names_only=True)
  File "bash\bosh\bsa_files.py", line 315, in __load
    self.load_bsa_light()
  File "bash\bosh\bsa_files.py", line 444, in load_bsa_light
    file_names = self._read_bsa_file(folder_records, read_file_record)
  File "bash\bosh\bsa_files.py", line 470, in _read_bsa_file
    bsa_file.read(name_size - 1))[0])
  File "bash\bosh\bsa_files.py", line 75, in _decode_path
    raise BSADecodingError(string_path)
bash.bosh.bsa_files.BSADecodingError: Undecodable string '\x00\x008-\x0ft\xb9\xe5Q\xac\xdc\x05\x00\x00;\x85\x00\x00\x0fscripts\\source\x00tp\x0fc\xc6\xcb9\x04@\x13\x00\x00\x17\x8b\x00\x00ad&aZe\xf8\x08\x06\x03\x00\x00W\x9e\x00\x0068$a\xdfv\xe2\x0b0\x03\x00\x00]\xa1\x00\x00c0\rt\x9a\x84\xec P\x02\x00\x00\x8d\xa4\x00'

- rework `srcBSAOrder = BSAInfos.active_bsa_index(src_bsas[0].name)`.
Only checks first bsa order (needs rewrite actually)