TES5VR: Add correct INI paths
Thanks to @Timboman for delivering clear info on these.

Closes #549
Under #454

Mopy/bash/basher/gui_patchers.py:
Escape ampersands in patcher dialog

God, this particular part of wx is annoying. Without this, plugins with
an ampersand in their name will not show that character in the patcher
dialog.

Mopy/bash/patcher/patchers/mergers.py:
Fix _AMerger blowing up on missing GRUPs

Otherwise you get something like this:

Traceback (most recent call last):
  File "bash\basher\patcher_dialog.pyo", line 201, in PatchExecute
  File "bash\patcher\patch_files.pyo", line 248, in scanLoadMods
  File "bash\patcher\base.pyo", line 79, in scan_mod_file
  File "bash\patcher\patchers\mergers.pyo", line 177, in scanModFile
  File "bash\mod_files.pyo", line 182, in __getattr__
ModError: EnchantingAdjustments - WACCF Patch.esp: Failed to retrieve top class for FACT; load factory is <snip>