Regression fixups:
parsers: Another (last one?) #637 regression

Traceback (most recent call last):
  File "bash\balt.py", line 1861, in __Execute
  File "bash\basher\mod_links.py", line 1737, in Execute
  File "bash\parsers.py", line 98, in write_text_file
  File "bash\parsers.py", line 170, in _write_rows
  File "bash\parsers.py", line 73, in _key_sort
  File "bash\parsers.py", line 60, in <lambda>
  File "bash\parsers.py", line 60, in <genexpr>
TypeError: '_FormID' object is not subscriptable

~~Decided to sort by the complete form id - I see no reason why not (?),
this was the behavior for ItemStats~~

Thought twice - if we sort by the full fid then the object_dex would be
unique per mod_fn (hopefully) so no use sorting by eid. Observing that
actually whenever we sorted by fid, we also sorted by eid I simplified,
still not being sure why we sorted by full fid in item stats.

Mopy/bash/game/oblivion/__init__.py: turns out Oblivion needs that too
thanks @lojack5 for pointing it out (and Inf for the code/git digging) -
see comments on commit this was introduced:
e7a31dc960853ae5ebbfebdd58027914d4d022b3

Mopy/bash/game/patch_game.py:
Add missing-implementation records to rec_header.sig_to_class

This will change soon but currently breaks with:

Traceback (most recent call last):
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\gui\events.py", line 178, in _post
    result = listener(*listener_args)
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\basher\app_buttons.py", line 799, in Execute
    PluginChecker.create_or_raise()
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\basher\frames.py", line 481, in create_or_raise
    cls().show_frame()
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\basher\frames.py", line 422, in __init__
    self.CheckMods()
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\basher\frames.py", line 450, in CheckMods
    self.check_mods_text = mods_metadata.checkMods(self, bosh.modInfos,
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\bosh\mods_metadata.py", line 249, in checkMods
    ext_data = ModHeaderReader.extract_mod_data(present_minf,
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\mod_files.py", line 446, in extract_mod_data
    next_header = unpack_header(ins)
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\brec\mod_io.py", line 235, in unpack_header
    raise ModError(ins.inName, f'Bad header signature: '
bash.exception.ModError: Skyrim.esm: Bad header signature: PGRE