Fix for Russian Fallout4 date reading code in save header:
See: https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=171061

Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 89, in <module>
    bash.main(opts)
  File "bash\bash.py", line 411, in main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 3991, in Init
    self.InitData(progress)
  File "bash\basher\__init__.py", line 4033, in InitData
    bosh.saveInfos.refresh(booting=True)
  File "bash\bosh\__init__.py", line 2778, in refresh
    return refresh_infos and FileInfos.refresh(self, booting=booting)
  File "bash\bosh\__init__.py", line 1426, in refresh
    notify_bain=not booting)
  File "bash\bosh\__init__.py", line 1402, in new_info
    notify_bain=notify_bain)
  File "bash\bosh\__init__.py", line 1321, in new_info
    load_cache=True)
  File "bash\bosh\__init__.py", line 405, in __init__
    super(FileInfo, self).__init__(g_path, load_cache)
  File "bash\bosh\__init__.py", line 286, in __init__
    self._reset_cache(self._stat_tuple(), load_cache)
  File "bash\bosh\__init__.py", line 417, in _reset_cache
    if load_cache: self.readHeader()
  File "bash\bosh\__init__.py", line 1116, in readHeader
    self.header = self.save_header_type(self.abs_path)
  File "bash\bosh\save_headers.py", line 60, in __init__
    self.load_header(ins)
  File "bash\bosh\save_headers.py", line 79, in load_header
    self.calc_time()
  File "bash\bosh\save_headers.py", line 382, in calc_time
    days = int(days[:-1])
ValueError: invalid literal for int() with base 10: '0\xd0'