UnicodeDecode errors monkey patches:
Closes #180.

UnicodeDecodeError in initLinks in french locale:

    Traceback (most recent call last):
      File "Wrye Bash Launcher.pyw", line 87, in <module>
	  File "bash\bash.pyo", line 574, in main
	  File "bash\basher.pyo", line 18921, in InitLinks
	  File "bash\basher.pyo", line 18291, in InitStatusBar
	  File "bash\bolt.pyo", line 2470, in deprint
	  File "StringIO.pyo", line 271, in getvalue
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 37: ordinal not in range(128)

Line 18291 (!) corresponds to:
deprint(_(u'Error finding icon for %s:') % target.s,
                                 traceback=True)

Moved the fix inside deprint - deprint raising is a bit of a nono.

See: http://stackoverflow.com/q/28660700/281545

Attempted workaround for UnicodeDecodeError on tmp dir creation:

Apparently fails if username has non ascii chars in it:

Traceback (most recent call last):
  File "bash\bash.pyo", line 382, in main
  File "bash\bosh.pyo", line 10347, in testUAC
  File "bash\bolt.pyo", line 657, in tempDir
  File "tempfile.pyo", line 331, in mkdtemp
  File "ntpath.pyo", line 84, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 7: ordinal not in range(128)

Left traceback.print_exc() in so we get some input.
Workaround adapted from: http://bugs.python.org/issue1681974
See: http://stackoverflow.com/q/28101187/281545

Mopy/bash/barb.py:
Using Path.sys_fs_enc instead of querying sys.