Jump to the mod's installer from the mods tab - #53:
Added Mod_JumpToInstaller link and Ctrl+click shortcut in the mods tab
Had to patch up EnsureVisible - removing a `_glist` use from basher -
see #163. Still a wip - added offhand focus parameter and
SashPanel.SelectUIListItem() but the code around EnsureVisible definitely
needs love. Note also that is not used as often as it should - moving
an installer from menu ("Move To...") does not use it at all.

When I cancel refresh of the installers tab, jump_to_mods_installer is
still called leading to:

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 992, in OnLeftDown
    if self.jump_to_mods_installer(mod_clicked): return
  File "bash\basher\__init__.py", line 1055, in jump_to_mods_installer
    balt.Link.Frame.notebook.SelectPage('Installers', installer)
  File "bash\basher\__init__.py", line 3518, in SelectPage
    tabInfo[page_title][2].SelectItem(GPath(item))
  File "bash\basher\__init__.py", line 276, in SelectItem
    self.uiList.SelectItem(item)
  File "bash\balt.py", line 1910, in SelectItem
    dex = self.GetIndex(item)
  File "bash\balt.py", line 2029, in GetIndex
    return self._gList.FindIndexOf(item)
  File "bash\balt.py", line 1553, in FindIndexOf
    return self.FindItemData(-1, self._item_itemId[item])
KeyError: bolt.Path(u'ULComp167-19370-1.7z')

but I consider this not important (and we need to refactor ShowPage
anyway, so adding yet another `refreshed` attribute is a nono).

Closes #53.

Signed-off-by: MrD <the.ubik@gmail.com>