Regression fixup in error printing for too many plugins:
TypeError: unicode string or integer address expected instead of \
PluginsFullError instance -> 3448ce9eacba1e3faff36ccbdbdc7a9b018e4a82
bain: some nit from __future__