(Some) Other places we need filename validation:
askFilename moved to Installers_Link (maybe move to UIList and override
for various Lists)

askFilename(check_exists)

Had to add yet another param in askFilename - first we centralize, then
we can come up with some more elegant validation way.

Allow archive extensions in project names:

Initially I had added code to disallow archives extensions but then
I don't see why not - maybe we used the extension to check for projects?
Anyway let the user decide - I did absorb the is_file check though

Under #580

Infernio:
Fix regression in Unpack to Project(s):

Traceback (most recent call last):
  File "bash\balt.py", line 1762, in __Execute
  File "bash\balt.py", line 810, in _conversation_wrapper
  File "bash\basher\installer_links.py", line 1015, in Execute
  File "bash\basher\__init__.py", line 127, in _askFilename
AttributeError: 'InstallerArchive_Unpack' object has no attribute 'dialogTitle'

Also track down 'dialogTitle', now just a method param in balt/bain.

Make _askFilename accept Paths

Not sure when this broke, but at least *some* usages of _askFilename
pass paths in, which breaks once we pass them as a default to askText.

Co-authored-by: Infernio <infernio@icloud.com>