askText now strips + a couple of `except:` fixed:
Just note how much ugly duplicate code this eliminates, annoyed me since
forever

Review "strip=false" in gui_patchers.py. Also we used to allow empty
player name (saves_links.Save_RenamePlayer) and empty save profile
name in Saves_ProfilesData - disallowed - profiles one would result in:

Traceback (most recent call last):
  File "bash\balt.py", line 1284, in DoAdd
    index = self._list_items.index(newItem)
ValueError: u'  ' is not in list

Corrected some `except:` I came accross - that's what I mean when I say
that warnings must be corrected when nearby code is revisited (not en
masse).