[!]WIP skip OBME records from vanilla tweaks:
patcher_dialog.py  310 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 194, in PatchExecute
  File "bash\mod_files.py", line 310, in used_masters_by_top
  File "bash\brec\record_groups.py", line 105, in updateMasters
  File "bash\brec\record_structs.py", line 608, in updateMasters
  File "bash\brec\complex_subrecords.py", line 861, in mapFids
  File "bash\brec\basic_elements.py", line 483, in mapFids
  File "bash\brec\complex_subrecords.py", line 710, in mapFids
AttributeError: 'MelObject' object has no attribute '_effect_sig_as_int'
or
AttributeError: 'MelObject' object has no attribute 'resist_av'
etc

There is 480-records-refactoring-pt3 tagging along since 2022 where
setDefault is removed - this is the right solution, it was a hell
pinning this, as the version 1.07 that was up on Nexus seemed to work
fine - see:
https://discord.com/channels/537706885965676554/537710082755133460/1514941094532747314
https://www.nexusmods.com/oblivion/mods/53020?tab=logs
What probably happens here is that the user was using an xEdit modified
file. xEdit uses a different definition for effects so we end up not
loading anything and getting AttributeError on random attributes while
iterating (in random order) over the set of _obme_form_elements in
MelEffectsTes4.mapFids. I close the case but also stash an [!] so you
know when some other OBME record sneaks in - and because we probably
could patch this.

Under #480