Another path fix - there are more I'm sure:
bash.bolt.BoltError: Error creating required Wrye Bash directories.  \
Please check the settings for the following paths in your bash.ini, \
the drive does not exist:

A path error was the result of relative paths.  The following paths are \
causing the errors, however usually a relative path should be fine.  \
Check your setup to see if you are using symbolic links or NTFS Junctions:

/mnt/win/GAMES/TESIV/Oblivion/..\Oblivion Mods/Bash Mod Data
/mnt/win/GAMES/TESIV/Oblivion/..\Oblivion Mods