squash!     Make mergeability_checks a dict: SSS EEE
Turns out has_esl was used while only __init__ had been called - in tests:

FAILED Mopy/bash/tests/test_bosh/test_cosaves.py::TestxSECosave::test_has_accurate_master_list -
 AttributeError: 'SteamEnderalGameInfo' object has no attribute 'has_esl'

I went in some pains as seen here to initialize the game dirs in Game init
and therefore absorb post_init in there. The hasty game_ini_path is not
the pinnacle of elegance but boot wasn't really made more complex - plus
setting the dirs will be more complicated thanks to SF (and more cli
arguments?) - so let's have all the pieces together till we split it
anew.

This is just a hack would blow for SVR
-------------------------- Mopy/bash/game/__init__.py --------------------------
index 73dd10f54..b49a805b0 100644
@@ -394,3 +394,3 @@ class GameInfo(object):

-    def __init__(self, gamePath, opts, init_warnings):
+    def __init__(self, gamePath, *args):
         self.gamePath = gamePath # absolute bolt Path to the game directory
@@ -398,4 +398,4 @@ def __init__(self, gamePath, opts, init_warnings):
         #--They depend on setting the bash.ini and the game
-        self.game_ini_path = initialization.init_dirs(opts, self,
-                                                      init_warnings)
+        if args:
+            self.game_ini_path = initialization.init_dirs(self, *args)
         self._init_plugin_types()

------------------------- Mopy/bash/initialization.py -------------------------
index 7999dd44e..1b99dc7f3 100644
@@ -107,3 +107,3 @@ def _get_ini_path(ini_key, dir_key, *args):

-def init_dirs(opts, game_info, init_warnings):
+def init_dirs(game_info, opts, init_warnings):
     """Initialize bass.dirs dictionary. We need the bash.ini and the game

Mopy\bash\game\__init__.py:401: in __init__
    self._init_plugin_types()
Mopy\bash\game\__init__.py:911: in _init_plugin_types
    pflags.error_msgs = {pflags[k]: {(h, msg % fmt): lam for (h, msg), lam
C:\hostedtoolcache\windows\Python\3.12.6\x64\Lib\enum.py:814: in __getitem__
    return cls._member_map_[name]
E   KeyError: <EslPluginFlag.ESL: ('esl_flag', '_is_esl', 4096, <MergeabilityCheck.ESL_CHECK: 1>, 253)>