Fix regression in BAIN wizards
A token may be created without a type or parser, at which point we'd
fail with an AttributeError:

Traceback (most recent call last):
  File "bash\belt.py", line 744, in Continue
  File "bash\ScriptParser.py", line 541, in RunLine
  File "bash\ScriptParser.py", line 405, in __call__
  File "bash\ScriptParser.py", line 297, in __call__
  File "bash\ScriptParser.py", line 607, in ExecuteTokens
  File "bash\ScriptParser.py", line 744, in ExecuteRPN
  File "bash\ScriptParser.py", line 333, in __init__
AttributeError: 'NoneType' object has no attribute 'getType'

Broke in c55b60dfee2cb4337ddbcb056075d0cb76ee818b.