WIP Mopy/bash/tests/test_localize.py:
Where we meet our old friend the boot sequence in new surroundings.
Note:

- I don't use setup locale in _emulate_startup
- the tests passed but if we add wx code they may blow (currently
  InitLocale is not overriden, and this might or might not make a
  difference for wx)
- in view of the above installing() the gettext and setting the locale
  must be separated - see if we can do the one without the other?
- weird fact: I had to keep the wx App around otherwise the CI *hangs*
  (not blows or fails) on testing setup_locale! This is what the CI log
  shows:

python -m pytest
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
	pythonLocation: C:\hostedtoolcache\windows\Python\3.9.9\x64
============================= test session starts =============================
platform win32 -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: D:\a\wrye-bash\wrye-bash
collected 122 items

Mopy\bash\tests\test_bolt.py ........................................... [ 35%]
.                                                                        [ 36%]

CI hang fix - keep the wx app around -> needed for the locale calls?

- wx.ArtProvider had nothing to do with the CI hanging - "unfortunately"
  wx calls pass just fine - so we still can't reproduce on the CI the
  user failure:

Traceback (most recent call last):
  File "bash\bash.py", line 287, in main
  File "bash\bash.py", line 454, in _main
  File "bash\basher\__init__.py", line 4215, in Init
  File "bash\basher\__init__.py", line 3840, in __init__
  File "bash\basher\__init__.py", line 3612, in __init__
  File "bash\basher\__init__.py", line 2015, in __init__
  File "bash\basher\__init__.py", line 245, in __init__
  File "bash\basher\__init__.py", line 1476, in __init__ # wx.ArtProvider.GetBitmap(wx.ART_PLUS, size=(16, 16)),
wx._core.wxAssertionError: C++ assertion "wxString::Format("%.3f", 1.23).find(str) != wxString::npos" failed at ..\..\src\common\intl.cpp(1633) in `anonymous-namespace'::GetInfoFromLCID(): Decimal separator mismatch -- did you use setlocale()?If so, use wxLocale to change the locale instead.

- getlocale failed *for both cases* with:

Run python -m pytest
============================= test session starts =============================
platform win32 -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: D:\a\wrye-bash\wrye-bash
collected 122 items

Mopy\bash\tests\test_bolt.py ........................................... [ 35%]
.                                                                        [ 36%]
Mopy\bash\tests\test_localize.py FF                                      [ 37%]
Mopy\bash\tests\test_bosh\test_cosaves.py .............................. [ 62%]
..                                                                       [ 63%]
Mopy\bash\tests\test_bosh\test_list_info.py .                            [ 64%]
Mopy\bash\tests\test_bosh\test_loot_parser.py .......................... [ 86%]
.................                                                        [100%]

================================== FAILURES ===================================
____________________________ test_setlocale_pl_PL _____________________________

capsys = <_pytest.capture.CaptureFixture object at 0x000001BF341C07C0>

	def test_setlocale_pl_PL(capsys):
		"""Test setting locale to default."""
		with capsys.disabled():
>           setup_locale('pl_PL', __wx)

Mopy\bash\tests\test_localize.py:35:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Mopy\bash\localize.py:126: in setup_locale
	f"{locale.getlocale()}'")
C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\locale.py:593: in getlocale
	return _parse_localename(localename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

localename = 'pl-PL'

	def _parse_localename(localename):
 ...
			return None, 'UTF-8'
>       raise ValueError('unknown locale: %s' % localename)
E       ValueError: unknown locale: pl-PL

C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\locale.py:501: ValueError
____________________________ test_setlocale_nocli _____________________________

capsys = <_pytest.capture.CaptureFixture object at 0x000001BF3412CF40>

	def test_setlocale_nocli(capsys):
		"""Test setting locale to pl_PL."""
		with capsys.disabled(): # https://stackoverflow.com/a/41533292/281545
>           setup_locale('', __wx)

Mopy\bash\tests\test_localize.py:46:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Mopy\bash\localize.py:126: in setup_locale
	f"{locale.getlocale()}'")
C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\locale.py:593: in getlocale
	return _parse_localename(localename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

localename = 'en-US'

	def _parse_localename(localename):
...
>       raise ValueError('unknown locale: %s' % localename)
E       ValueError: unknown locale: en-US