Implement tagging the build with the commit sha:
WIP, missing specs for the WB_FILEVERSION and whether I should be
using a dash here - see the lowercase todo in build.py to be addressed
in next commit. Product version is not displayed in Explorer >
Properties > Details - (very) minor [!]. Note I changed the OSError to
a ValueError, seems more appropriate here. Note also I dropped the
second nightly regex check - we want the full version string to be in
the previous build IIUC. DIST_PATH is supposed to contain just the
previous build, and the version string should appear in each and every
artifact, so whatever you get with next(), except if the folder doesn't
exist or is empty, where you get OSError/StopIteration. Note we used to
remove DIST_PATH *before* the version check, virtually invalidating the
check (which is why we didn't ever get "IndexError" in parent commit,
b40838baa997d22a1020c11d2fa3113e7ec96a81 - I now remove the dist dir
after I do the dist check which makes more sense also if we raised a VE
on invalid/same build version, as we should keep the previous build).

Seems VIProductVersion must be in n 4-part numeric X.X.X.X format

Command line defined: "WB_FILEVERSION=315.2026"
...
Processing script file: "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\scripts\build\installer\main.nsi" (ACP)

Processed 1 file, writing output (x86-unicode):
Error: invalid VIProductVersion format, should be X.X.X.X
Error - aborting creation process

Note X.X.X.X-789abcd passes. In this case File Version is displayed as
X.X.X.X as if we didn't add the -789abcd part.

Under #675 - this was also the original scope - see also next commit.