WIP use precompiled struct unpackers:
This is not so much about performance as for centralizing the handling
of packers and unpackers so we can further extend/error check etc.
Note we should really only override loadData in brec - note similarity
in some of the overrides. Sometimes using EAFP for errors (and avoiding
if checks) could lead to cleaner code - note also using dictionaries to
the same end.
Re: optimization, note that apart from using precompiled Struct, we
also bring stuff to local scope. This is done with the dunder prefixed
function parameters - they are not meant to be used by clients.
Unfortunately this introduces more `.unpack` occurrences - fortunately
you can search for the calls with (?<!\))\.unpack\b

MelCtda fixups - don't pay much attention Infernio fixed those for good
in Rewrite CTDA handling

Mopy/bash/game/oblivion/records.py: This was blowing as:

out.packSub('CTDA','B3sfI'+ record.form12 + '4s',

is always writing record.unused2 - so form12 must be len 2. But then I
must read a str in and not an int

mod_io.py  368 packSub: <bash.brec.mod_io.ModWriter object at 0x27F4B1B0>: Failed packing: CTDA, B3sfIIi4s, (0, '\x00\x00\x00', 1.0, 71, 109893, 0, 0)
Traceback (most recent call last):
  File "bash\brec\mod_io.py", line 355, in packSub
    if values: data = struct_pack(data, *values)
error: argument for 's' must be a string

However rest of files were using record.form12345 to pack *all* record
attrs - this looks it would blow but for only the biggest possible sizes
(32 skyrim, 28 fallout) - so was it intended to always write the bigger
ones (as Oblivion) or should we chop off the attrs as I do? In that
case we should not fill them with null4 and try packing them with 'I'..

Mopy/bash/brec/mod_io.py: this was completely swallowed - should we raise?

@@@ -366,4 -366,4 +366,9 @@@ class ModWriter(object)
              bolt.deprint(u'%r: Failed packing: %s, %s, %s' % (
  <<<<<<< HEAD
 +                self, sub_rec_type, data, values))
 +            raise
  =======
+                 self, sub_rec_type, data, values), traceback=True)
+             # raise ??
  >>>>>>> abe4c1b0f... MelCtda fixups SSS XXX TTT

lol :D

Infernio: Carried edits to Nehrim