Hacky fix for version being None in status bar buttons:
Wrye Bash encountered an error.
Please post the information below to the official thread at
https://afkmods.com/index.php?/topic/4966-wrye-bash-all-games
or to the Wrye Bash Discord at
https://discord.gg/NwWvAFR

Traceback (most recent call last):
  File "bash\bash.py", line 193, in main
    _main(opts)
  File "bash\bash.py", line 377, in _main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4030, in Init
    frame = BashFrame() # Link.Frame global set here
  File "bash\basher\__init__.py", line 3684, in __init__
    self.SetStatusBar(BashStatusBar(self))
  File "bash\balt.py", line 2858, in __init__
    self.UpdateIconSizes()
  File "bash\basher\__init__.py", line 3569, in UpdateIconSizes
    self._addButton(link)
  File "bash\balt.py", line 2873, in _addButton
    gButton = link.GetBitmapButton(self)
  File "bash\basher\app_buttons.py", line 203, in GetBitmapButton
    window, self.images[idex].GetBitmap(), onRClick)
  File "bash\basher\app_buttons.py", line 87, in GetBitmapButton
    tooltip=self.sb_button_tip)
  File "bash\basher\app_buttons.py", line 135, in sb_button_tip
    return self._tip + u' ' + self.version
  File "bash\basher\app_buttons.py", line 125, in version
    version = self.exePath.strippedVersion
  File "bash\bolt.py", line 805, in strippedVersion
    version = list(self.version)
TypeError: 'NoneType' object is not iterable

Example files from debug print added:

------------------------------ Mopy/bash/bolt.py ------------------------------
index 08ce2862b..1574fec9b 100644
@@ -600,3 +600,7 @@ def version(self):
         from env import get_file_version
-        return get_file_version(self._s)
+        version_ = get_file_version(self._s)
+        if version_ is None:
+            print u'%s version is None' % self.s
+            version_ = ()
+        return version_

C:\GAMES\TESIV\Oblivion\Tools\TES4Edit_3_0_15_EXPERIMENTAL-11536\TES4Edit.exe version is None
C:\GAMES\TESIV\Oblivion\Tools\TES4LODGen_3_0_15_EXPERIMENTAL-15781\Tes4LodGen.exe version is None

From the discussion in 45ca86ae4e15c850f7225fb19631c702bb8e0a03 turns
out that pywin 225 blows for me but not for Infernio
Those dll issues remind the situation with loot that blows for
some people but not for others - for now let's limit pywin and
patch the linux method to return an empty tuple instead of None

Mopy/bash/env.py: remove redundant parentheses warn