Fixups for case insensitive paths compare in core BAIN (and more):
Wrong comparisons introduced in a34b27aea5ab8a726bc5911ee1a26ff9db8a31df

Refactored slightly and added comments for readability and possible
enhancements.

    # This is the 2nd commit message:

Renamed deleted -> deleted_or_pending for readability, added comments
on groupby.

    # This is the 3rd commit message:

Comments in _plugins_cache_wrapper from load order refactoring (in undo
I returned None)

  # This is the 2nd commit message:

refreshMissingStrings -> _refreshMissingStrings. Tried to move it
before load order check to get (in Skyrim)

Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 431, in main
    frame = app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4257, in Init
    self.InitData(progress)
  File "bash\basher\__init__.py", line 4292, in InitData
    bosh.modInfos.refresh()
  File "bash\bosh\__init__.py", line 3421, in refresh
    hasMissingStrings = hasChanged and self._refreshMissingStrings()
  File "bash\bosh\__init__.py", line 3462, in _refreshMissingStrings
    bad = set(fileName for fileName, fileInfo in self.iteritems() if
  File "bash\bosh\__init__.py", line 3463, in <genexpr>
    fileInfo.isMissingStrings())
  File "bash\bosh\__init__.py", line 2578, in isMissingStrings
    return modInfos.isMissingStrings(self.name)
  File "bash\bosh\__init__.py", line 3911, in isMissingStrings
    bsaPaths = self.extra_bsas(modInfo)
  File "bash\bosh\__init__.py", line 3954, in extra_bsas
    iniFiles = self._ini_files(descending=descending)
  File "bash\bosh\__init__.py", line 3943, in _ini_files
    iniPaths = (self[name].getIniPath() for name in self.activeCached)
  File "bash\bosh\__init__.py", line 3350, in activeCached
    return self.plugins.lord.activeOrdered
AttributeError: 'NoneType' object has no attribute 'activeOrdered'

hence the comment

  # This is the 3rd commit message:

Copy conflicts - since the conflicts project will be created we need
to bump up the numbers of the subpackages - reported by @alt3rn1ty:
http://forums.bethsoft.com/topic/1602198-wrye-bash-thread-109/page-3#entry25149332

Needs more work - creates invalid packages if complex packages are
involved.