Drop MelObject hash:
As discussed - MelObject is mutable so should *not* be used in sets:

>>> from Mopy.bash.brec import MelObject
>>> class M(MelObject): pass
>>> m=M()
>>> m.a=[1]
>>> s={m}
>>> m in s
True
>>> m.a.append(2)
>>> m in s
False

See also discussion of when we probably stopped using those is sets in
https://github.com/wrye-bash/wrye-bash/commit/9607d8d28ebedf51c00e7e51672319e4e2f4e44a#commitcomment-78126537

I went for TypeError as:

>>> {}[[]]
Traceback (most recent call last):
  File "C:\_\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: unhashable type: 'list'

Mopy/bash/game/fallout4vr/records.py missing import!