Fixup in apply embedded:
Traceback (most recent call last):
  File "bash\balt.py", line 1826, in __Execute
    # After every 30 added items, add a break in the menu to avoid having
  File "bash\balt.py", line 875, in _conversation_wrapper
    _singleCell = False # allow only single selections (no ctrl/shift+click)
  File "bash\basher\installer_links.py", line 1275, in Execute
    if not destinations: return # destinations == [dest] if all was ok
  File "bash\bosh\bain.py", line 1900, in applyEmbeddedBCFs

  File "bash\bosh\bain.py", line 1915, in apply_converter
    #--Extract the embedded BCF and move it to the Converters folder
  File "bash\bosh\converters.py", line 365, in apply
    self._unpack(srcInstaller, files,
  File "bash\bosh\converters.py", line 606, in _unpack
    for archive in map(subTempDir.join, subArchives):
  File "bash\bosh\converters.py", line 587, in _unpack
    installerCRC = srcInstaller.crc
AttributeError: 'Path' object has no attribute 'is_archive'

Squash: Gpath not needed here
Mopy/bash/fomod.py: rename conditions (records code)

Infernio:

Mopy/bash/bosh/bain.py: fix regression from 'Data' commit -
6471cda084147c17606c8f9cb6a1f581de5abce3

Also fixed a random typo in the vicinity (% s -> %s).