Catch another corrupted ini crash:
Mopy/bash/bosh/ini_files.py: fixup following up
8c9537f103c30d05842bc3a2378a48e3619b978c. When installers was enabled on
boot Bash would CTD.

Traceback (most recent call last):
  File "bash\bash.py", line 259, in main
    _main(opts)
  File "bash\bash.py", line 425, in _main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4003, in Init
    frame.RefreshData(booting=True)
  File "bash\balt.py", line 1605, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\__init__.py", line 3771, in RefreshData
    refresh_target=True)
  File "bash\balt.py", line 1605, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\__init__.py", line 2837, in ShowPanel
    scan_data_dir)
  File "bash\balt.py", line 1605, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\bosh\bain.py", line 1474, in _projects_walk_cache_wrapper
    return func(self, *args, **kwargs)
  File "bash\basher\__init__.py", line 2867, in _refresh_installers_if_needed
    refresh_info)
  File "bash\bosh\bain.py", line 1546, in irefresh
    oblivionIni.setBsaRedirection(True)
  File "bash\bosh\ini_files.py", line 618, in setBsaRedirection
    self.saveSetting(u'Archive',u'sArchiveList',sArchives)
  File "bash\bosh\ini_files.py", line 547, in saveSetting
    self.saveSettings(ini_settings)
  File "bash\bosh\ini_files.py", line 275, in saveSettings
    line = unicode(line,'cp1252')
  File "C:\_\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 48: character maps to <undefined>

Under #326.

Strange -> Bash won't ctd will display the quit dialog but boot ok after
the work in parent commit - since parent commit was fixed, so destroys
windows, it would boot and display the quit dialog, which now would quit

Under #373.