[!]bosh.bain:
Important patch drastically reducing bosh size. I had to move the
tmp dir stuff out of Installer as it lead to very nasty cyclic imports
between bosh.bain and bosh.converters. This is welcome, as those tmp dir
belong to module scope and Installer namespace could not use enough
cleanup, but still a WIP - tmp files handling needs thought (and more
finally blocks). Note the local import of bolt in bass - not good.
Local imports (there were some introduced in bosh.bain.py too, notably
singleton ones like modinfos) are always a smell - search for them via
`^[ ]+from`

Note the reduce introduced - necessary to keep backwards settings
compatibility

+    def __reduce__(self):
+        from . import InstallerMarker as boshInstallerMarker
+        return boshInstallerMarker, (GPath(self.archive),), tuple(
+            imap(self.__getattribute__, self.persistent))

Took a bit to get this right - and actually I later realized that
initDefault is called two times on unpickling (`__reduce__` calls
`__init__` which calls initDefault), however I did not drop it from
`__setstate__`, as when updating from older versions __init__ is not
called on unpickling so setstate fails with:

Traceback (most recent call last):
  ...
  File "bash\bosh\bain.py", line 1621, in __load
    self.dictFile.load()
  File "bash\bolt.py", line 1471, in load
    self.data.update(cPickle.load(ins))
  File "bash\bosh\bain.py", line 297, in __setstate__
    else: dest_scr = self.refreshDataSizeCrc()
  File "bash\bosh\bain.py", line 556, in refreshDataSizeCrc
    object.__getattribute__(self,attr).clear()
AttributeError: skipExtFiles

New settings are loaded fine by older versions, but apparently first
time new version pickles reduce adds some stuff that calls init. Still
I don't get all the details - will have to ask. Nice post that helped:
http://stackoverflow.com/a/30700077/281545

Note also:
@@ -1725,2 +1727,3 @@ def _refreshInstallers(self, progress, fullRefresh, refresh_info, deleted,
         # in irefresh and also add extra processing for deleted files
+        from . import InstallerArchive, InstallerProject # use the bosh types
         progress = progress or bolt.Progress()
@@ -1581,2 +1581,3 @@ def hidden_dir(self): return bass.dirs['modsBash'].join(u'Hidden')
     def add_marker(self, name, order):
+        from . import InstallerMarker
         self[name] = InstallerMarker(name)
@@ -1596,3 +1597,3 @@ def irefresh(self, progress=None, what='DIONSC', fullRefresh=False,
         #--Archive invalidation
-        from . import oblivionIni
+        from . import oblivionIni, InstallerMarker
         if bass.settings.get('bash.bsaRedirection') and oblivionIni.abs_path.exists():
Another needed hack as the rest of the code checks isinstance on the
bosh types.
And a fixup in renaming markers:
@@ -1026,3 +1026,3 @@ def renameInstaller(self, name_new, data):
         if newName == archive:
-            return False
+            return False, False, False
         #--Add the marker to Bash and remove old one
More to come in next commit.

Under #201 - bosh went from 7448 to 4874 lines.