Plug save_files.py to Bash:
Compare readability/better design:

@@ -2017,3 +2017,3 @@ def DoSave(self):
             saveInfo.header.masters = self.uilist.GetNewMasters()
-            saveInfo.header.writeMasters(saveInfo.getPath())
+            saveInfo.write_masters()
             saveInfo.setmtime(prevMTime)

Note also the header attributes are not enforced in a comment - note the
difference between that comment and the SaveHeader class (gameDays)

Initially I only imported save_files locally - this crashed oblivion -
for links see #360.

Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 441, in main
  File "bash\basher\__init__.py", line 4033, in Init
  File "bash\basher\__init__.py", line 4083, in InitData
  File "bash\bosh\__init__.py", line 3702, in refresh
  File "bash\bosh\__init__.py", line 2424, in refresh
  File "bash\bosh\__init__.py", line 1591, in getHeaderError
  File "bash\bosh\__init__.py", line 2156, in readHeader
ImportError: No module named save_files

http://forums.bethsoft.com/index.php?app=forums&module=forums&section=findpost&pid=25304464

Mystery remains (game/oblivion/patcher/special importing bosh in bush is
the cause most probably) - fixed by moving the import to module scope.

Under #349.