[!]Regression in sound patcher II:
Follow up for 185b2a79ab5a4d5a1873e5c1bac0ad2335ba18e6
Turns out that in brec.MelStruct#loadData the self.attrs
does not look at getSlotsUsed of the MreSound record - so:

'MreSoun' object has no attribute 'minDist1'
Error loading 'SOUN' record and/or subrecord: 00025411
  eid = u'BlockLight'
  subrecord = 'SNDD'
  subrecord size = 8
  file pos = 268927
Error in Oblivion.esm
parsers.py 4015 load:
Traceback (most recent call last):
  File "bash\parsers.py", line 4009, in load
    self.tops[label].load(ins, unpack and (topClass != MobBase))
  File "bash\record_groups.py", line 70, in load
    ins.tell() + self.size - self.header.__class__.size)
  File "bash\record_groups.py", line 172, in loadData
    record = recClass(header,ins,True)
  File "bash\brec.py", line 1665, in __init__
    self.__class__.melSet.initRecord(self,header,ins,unpack)
  File "bash\brec.py", line 1212, in initRecord
    MreRecord.__init__(record,header,ins,unpack)
  File "bash\brec.py", line 1460, in __init__
    if ins: self.load(ins,unpack)
  File "bash\brec.py", line 1523, in load
    self.loadData(ins,inPos+self.size)
  File "bash\brec.py", line 1674, in loadData
    self.__class__.melSet.loadData(self,ins,endPos)
  File "bash\brec.py", line 1241, in loadData
    loaders[Type].loadData(record,ins,Type,size,readId)
  File "bash\game\oblivion\records.py", line 2079, in loadData
    MelStruct.loadData(self, record, ins, sub_type, size, readId)
  File "bash\brec.py", line 963, in loadData
    setter(attr,value)
AttributeError: 'MreSoun' object has no attribute 'minDist1'

This halted loading of Oblivion.esm and therefore later on the patch
procedure crashed:

MERGE/SCAN ERROR: Unofficial Oblivion Patch.esp
Traceback (most recent call last):
  File "bash\balt.py", line 416, in <lambda>
    if onButClick: self.Bind(wx.EVT_BUTTON, lambda __event: onButClick())
  File "bash\balt.py", line 1558, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\patcher_dialog.py", line 203, in PatchExecute
    patchFile.scanLoadMods(SubProgress(progress,0.2,0.8)) #try to speed this up!
  File "bash\patcher\patch_files.py", line 253, in scanLoadMods
    patcher.scanModFile(modFile,nullProgress)
  File "bash\patcher\patchers\special.py", line 168, in scanModFile
    levLists[listId].mergeOverLast = True
KeyError: (bolt.Path(u'Oblivion.esm'), 247796)

Apparently the u'BlockLight' uses the 'SNDD' SOUN subrecord instead of
SNDX. Solved by renaming the attributes into the same names - hopefully
no SOUN record contains both SNDD and SNDX subrecords. However the
SNDD overrides dumpData and setDefault to no-op - are the SNDX
overrides used ? For dumpData I guess yes but for setDefault dunno -
dunno what this entails either so [!]

Signed-off-by: MrD <the.ubik@gmail.com>