Drop Export/Import Stats link for Skyrim
Starting raising errors in cb32315426e64989264be355cdbaa1bcb4139cd4, but
it wasn't working properly before that either.

The convertToLongFids() call introduced there works fine in the patcher
where only readFromMod is used. However, it breaks the Import Stats link,
which uses writeToMod. That method has to load with LoadFactory's
keepAll feature, which will load all tops with MobBase. That means it
can't do a blanket convertToLongFids() call, because MobBase does not
implement convertFids, leading to this traceback:

Traceback (most recent call last):
  File "bash\balt.py", line 1792, in __Execute
    self.Execute()
  File "bash\basher\mod_links.py", line 1935, in Execute
    changed = self._import(ext, textDir, textName, textPath)
  File "bash\basher\mod_links.py", line 1897, in _import
    changed = parser.writeToMod(self._selected_info)
  File "bash\parsers.py", line 1491, in writeToMod
    modFile.convertToLongFids()
  File "bash\parsers.py", line 4120, in convertToLongFids
    selfTops[type].convertFids(mapper,True)
  File "bash\record_groups.py", line 151, in convertFids
    raise AbstractError
bash.exception.AbstractError: Abstract section called.

Of course, we can't just not convert to long fids either - Otherwise we
won't be able to handle critical effects. The only solution, for now, is
to remove the Export/Import Stats links for Skyrim. Will be revisited in
the parser ABC merge.

Note that this once again goes to show that the whole ModFile API is a
big footgun right now :)
Ideally, we'd make ModFile.load automatically convert to long fids, and
ModFile.save automatically convert back to short fids to avoid this
whole debacle - see future tweak pooling merge for some more work in
this direction.

Threw in some stuff taken from future tweak pooling merge (
bolt.floats_equal, unused load_unpack/load_UI dropped, etc.).