Load order comments etc WIP:
Mopy/bash/_games_lo.py: trying to write docs for this, help, under #309

'name' renames - 13 more .s

Especially happy about Mopy/bash/gui/top_level_windows.py, moral: don't
name your parameters 'name' (I think it needed to be a kwarg on older wx)

Mopy/bash/basher/bsa_links.py: not project.s haven't we just checked if
result is a truish string? See how difficult is to reason if this check
is needed with all the GPath transformations going on.

Mopy/bash/bolt.py:

Note slight change in Path.list() - it will now blow on an existing file
as oposed to an existing dir

os.listdir('jj')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
OSError: [Errno 2] No such file or directory: 'jj'
os.listdir("ttt.txt")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
OSError: [Errno 20] Not a directory: 'ttt.txt'

Under #543, #368

Renames - OSError, IOError

Mopy/bash/basher/__init__.py
Mopy/bash/bosh/__init__.py: renames
_updated, _deleted_ was from I was debugging refresh needed to
stand out - will be the basis for an event refresh mechanism

I added some IOError cause recent do_update WIP broke with IOError when
I was expecting OSError - python 3 can't come soon enough. Changed the
order to most usual OSError, IOError to replace easily with OSError on
py3