Debug prints for invalid paths error and nitpick:
Triggered by:
http://forums.bethsoft.com/topic/1602198-wrye-bash-thread-109/?p=25145760

Traceback (most recent call last):
  File "bash\balt.py", line 2371, in __Execute
    self.Execute()
  File "bash\balt.py", line 1573, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\installer_links.py", line 573, in Execute
    ui_refresh, progress, last, override)
  File "bash\bosh\__init__.py", line 6553, in bain_install
    override)
  File "bash\bosh\__init__.py", line 6528, in _install
    SubProgress(progress, index, index + 1))
  File "bash\bosh\__init__.py", line 5748, in install
    env.shellMove(stageDataDir, destDir, progress.getParent())
  File "bash\env.py", line 482, in shellMove
    renameOnCollision=autoRename, silent=silent)
  File "bash\env.py", line 434, in _fileOperation
    raise FileOperationErrorMap.get(result, FileOperationError(result))
bash.env.FileOperationError: FileOperationError: 124

Next time I see this I'd like to see the paths too, thanks. Untested.

Rest is small stuff, the kind is produced all the time in my branch,
the not quite final kind.
Mopy/bash/brec.py:
if _debug: print Type,size, but anyway type renaming is WIP
The comments in Mopy/bash/patcher/base.py were intentionally dirty - or
a merge artifact. Still they feel dirty to me - ##: "performing" ? how ?

 # This is the 2nd commit message:

Remove unused Installer.clearTemp()

	# This is the 2nd commit message:

Type comments - took the opportunity to make gmaeInis to a tuple as is
read only.

		# This is the 2nd commit message:

patcher -> renaming patchName to patch_name to single out nasty and ugly
patchName class attributes