Centralize COED sort handling
Use a sort_special to fix COED sorting

COED is optional, but influences sorting for leveled lists and records
that contain items (e.g. CONT records). That means we get TypeErrors if
we try sorting when we have multiple entries/items, some with COED and
some without COED:

TypeError: '<' not supported between instances of 'Rounder' and 'NoneType'

NONE_FID probably makes more sense, we already use that for PERKs too.

Utumno: this is necessary due to *next* commit switching MelStruct
defaults to None - merging here so it stands out (note also ##:)