FO4: Fix renaming save masters
Broke in 015a699146f7306c3637954bbe99eea32bbb6c33:

Traceback (most recent call last):
  File "bash\gui\events.pyo", line 177, in _post
  File "bash\balt.pyo", line 825, in _conversation_wrapper
  File "bash\basher\__init__.pyo", line 2318, in DoSave
  File "bash\bosh\__init__.pyo", line 1343, in write_masters
TypeError: 'NoneType' object is not iterable