Upgrade to pyinstaller 6.7.0
Should fix the following:

Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 158, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources\__init__.py", line 77, in <module>
ModuleNotFoundError: No module named 'pkg_resources.extern'

See https://github.com/pyinstaller/pyinstaller/issues/8554

FO4: Add high res DLC to bethDataFiles

FNV: Update CTDA data for JIP LN v57.30

Checked against GECK.