WizardDialog:
Wizard size was not persisted on dev also - took a while to get this one
but took a lot of ugly code along - not final but sizes API starts to
pay. I catch wx.EVT_SHOW - re-added first_shown otherwise this callback
is fired more often - but maybe somehow use window.Create?
Note I dropped self.SetPageSize((600,500)), although I kept enforcing
this min size on opening a wizard. Not sure what best practices are -
for one a common min size seems to exist as currently a wizard can't be
resized arbitrarily small. I would like to see how this is set and
enforce that on restore maybe.

Mopy/bash/belt.py:
Mopy/bash/basher/installer_links.py:
dropped the machinery for setting the size/pos - this should be taken
care of in _TopLevelWin._set_pos_size - testing needed and settings
might tinily break for existing users. Rest was some backwards
compatibility that should go now - note the coupling of gui and
InstallInfo on WizardReturn -> WizInstallInfo (sic) is gone at last.
Event handling API starts to pay, as is the component_size/pos
properties :)

De-wxing:

Mopy/bash/belt.py: self.bmp was unused, moved wx.MAXIMIZE_BOX to parent
Dropped usedOnceMethods

Tracebacks:

keywords must be strings !!! Check on wx4!~

Traceback (most recent call last):
  File "bash\balt.py", line 2461, in __Execute
    self.Execute()
  File "bash\balt.py", line 1566, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\installer_links.py", line 209, in Execute
    self.bAuto, subs)
  File "bash\belt.py", line 88, in __init__
    style=wx.MAXIMIZE_BOX)
  File "bash\gui\top_level_windows.py", line 176, in __init__
    super(WizardDialog, self).__init__(parent, **kwargs)
  File "bash\gui\top_level_windows.py", line 130, in __init__
    sizes_dict, icon_bundle, title=self.title, style=style, **kwargs)
  File "bash\gui\top_level_windows.py", line 55, in __init__
    **kwargs)
  File "bash\gui\base_components.py", line 84, in __init__
    **kwargs)
  File "C:\_\Python27\lib\site-packages\wx\wizard.py", line 360, in __init__
    _wizard.Wizard_swiginit(self,_wizard.new_Wizard(*args, **kwargs))
TypeError: keywords must be strings

@@ -60,5 +60,5 @@ def __init__(self, wx_window_type, parent, sizes_dict, icon_bundle, *args,
     def _set_pos_size(self, kwargs, sizes_dict):
-        kwargs[u'pos'] = kwargs.get(u'pos', None) or sizes_dict.get(
+        kwargs['pos'] = kwargs.get('pos', None) or sizes_dict.get(
             self.posKey, self._defPos)
-        kwargs[u'size'] = kwargs.get(u'size', None) or sizes_dict.get(
+        kwargs['size'] = kwargs.get('size', None) or sizes_dict.get(
             self.sizesKey, self._def_size)
@@ -185,6 +185,6 @@ def _set_pos_size(self, kwargs, sizes_dict):
         #default keys for wizard should exist and return settingDefaults values
-        kwargs[u'pos'] = kwargs.get(u'pos', None) or sizes_dict[self.posKey]
-        saved_size = kwargs.get(u'size', None) or sizes_dict[self.sizesKey]
+        kwargs['pos'] = kwargs.get('pos', None) or sizes_dict[self.posKey]
+        saved_size = kwargs.get('size', None) or sizes_dict[self.sizesKey]
         # enforce min size
-        kwargs[u'size'] = (max(saved_size[0], self._def_size[0]),
+        kwargs['size'] = (max(saved_size[0], self._def_size[0]),
                            max(saved_size[1], self._def_size[1]))

Size pos broken XXX

Traceback (most recent call last):
  File "bash\balt.py", line 2461, in __Execute
    self.Execute()
  File "bash\balt.py", line 1566, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\installer_links.py", line 209, in Execute
    self.bAuto, subs)
  File "bash\belt.py", line 88, in __init__
    style=wx.MAXIMIZE_BOX)
  File "bash\gui\top_level_windows.py", line 176, in __init__
    super(WizardDialog, self).__init__(parent, **kwargs)
  File "bash\gui\top_level_windows.py", line 130, in __init__
    sizes_dict, icon_bundle, title=self.title, style=style, **kwargs)
  File "bash\gui\top_level_windows.py", line 55, in __init__
    **kwargs)
  File "bash\gui\base_components.py", line 84, in __init__
    **kwargs)
  File "C:\_\Python27\lib\site-packages\wx\wizard.py", line 360, in __init__
    _wizard.Wizard_swiginit(self,_wizard.new_Wizard(*args, **kwargs))
TypeError: 'size' is an invalid keyword argument for this function

@@ -186,5 +186 @@ def _set_pos_size(self, kwargs, sizes_dict):
         kwargs['pos'] = kwargs.get('pos', None) or sizes_dict[self.posKey]
-        saved_size = kwargs.get('size', None) or sizes_dict[self.sizesKey]
-        # enforce min size
-        kwargs['size'] = (max(saved_size[0], self._def_size[0]),
-                           max(saved_size[1], self._def_size[1]))

Random traceback (not repeated - broken in intermediate steps?)

Traceback (most recent call last):
  File "bash\gui\events.py", line 167, in _post
	result = listener(*listener_args)
  File "bash\gui\top_level_windows.py", line 85, in on_closing
	if self.posKey: self.sizes_dict[self.posKey] = self.component_position
  File "bash\gui\base_components.py", line 196, in component_position
	return curr_pos.x, curr_pos.y
AttributeError: 'PySwigObject' object has no attribute 'x'

Infernio:

Encapsulate wizard size/pos logic fully

Otherwise we have to copy-paste this for fomods as well