Fix for dates before the epoch on windows:
Recent GoG Oblivion update changed oblivion dates to before epoch:
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 117, in <module>
    bash.main(opts, FakeUnicodeImporter)
  File "bash\bash.py", line 427, in main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4005, in Init
    frame = BashFrame() # Link.Frame global set here
  File "bash\basher\__init__.py", line 3647, in __init__
    self.notebook = BashNotebook(self)
  File "bash\basher\__init__.py", line 3420, in __init__
    item = panel(self)
  File "bash\basher\__init__.py", line 1743, in __init__
    super(ModPanel, self).__init__(parent)
  File "bash\basher\__init__.py", line 253, in __init__
    super(BashTab, self).__init__(parent, isVertical)
  File "bash\basher\__init__.py", line 213, in __init__
    keyPrefix=self.keyPrefix, panel=self)
  File "bash\balt.py", line 1702, in __init__
    self.PopulateItems()
  File "bash\balt.py", line 1815, in PopulateItems
    for item in items: self.PopulateItem(item=item)
  File "bash\balt.py", line 1760, in PopulateItem
    labelTxt = self.labels[col](self, item)
  File "bash\basher\__init__.py", line 770, in <lambda>
    ('Modified',   lambda self, p: formatDate(self.data_store[p].mtime)),
  File "bash\bolt.py", line 168, in formatDate
    return decode(time.strftime('%c', time.localtime(value)),
ValueError: (22, 'Invalid argument')

See: https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=167215

Monkey patched as locale is, was and will be a pain