Regressions:
Lumped together cause policy is that they must be fixed as soon as
found, for a less broken dev.

Strange mysterious bug with default dict:

For reasons that I can't really put my finger on _sometimes_ iniedits
ended up with a 'default_fatory' key mapping to an empty dict - the
'default_fatory' is a defaultdict attribute containing, well, the
default_fatory for this defaultdict. That's black magic but better safe
than sorry so I partially reverted commit
fca2ed950ad04d59d813701c2f79d4897fc8a15e.
Note that this was probably added in generateTweakLines as I got at some
point:
Traceback (most recent call last):
  File "bash\balt.py", line 2445, in __Execute
    self.Execute()
  File "bash\balt.py", line 1566, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\installer_links.py", line 266, in Execute
    self._apply_tweaks(installer, ret, ui_refresh)
  File "bash\basher\installer_links.py", line 275, in _apply_tweaks
    for iniFile, section_settings in ret.IniEdits.iteritems():
RuntimeError: dictionary changed size during iteration
or not... Initial error was missing iniFile missing sbody attribute
(cause not a Path, just u'default_fatory').
Mopy/bash/basher/installer_links.py: pythonization.

Mopy/bash/balt.py:
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 438, in main
  File "bash\basher\__init__.py", line 3993, in Init
  File "bash\basher\__init__.py", line 3635, in __init__
  File "bash\basher\__init__.py", line 3417, in __init__
  File "bash\basher\__init__.py", line 1739, in __init__
  File "bash\basher\__init__.py", line 271, in __init__
  File "bash\basher\__init__.py", line 233, in __init__
  File "bash\balt.py", line 1663, in __init__
  File "bash\balt.py", line 1776, in PopulateItems
  File "bash\balt.py", line 1726, in PopulateItem
  File "bash\balt.py", line 1759, in __setUI
  File "bash\balt.py", line 69, in Style
  File "C:\Games\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_gdi.py", line 2273, in SetUnderlined
    return _gdi_.Font_SetUnderlined(*args, **kwargs)
TypeError: Required argument 'underlined' (pos 2) not found

reported by Malonn:
http://forums.bethsoft.com/topic/1612572-wrye-bash-thread-112/#entry25270490
Introduced in d1a5350310e2e955b8063bf6cfe9d7cb9c605fe8

Mopy/bash/game/oblivion/constants.py:
Fixup in sound patcher - introduced in
afe393bedca0c865d2b78cd00fc5cb47cead3883. reported by @iaz3:
http://forums.bethsoft.com/topic/1612572-wrye-bash-thread-112/#entry25269454