Rip defaultEyes out of bush and falloutnv/records
...and move them into the matching constants files instead, since they
really don't belong in those places.

In order to not introduce a bolt dependency in these files, I had to add
some logic to the patchers to make them convert the strings to Path
objects on the fly. Hopefully nothing broke.

Also PEP8'd defaultEyes and standardEyes while I was at it.

Note: I renamed x -> _x, hiding them from the dynamic importer to
avoid a traceback:

Traceback (most recent call last):
  File "bash\bash.py", line 187, in main
    _main(opts)
  File "bash\bash.py", line 266, in _main
    bashIni, bush_game, game_ini_path = _detect_game(opts, bash_ini_path)
  File "bash\bash.py", line 390, in _detect_game
    bush_game = _import_bush_and_set_game(opts, bashIni)
  File "bash\bash.py", line 423, in _import_bush_and_set_game
    bush.detect_and_set_game(opts.oblivionPath, bashIni, retCode)
  File "bash\bush.py", line 186, in detect_and_set_game
    __setGame(name, u' Using %(gamename)s game:')
  File "bash\bush.py", line 177, in __setGame
    game.init()
  File "bash\game\oblivion\__init__.py", line 235, in init
    cls._dynamic_import_constants(__name__)
  File "bash\game\__init__.py", line 441, in _dynamic_import_constants
    raise RuntimeError(u'Unexpected game constant %s' % k)
RuntimeError: Unexpected game constant x