ut-336-drop-table at 1fc3f861156d009f24a9967823b19c5d418bc559:
WIP reduce table.getColumn uses: EEE ##: TTT in mod_links

I wanted to do this for a while but seemed performance would be affected
(in theory, in practice it really won't matter). On closer inspection
DataColumn.get does exactly what get_table_prop does modulo a couple dots.
Dialogs and balt really does not matter - where one might think it makes
a diff is when iterating the column - as in the (ad hoc) operations in
mod_links.py - but then DataColummn.__iter__ would iterate over modInfos
essentially, as the table contains all keys for modInfos (crc cache
info). So I stopped counting dots and flattened this nested mess.
Resulting code reads more naturally and performance differences should
not really matter, anyway this is a step towards removing table, whose
occurrences went down in favor of direct modInfo accesses.

- readFromModInfos/writeToModInfos single uses passed self.selected in -
I doubt this would be empty TTT
- bonus: prune getItem calls

TTT

@@ -2091,3 +2090,3 @@ def _modinfos_cache_wrapper(self: ModInfos, *args, **kwargs) -> LordDiff:
                 ghostify.update({k: True for k in new_inactive if
-                                 allowGhosting.get(k, True)})
+                    self[k].get_table_prop('allowGhosting', True)})
             ldiff.affected.update(mod for mod, modGhost in ghostify.items()

Note in basher/dialogs.py we would set the group to an empty string -
we should prune those if they exist in settings.

Refactor setOblivionVersion: RRR

This is one of the most arcane pieces of the FileInfos machinery.
Specification lost in Oblivion, file operations (# RRR 241 ) - reported
heisenbug stuff. Note size_esm_version[oldSize] was outside of the
KeyError try/except - some of this could be converted to EAFP?
Some of it moved to bush.game? What exactly needs be refreshed? Should
we disallow activating the modding esms or does not make sense/it's too
complex (_game_lo is actively refactored currently)? Black magic, I
reduced the repetition in the logic - this made me notice a bug in
error in 907bdccaea6e1474a433813a70cdbcddad28ae76 (i did not change the
parameters to infos in the error handler). I absorbed the helper so
this is as few lines as possible. As seen from questions above
setOblivionVersion badly needs a spec but still works (well see next
commit) - and hopefully now it's clearer what it does.
Mopy/bash/basher/mods_links.py: disable the menu if it won't do anything

Fix in Oblivion esm swap: TTT locking copy_from RRR

So Oblivion.esm active, Oblivion_1.1.esm inactive and ghosted - on
calling file_info_rename_op(*args_dict) to rename Oblivion_1.1.esm
to Oblivion.esm the ModInfo.get_rename_paths will add .ghost - the
_active_wip cache would be updated correctly but then cached_lo_save_all
would set ghostify = dict.fromkeys(ldiff.act_new, False) - now
Oblivion.esm was already active before, so not in act_new, so it would
never be unghosted. The UI would not reflect that, but on next restart
Bash would crash on boot with:

Traceback (most recent call last):
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bash.py", line 531, in main
    _main(opts, wx_locale, wxver)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bash.py", line 696, in _main
    frame = bapp.Init() # Link.Frame is set here !
            ^^^^^^^^^^^
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\__init__.py", line 4277, in Init
    self.InitData(progress)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\__init__.py", line 4304, in InitData
    bosh.modInfos = bosh.ModInfos()
                    ^^^^^^^^^^^^^^^
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bosh\__init__.py", line 2127, in __init__
    raise FileError(bush.game.master_file,
bash.exception.FileError: Oblivion.esm: File is required, but could not be found

which also means that having the master esm ghosted needs handling (we
should not crash just unghost). To address this correctly we would need
rename refactoring done so wait for next merge - meanwhile I added code
for this particular case. Note that notify_bain would never be fed
the altered path - will have to wait for # <--- RRR 353. The solution
is adding some of the rename_operation machinery to the info.

Drop allow_deactivate_master:

Probably a relic from early Nehrim support. However, game_lo API aims to
mimic what the game itself will load (and in which order) so it is
easier to think in terms of the master esm being active at all times.
In particular esm swap would be much easier to reason about which partly
prompted this commit, after the buggy fact (see parent).
Maybe must_be_active_if_present should be never empty now. We need to
revisit places where we check if it's empty - *after* _games_lo upcoming
refactoring.

SSS simplify rename args

Remove _files_to_delete:

Since we already override both _delete_operation and delete_refresh in
Installers. filter_essential is right where it should be, once. Yey, and
to celebrate I sprinkled a finally in there - I use it to mark areas of
the APIs that are final but I am not really a fan.

I had to add an fn_key attr to Corrupted otherwise:

  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bosh/__init__.py", line 1651, in _diff_dir
    if inf.fn_key not in inodes}
       ^^^^^^^^^^
AttributeError: 'Corrupted' object has no attribute 'fn_key'

Corrupted is still new - it may inherit aunt ListInfo once the dust
settles.

XXX sanity checks(?) TTT and todos

saved.lo_diff(fixed)rdata.to_add

ldiff.added may differ from rdata.to_add, for instance when booting
rdata.to_add is all the plugins in the data dir, but ldiff.added may
be a new plugin whose mtime would not put it at the end of the load
order, where it is put when fixing the saved load order - so
ldiff_saved will be returned which will only contain the new plugin
similarly, ldiff.missing may differ from rdata.to_del

Use an AFile for loadorder/plugins txts: TTT

This is a mini branch actually - contains also some refactoring of
get_*file, which were moved to base and _backup_*** overrides were absorbed
(for the IniGame based on the observation that the _handle_*** test is
performed in the get_*file). It is WIP in the sense that those mirror
methods should be atomic but more on that latter. We could also probably
set the ini files to the AFile attributes hmmm. Note error handling is
unified in __backup.

Needs testing especially: TTT

- _plugins_txt_modified now returns True for deleted plugins.txt
- same for load_order_changed for deleted load_order_txt
- swap uses FNF untested
- ...

Fixup for parsing comments: TTT

Introduced probably in cb9de8be5983da1ff15fbfa2eb01e6584ee1f5d1 (didn't
check). _get_ci_settings would parse the whole line comments like
settings. I introduced _re_whole_line_com so I do not mess with reComment
logic still needs a second pair of eyes TTT (also wouldn't isn't
\s* == [^\S\r\n]*  ?)

FFF TTT not sure about inline comments here

see cb9de8be5983da1ff15fbfa2eb01e6584ee1f5d1

SSS Bump dependencies

A couple major bumps, but they shouldn't affect us.

One set_store_dir to rule them all: EEE fix profiles XXX

This takes with it all the SaveInfos cruft. I also made ScreenInfos
init static. Typing is left for after the dust settles.

Does refresh need be after the swap??

@@ -195,7 +197,7 @@ def Execute(self):
             with BusyCursor():
-                self.window.set_local_save(newSaves, refreshSaveInfos=False)
-                bosh.modInfos.swapPluginsAndMasterVersion(arcSaves, newSaves, askYes)
-                bosh.saveInfos.refresh()
+                old = bosh.saveInfos.store_dir
+                self.window.set_local_save(new_dir)
+                bosh.modInfos.swapPluginsAndMasterVersion(old, new_dir, askYes)
                 self.window.DeleteAll() # let call below repopulate

WIP rip off swapPluginsAndMasterVersion: SSS TTT

Note swapPluginsAndMasterVersion would be called *after* set_local_save
which sets the Bash title - so if the esms were swapped the title would
not reflect that.

I ended up introducing try_set_version to decouple save and modInfos -
not sure if voAvailable may contain voCurrent but let's not pursue this
further.

Bye getColumn:

The tough part was DocBrowser - is the BP doc displayed for a new BP?

SSSSS getColumn FFF EEE ##:TTT EEE bosh.modInfos.refresh() ##: needed?

Mopy/bash/basher/mod_links.py:
could labels be empty? I guess no but I also now check it in the
`and (p := v.get_table_prop(self.column)` if condition. Then I drop the
any from `not any(column_contents)` TTT

Drop table TTT

There were some sure signs that this should happen:

- operations overrides (more work on renames soon)
- the hackiest use of get_store(), which is itself a hack (the
infos should not need to know their parent - used for backup/hide and
notifying BAIN - so yeah).

DataTable(PickleDict) SSS table

A DataDict override down - especially welcome nuking hasChanged

Call refresh on data stores init: RRR

This is in prep of disabling the costly SaveInfos refresh

TTT hacky fix for needing the modInfos singleton during modInfos refresh SSS FFF

This should need a completely different treatment - done later (this is
what sprang the string bsa refactoring)

Drop BashApp RRR

I thought let's inline those two static methods as they're not as huge
as in the old days. Turns out 'Start application' was not accurate -
BashApp did nothing much anymore - the thin class so to speak. The boot
code is nowhere near to where it was 10 years ago, looks almost boring
now, used to be a perilous mess of wx and weird unpredictable stuff
with queer names like bosh. Hundreds of tracebacks. I can't say I luv
the splash thing but I won't remove it cause it is a screen. So I made
it more fail safe and less ugly, it's almost cute now that I don't need
to assign it. But what I like most is further untangling the main
modules responsibilities - remember initBosh? :P

Under # <--- RRR 600

Drop  the double sort (is that what we want? TTT)

ABsa.str_bsas_sorted TTT EEE _str_heuristics per game (SSE)

Drop _find_string_bsas in favour of a cache - should make loading files
faster (note removed performance comment)

TTT get_bsa_lo -> single occurrence:

The previous situation looks like a bug: in the get_bsa_lo([self.fn_key])
call we would be adding to bsa_lo for each localized plugin the index:

bsa_lo[binf] = i (i would alwayss be zero here)

This meant that we would search for strings in some other plugins bsas.
I changed it so it copies self.__bsa_lo which at this point is just the
bsas that are loaded by inis - is this correct? TTT Also:

- why we use reverse - see next commit
- should we del available_bsas[binf.fn_key] in place or pass a copy - aka
is allowed to load strings from the same bsa from two files? (no I guess)

in short we'd need a couple more comments

TTT SSS fix sorting: XXX correct?

This should matter in unpacking and actually we should probably give
priority when loading to the ini ones (for ModInfo.getStringsPaths)?

SSS move handling of bsas in bush.game.Bsa:

One nice side effect is removing a particularly nasty bush.game.fsName
use

Refactor _get_bsas_from_inis TTT

FFF drop OD

Move handling of bsa lo in GameInfo.Ini/Bsa:

This will permit us to finally address Morrowind bsa lo