Slight bsas apis refactoring:
Mopy/bash/bosh/bsa_files.py:
assets -> folder_assets, ofc - assets is another attribute
Note in BA2s I used to pass just the filename as the asset's "filename"
attribute. Maybe I should drop the filename attribute (used in repr) -
or BSAAsset altogether ?
I needed to update tests:
https://github.com/wrye-bash/test_bash/commit/8ea73300c5d2d8cf45d9b24fbd42bf97f89c9a7f
Mopy/bash/bosh/__init__.py:
Renames - never name a local var as the method.

And a fixup:

@@ -400,3 +400,3 @@ def assets(self):
-            self.load_bsa_light()
+            self.__load(names_only=True)

We must wrap struct error in a BSAError cause otherwise it may prevent
Bash to boot - see:
http://forums.bethsoft.com/topic/1614408-wrye-bash-thread-113/?p=25306824

Traceback (most recent call last):
File "Wrye Bash Launcher.pyw", line 88, in <module>
File "bash\bash.pyo", line 439, in main
File "bash\basher\__init__.pyo", line 4032, in Init
File "bash\basher\__init__.pyo", line 4074, in InitData
File "bash\bosh\__init__.pyo", line 2990, in refresh
File "bash\bosh\__init__.pyo", line 2797, in _modinfos_cache_wrapper
File "bash\bosh\__init__.pyo", line 3051, in _refreshMissingStrings
File "bash\bosh\__init__.pyo", line 3052, in <genexpr>
File "bash\bosh\__init__.pyo", line 3470, in isMissingStrings
File "bash\bosh\bsa_files.pyo", line 393, in has_asset
File "bash\bosh\bsa_files.pyo", line 402, in assets
File "bash\bosh\bsa_files.pyo", line 447, in load_bsa_light
File "bash\bosh\bsa_files.pyo", line 473, in _read_bsa_file
struct.error: bad char in struct format