Fixup for de/activation:
From @sibir-ine:

I found another regression in 4ce6d79. Deactivating the dependency of an
active plugin or activating the dependent of a deactivated plugin throws
this traceback:

 File "*****\bash\basher\dialogs.py", line 916, in make_highlight_entry
    parent_tab_key=data_key.value[0])
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

Nit - hunt down modInfos:

parsers: removed _mod_has_tag unused since
a5ca81cbd2c52f689d9aafbda5b7640c8a68741f. More local imports pruned -
modInfos is now used directly in few files - namely bosh and basher but
also save_headers, bain.py and fomod.py - those should be revisited.