Fix for recursive BCFs:
Somehow a Path was passed in when there are archives inside the package
to be converted - create an archive with archives inside, create a BCF
for a BAIN'ed archive which has those files unpacked, delete the BAIN'ed
archive due to #223, apply the BCF and get:

Traceback (most recent call last):
  File "bash\balt.py", line 1777, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\installer_links.py", line 1204, in Execute
    SubProgress(progress, 0.0, 0.99))
  File "bash\bosh.py", line 6871, in apply
    self.arrangeFiles(SubProgress(progress,lastStep,0.7))
  File "bash\bosh.py", line 6907, in arrangeFiles
    srcFile = tempJoin(u"%08X" % srcDir,srcFile)
TypeError: %X format: a number is required, not Path

Took the opportunity to rename _arrangeFiles - not part of the API