bosh - FIX for created balo_group.esp ModInfo.header being None:
Edit balo groups dialog:
Traceback (most recent call last):
  File "bash\basher\__init__.py", line 12092, in DoSave
    bosh.modInfos.refresh()
  File "bash\bosh.py", line 4340, in refresh
    self.refreshInfoLists()
  File "bash\bosh.py", line 4503, in refreshInfoLists
    if modInfo.header.author == u"BASHED PATCH":
AttributeError: 'NoneType' object has no attribute 'author'

This:
+                    newInfo.getHeader() # set newInfo.header from the file

Took the opportunity to actually make getHeader return the header
Notice in refresh if header == None it won't load it from disc

Deleted unneeded ins.close() (code uses with)