Drop naming for extra_recs and @_process_rec fixups:
Simplify by getting rid of the internal naming of the attributes - I
kept separate to have the previous mechanism in case one needs to
implement something similar but keep in mind this was subtly buggy -
for one the del _extra_records[b'CELL'] would modify the class variable
leading to chaos. Anyway the internal attribute names were not needed,
and the design does not scale for new games - so use the record
signatures and expose the _stray_rec values the clients need as
properties(use sparingly). ImportCells patcher is still broken due to a
wrong getActiveRecords use - rest of patch builds (but needs more fixups
in this branch).

Another DUMMY_FID

I am so glad I introduced those

patcher_dialog.py  272 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 184, in PatchExecute
  File "bash\basher\patcher_dialog.py", line 281, in _save_pbash
  File "bash\mod_files.py", line 257, in safeSave
  File "bash\mod_files.py", line 291, in save
  File "bash\brec\record_groups.py", line 278, in dump
  File "bash\brec\record_groups.py", line 529, in dump
  File "bash\brec\record_groups.py", line 945, in dump
  File "bash\brec\record_groups.py", line 527, in dump
  File "bash\brec\record_groups.py", line 529, in dump
  File "bash\brec\record_groups.py", line 944, in dump
  File "bash\brec\record_groups.py", line 235, in _write_header
  File "bash\brec\mod_io.py", line 152, in pack_head
  File "bash\brec\mod_io.py", line 201, in _pack_args
  File "bash\brec\utils_constants.py", line 290, in dump
bash.exception.AbstractError: Dumping a dummy fid

This *would* dump a dummy fid but what is the logic of merge_records
exactly? Should it not copy over if the cell is None anyways?

@@ -1235,3 +1235,3 @@ def merge_records(self, src_block, loadSet, mergeIds, iiSkipMerge, doFilter):
                 self._stray_recs[b'CELL'] = _PersistentCell(self._load_f, None,
-                                                            cell=None)
+                                                            cell=src_cell)
             # Delegate merging to the (potentially newly added) block