Monkey patch type error in PERK:
https://discord.com/channels/537706885965676554/537710082755133460/978605385093120010

record_structs.py  196 dumpData: Error dumping data:
Traceback (most recent call last):
  File "bash\brec\record_structs.py", line 194, in dumpData
  File "bash\brec\advanced_elements.py", line 1056, in dumpData
TypeError: '<' not supported between instances of 'NoneType' and 'int'

record_structs.py  197 dumpData: Occurred while dumping <SmallFrame [PERK:00135EC6]>
record_structs.py  207 dumpData: > conditions: [<compValue: b'\x00\x00 A', ifunc: 495 (GetPermanentActorValue), operFlag: 0x00000080 (), param1: 10, param2: b'\x00\x00\x00\x00', reference: 0, runOn: 0, unused1: b'\x00\x00\x00', unused2: b'\x00\x00'>]
record_structs.py  207 dumpData: > hidden: 0
record_structs.py  207 dumpData: > iconPath: 'interface\\icons\\pipboyimages\\perks\\perk_small_frame.dds'
record_structs.py  207 dumpData: > ranks: 1
record_structs.py  207 dumpData: > full: 'Small Frame'
record_structs.py  207 dumpData: > eid: 'SmallFrame'
record_structs.py  207 dumpData: > minLevel: 1
record_structs.py  207 dumpData: > _loader_state: [b'PRKE']
record_structs.py  207 dumpData: > effects: [<ability: 1269442, effectConditions: [], effectParams: [], entry_point: 0, footer: b'', function: 0, perk_conditions_tab_count: 0, priority: 0, quest: 0, quest_stage: 0, rank: 0, type: 1, unused_data: b'\x00\x00\x00'>, <ability: None, effectConditions: [], effectParams: [], entry_point: 0, footer: b'', function: 0, perk_conditions_tab_count: 0, priority: 0, quest: 0, quest_stage: 0, rank: 0, type: 1, unused_data: b'\x00\x00\x00'>, <ability: None, effectConditions: [], effectParams: [<buttonLabel: None, compiled_script: None, compiled_size: 0, function_parameter_type: 1, last_index: 0, num_refs: 0, param1: Rounder(1.25), param2: Rounder(0.0), references: [], schr_flags: 0x00000000 (None), script_flags: 0x00000000 (None), script_source: None, script_type: 0, script_vars: [], unused1: b'\x00\x00\x00\x00'>], entry_point: 6, footer: b'', function: 3, perk_conditions_tab_count: 3, priority: 0, quest: 0, quest_stage: 0, rank: 0, type: 2, unused_data: b'\x00\x00\x00'>]
record_structs.py  207 dumpData: > playable: 1
record_structs.py  207 dumpData: > description: 'Due to my small size, I have a +1 to my Agility but my limbs are more easily crippled. Easy fix? I just have to not get hit. '
record_structs.py  207 dumpData: > trait: 1
patcher_dialog.py  265 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 183, in PatchExecute
  File "bash\basher\patcher_dialog.py", line 274, in _save_pbash
  File "bash\mod_files.py", line 287, in safeSave
  File "bash\mod_files.py", line 320, in save
  File "bash\brec\record_groups.py", line 260, in dump
  File "bash\brec\record_groups.py", line 249, in getSize
  File "bash\brec\record_groups.py", line 250, in <genexpr>
  File "bash\brec\record_structs.py", line 474, in getSize
  File "bash\brec\record_structs.py", line 609, in dumpData
  File "bash\brec\record_structs.py", line 194, in dumpData
  File "bash\brec\advanced_elements.py", line 1056, in dumpData
TypeError: '<' not supported between instances of 'NoneType' and 'int'

Turns out there was a PERK with type=1 (ability) and no DATA ->
ability=None -> compare with other int formIDs -> boom. I ordered this
last (as it seems to be in FalloutNV.esm)

Some nit in PERK - note how similar those are.