Fixup for converting screens to jpg and load order nit:
AttributeError: 'ImgFromPath' object has no attribute 'save_bmp'
Broke in b3e46b4a3d96e2bff5e003bd81540604c18920fd

More load order nit:

get_load_order (single) use passes a fix_lo instance in - we need to
untangle quiet from fix_lo as turns out the latter contains super
detailed info on active and lord changes :)

Wip typing

Mopy/bash/bosh/bain.py: more nit

Drop _activeModsFirst override:

With a hack - I need to reduce load_order/modInfos.* accesses. Will be
put to good use to reduce duplication in set_item_format soon.