Fix[bosh]: code paths in InitSettings:
See #178.

Ex.: If backup settings exists and is corrupted and usebck == False
dictFile.load() will try to load the backup again - fixed:
introduced 'ignoreBackup' param
Introduced delBackup whereupon I delete the backup when I know it's
"corrupted"

Exceptions raised from the error message:
u'%s' % "cPickle.UnpicklingError: invalid load key, 'ÿ'."
Traceback (most recent call last):
  File "<input>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 44: ordinal not in range(128)

So yeah - use repr: http://stackoverflow.com/q/27652804/281545

Maybe other occurrences of this pattern in the code...

Needs work