Nit in _dropIndexes and fixups galore:
I was wondering how come `if newIndex < 0` and not `<= 0` - turns out
this is handled in dropItems. Back-ported from _lo_op merge.

Fixups:

All the testing 313 never got - that was a tough adventure as we were
few and wide apart and had to deal with #689 which blurred the water for
a while while we hadn't figured out it's not a bug in Bash.

Base do_update passes load_cache=True to Installers:

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 3738, in OnShowPage
  File "bash\balt.py", line 515, in _conversation_wrapper
  File "bash\basher\__init__.py", line 3255, in ShowPanel
  File "bash\bosh\bain.py", line 2240, in update_installers
  File "bash\bosh\bain.py", line 1694, in do_update
  File "bash\bolt.py", line 1709, in do_update
  File "bash\bosh\bain.py", line 1204, in _reset_cache
TypeError: InstallerProject._fs_refresh() got an unexpected keyword argument 'load_cache'

Compliments of 32bf6069a6a399b6b3d96e3fab13667f87a23f31

Mopy/bash/bosh/__init__.py:

- fixup from ae387865a5f62a969c63ef5a1f281da7d419e054
- slight fixup in _file_or_active_updates - old_dexs contains the
inactive ones that are added dynamically with an index = sys.maxsize.
These need not be updated
- only call del_refresh if needed - calls load order methods and
complicates debugging.

Mopy/bash/basher/installers_links.py: stray import from
a4d95c93986ac0408c1c15b508d76bdeccf8a6d1

basher/*links.py: use self._data_store

We need to encapsulate bosh singletons to better define UI/bosh
interfaces - this will be the final responsibility of Store.

plugin_types.py: fixup for not flagging .esl extension plugins as esm

Mopy/bash/bosh/save_headers.py:
Fixup from 53e308ddbcbe2519420635bf019d9e02e1be5389 - turns out we pass
ins in in _saves.SaveFile.load.

Mopy/bash/game/__init__.py: hasty caching of the bsas we already warned
for (see 37017da603ae4889df6db9f7298386a4d43dc181). Could use an AFile
here instead of reading the inis again and again?

Mopy/bash/bosh/save_headers.py: nit - encapsulate, ins is a bad name
for a param

No bugfixing round would be complete without some rename fixups:

Mopy/bash/basher/installer_links.py: Fixup in Installer_Duplicate

basher: fixup in IList try_rename, the return value should be a RefrData
- try renaming [A (1).7z, A.7z] -> boom - now [A (2).7z, A.7z] (yep).
Nit in details panel code - from a time SetFile was an issue - un-nest
and cleanup

bolt: Fixup for ghosts in mod details rename - the two uses of
validate_name are for infos present in the store folder - see comment
in Mopy/bash/basher/files_links.py. Note on tabbing out of Bash the
OnFileEdited will be triggered (so will revert the edit if fileStr in
modInfos) - then tabbing back in modInfos should be updated, so indeed
we don't need the exists() check.

bosh: Fixup in screens validate name - num_str might be None

Under #580

basher: Fixup for ordering by author

Probably from 36399fbfa50fb276b784e0960576e13abfbd37d3