WIP bolt.wrapPopenOut():
setter = object.__setattr__ was unused
Note that now it's more likely to have a StateError raised
Dropping stdin=subprocess.PIPE results in:
Traceback (most recent call last):
  File "bash\balt.py", line 1777, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\installer_links.py", line 1204, in Execute
    SubProgress(progress, 0.0, 0.99))
  File "bash\bosh.py", line 6839, in apply
    self.load(True)
  File "bash\bosh.py", line 6822, in load
    u"\nLoading %s:\nBCF extraction failed." % self.fullPath.s)
  File "bash\bolt.py", line 2006, in wrapPopenOut
    startupinfo=startupinfo)
  File "C:\_\Python27\lib\subprocess.py", line 760, in __init__
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "C:\_\Python27\lib\subprocess.py", line 833, in _get_handles
    p2cread = self._make_inheritable(p2cread)
  File "C:\_\Python27\lib\subprocess.py", line 884, in _make_inheritable
    _subprocess.DUPLICATE_SAME_ACCESS)
WindowsError: [Error 6] The handle is invalid