Fix for CoblCatalogsPatcher:
Mopy/bash/patcher/base.py:
Enabling only the Cobl patchers would result in:

patch_files.py  370 scanLoadMods: MERGE/SCAN ERROR: Cybiades.esm
patcher_dialog.py  279 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\patcher_dialog.py", line 171, in PatchExecute
    patchFile.scanLoadMods(SubProgress(progress,0.2,0.8)) #try to speed this up!
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\patcher\patch_files.py", line 355, in scanLoadMods
    self.update_patch_records_from_mod(modFile)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\patcher\patch_files.py", line 412, in update_patch_records_from_mod
    block.updateRecords(modFile.tops[top_sig], self.mergeIds)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'MobBase' object has no attribute 'updateRecords'

This was due to CoblCatalogsPatcher.active_write_sigs not including INGR
which was however loaded as an (empty!) MobBase in scanModFile. Fixed
there, but real fix is centralizing loading even more.
Rest is some fdust/nit split from "Centralize plugins loading" commit.