Fix for python files icons - docs/tests needed:
The icon would not be detected for py file shortcuts in the Apps folder.
Fixed but docs are badly needed. Fix was that the filedata var
could be an absolute path. The variables were:

filedata = {unicode} u'C:\\_\\Python27\\DLLs\\py.ico'
file_association = {str} 'Python.File'
idex = {unicode} u'0'
target = {Path} C:\...\some.py

So:

icon, idex = u'C:\\_\\Python27\\DLLs\\py.ico'.split(',')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: need more than 1 value to unpack

Cf the case of an image shortcut - the variable values were:

filedata = {unicode} u'C:\\__\\IrfanView\\i_view32.exe,0'
file_association = {str} 'IrfanView.jpg'
idex = {unicode} u'0'
target = {Path} C:\...\some.jpg

Rearranged the init_app_links code as if customIcons exist, no need to
run the rest of the code.
What the code does is use win32gui.ExtractIcon and let it raise to
detect presence of icon in the exe - we should be using ExtractIconEx.
Note the handle used to leak, plugged:

	win32gui.DestroyIcon(hIcon)

I added some tests to explore how ExtractIcon and ExtractIconEx work:
https://github.com/wrye-bash/test_bash/commit/a79e9f87c273216ce1c9479915d5c29b603b5e06
and ex.

For the meaning of `if target.lower().find(ur'installer\{') != -1` see
dc0c8de0c8e969673833565bb3636377ba7082b8 - make apps dir shortcuts work
with the funky msi generated shortcuts...