Notify BAIN when (un)ghosting
I first added this BAIN notification in
11230fd74959124a899650db22f68f73cc6751ab.
56d1b4f26ff9c710b8b026bcd98e826a39d63cff got rid of it again, but this
causes various tracebacks when an unghosted plugin is added to BAIN's
external tracker (cls._externally_updated) and then ghosted afterwards.
Example reproducer:

 1. On the Mods tab, enable Auto-Ghosting and press Ctrl+O to open the
    Data folder
 2. On the Installers tab, monitor an external installation and accept
    the initial popup with 'Yes'
 3. In the Data folder, make a copy of a plugin, e.g. Dragonborn.esm in
    Skyrim
 4. On the Installers tab, press 'OK' on the second Monitor External
    Installation popup
 5. We would now expect to get an external installation with 'Dragonborn
    - Copy.esm' included
 6. Instead, we get a traceback:

Traceback (most recent call last):
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/balt.py", line 1684, in __Execute
    self.Execute()
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/balt.py", line 515, in _conversation_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/basher/installers_links.py", line 108, in Execute
    self.iPanel.ShowPanel(canCancel=False, scan_data_dir=True)
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/balt.py", line 515, in _conversation_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/basher/__init__.py", line 3423, in ShowPanel
    do_refresh = self.listData.refreshTracked()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bosh/bain.py", line 2521, in refreshTracked
    s, m = apath.size_mtime()
           ^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bolt.py", line 1067, in size_mtime
    lstat = os.lstat(self._s)
            ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/infernio/Games/steam/steamapps/common/Skyrim Special Edition/Data/Dragonborn - Copy.esm'

(This was obviously on Linux, but I first noticed it in my Windows VM)

Perhaps the right solution is some more refactoring to improve ghost
handling, but this works for now and solves a bunch of random tracebacks
I got while doing my round of testing.