Regression: Fixup for saves' edits:
For instance clicking on any Save_EditCreated link (similar for
Save_EditPCSpells):

Traceback (most recent call last):
  File "bash\balt.py", line 2346, in __Execute
    self.Execute()
  File "bash\basher\saves_links.py", line 509, in Execute
    data = Save_EditCreatedData(self.window,saveFile,recordTypes)
  File "bash\basher\saves_links.py", line 393, in __init__
    record = record.getTypeCopy()
  File "bash\brec.py", line 1494, in getTypeCopy
    myCopy.load(unpack=True)
  File "bash\brec.py", line 1540, in load
    if ins.hasStrings: reader.setStringTable(ins.strings)
AttributeError: 'NoneType' object has no attribute 'hasStrings'

Introduced in 1b7f304cb8cd0a2f4bcb782db278becc911e3633
It did affect core functionality - hey, all in the day's work.

Signed-off-by: MrD <the.ubik@gmail.com>