Fixes for longid handling, add face and trying to parse OBME effects:
Mopy/bash/bosh/faces.py:
Traceback (most recent call last):
  File "bash\balt.py", line 1803, in __Execute
  File "bash\basher\mod_links.py", line 1666, in Execute
  File "bash\bosh\faces.py", line 446, in mod_addFace
AttributeError: 'NoneType' object has no attribute 'female'

Yep default is switched to None since forever now - let's address this
properly come #480

Av Latta Magicka.esm export spells failed with:

Traceback (most recent call last):
  File "bash\balt.py", line 1803, in __Execute
  File "bash\basher\mod_links.py", line 2087, in Execute
  File "bash\basher\mod_links.py", line 1718, in Execute
  File "bash\parsers.py", line 90, in write_text_file
  File "bash\parsers.py", line 164, in _write_rows
  File "bash\parsers.py", line 1237, in _row_out
  File "bash\parsers.py", line 1177, in _row_out
  File "bash\parsers.py", line 1178, in <genexpr>
  File "bash\game\oblivion\records.py", line 296, in <lambda>
  File "bash\game\oblivion\records.py", line 438, in _write_effects
AttributeError: 'MelObject' object has no attribute 'actorValue'

Guess what - it's OBME - skipping processing here too

Rest is long fids handling around the parsers code - last regressions
from #637 (seems no one used those)

Traceback (most recent call last):
  File "bash\balt.py", line 1793, in __Execute
  File "bash\basher\mod_links.py", line 1924, in Execute
  File "bash\parsers.py", line 990, in export_scripts
  File "bash\parsers.py", line 89, in write_text_file
  File "bash\parsers.py", line 1011, in _header_row
TypeError: '_FormID' object is not subscriptable