Fixup for Morph patcher:
It would never read the csv - the exception control flow should be
revisited.

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\patcher\base.py", line 143, in _parse_csv_sources
    parser_instance.read_csv(csv_path)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\parsers.py", line 181, in read_csv
    with open(csv_path, encoding='utf-8-sig') as ins:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\GAMES\\TESIV\\Oblivion\\Data\\Bash Patches\\Bash_MFact.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\parsers.py", line 193, in read_csv
    self._parse_line(fields)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\parsers.py", line 237, in _parse_line
    key1 = self._key1(csv_fields)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\parsers.py", line 248, in _key1
    top_grup_sig = self._parser_sigs[0] # one rec type
                   ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Nit:

Mopy/bash/parsers.py: I used the type annotation pattern from
_AComponent in hopes it will type a bit. Some refactoring to make
clearer the internals of _AParser - note that _write_record_2 seems
to honor additions and changes but on closer inspection also seems that
the FactionRelations due to its _read_record_sp would not carry on
additions when there is no changes also. See discussion in

https://github.com/wrye-bash/wrye-bash/issues/480#issuecomment-1475032197

Some more work in the 312-647 upcoming merge.