Fix in new_bp_part:
patcher_dialog.py  320 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash\bolt.py", line 575, in __eq__
AttributeError: 'PatchFile' object has no attribute '_lower'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 215, in PatchExecute
  File "bash\patcher\patch_files.py", line 501, in split_patch
  File "bash\patcher\patch_files.py", line 485, in new_bp_part
  File "bash\bosh\__init__.py", line 3129, in create_new_mod
  File "bash\bosh\__init__.py", line 2305, in cached_lo_insert_after
  File "bash\bolt.py", line 578, in __eq__
TypeError: descriptor 'lower' for 'str' objects doesn't apply to a 'PatchFile' object

I made create_mod_file a bit more complex (joking, it's the way of
factories, similar with find_launcher for instance) - chops off a
couple new_info which is *very* nice.

Under #533.

Some nit

native_init make recreate kw only

bash: textwrap.wrap messes the exception message - I split the message
so it wraps some