Regression - bash.bashFrame was None and restore settings failed:
See: #163
3fcbe3f87a99bca3f6aa85481697c0e3b073d390 (needed review!) introduced:

Traceback (most recent call last):
  File "<string>", line 11205, in Execute
  File "bash\barb.py", line 352, in Apply
    self.WarnRestart()
  File "bash\barb.py", line 411, in WarnRestart
    bash.bashFrame.Restart()
AttributeError: 'NoneType' object has no attribute 'Restart'

Turns out bashFrame is initialized in basher.BashApp.onInit(self):

def Init(self): # not OnInit(), we need to initialize _after_ the app
# has been instanced

There frame = BashFrame() is called and in there `BashFrame = self` is set.

Change: now basher.BashApp.onInit() returns the bashFrame !