Fix for relocating non repo files:
Would fail in my case with:
[package_for_release]: Creating installer distributable...
[package_for_release]:  WARNING: Non-repository files are present in your source directory.
[package_for_release]:           You have chosen to move the non-repository files out of the source directory temporarily.
[package_for_release]:  Relocating non-repository files:
[package_for_release]:   macro\py
[package_for_release]:   macro\macro
[package_for_release]:   bash\patcher\oblivion
[package_for_release]:   bash\game\falloutnv
[package_for_release]:   bash\game\fallout3
[package_for_release]:   _inis
[package_for_release]:   macro
[package_for_release]:  Restoring non-repository files
[package_for_release]:  Error calling creating installer, aborting creation.
Traceback (most recent call last):
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/scripts/package_for_release.py", line 520, in BuildInstallerVersion
    RelocateNonRepoFiles(non_repo)
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/scripts/package_for_release.py", line 391, in RelocateNonRepoFiles
    shutil.move(src, dst)
  File "C:\_\Python27\lib\shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
Error: Destination path 'scripts\temp\macro\macro' already exists

Turns out macro/ was first added to the non_repo.insert(0, dir) and
it was already there complete with subdir macro\macro. An ancient
Bash directory - if you were wondering.
Fix could be simpler but it's good enough for now
Avoided trying to move files that were moved with dirs:

- non_repo = [x[5:] for x in non_repo]
+non_repo = (x[5:] for x in non_repo)
+tuple_parent_dirs = tuple(parent_dirs)
+non_repo = [x for x in non_repo if not x.startswith(tuple_parent_dirs)]

Note bugsie fixed later in this merge - should be:

tuple(d + os.sep for d in parent_dirs)