Regression in installers rename:
Introduced in d09b43476b345591e5aa2ef9247e888bb08ed395, reported:
http://forums.bethsoft.com/topic/1606578-wrye-bash-thread-111/page-4#entry25243216
Traceback (most recent call last):
  File "bash\basher\__init__.py", line 2191, in OnLabelEdited
    any(grouped) for grouped in zip(*refreshes)]
TypeError: zip argument #2 must support iteration
Installers rename code just _needs_ simplification.

Signed-off-by: MrD <the.ubik@gmail.com>