[!]Regression - sound patcher broken in Oblivion:
Regression introduced in ed5c017de7006de5a806cf9ef5f84982fc7ea1c4 but
essentially the cause was 4977f324773b892392f8665fbf992e37d0c29b54
There was no minDist1 attribute - so when a mod was tagged with Sound
and included in the Import Sounds patcher and had a SOUN record it blew
with (note it blows parsing Oblivion.esm):

'MreSoun' object has no attribute 'minDist1'
Error loading 'SOUN' record and/or subrecord: 00025411
  eid = u'BlockLight'
  subrecord = 'SNDD'
  subrecord size = 8
  file pos = 268927
Error in Oblivion.esm
parsers.py 4016 load:
Traceback (most recent call last):
  File "bash\parsers.py", line 4010, in load
    self.tops[label].load(ins, unpack and (topClass != MobBase))
  File "bash\record_groups.py", line 70, in load
    ins.tell() + self.size - self.header.__class__.size)
  File "bash\record_groups.py", line 172, in loadData
    record = recClass(header,ins,True)
  File "bash\brec.py", line 1665, in __init__
    self.__class__.melSet.initRecord(self,header,ins,unpack)
  File "bash\brec.py", line 1212, in initRecord
    MreRecord.__init__(record,header,ins,unpack)
  File "bash\brec.py", line 1460, in __init__
    if ins: self.load(ins,unpack)
  File "bash\brec.py", line 1523, in load
    self.loadData(ins,inPos+self.size)
  File "bash\brec.py", line 1674, in loadData
    self.__class__.melSet.loadData(self,ins,endPos)
  File "bash\brec.py", line 1241, in loadData
    loaders[Type].loadData(record,ins,Type,size,readId)
  File "bash\game\oblivion\records.py", line 2079, in loadData
    MelStruct.loadData(self, record, ins, sub_type, size, readId)
  File "bash\brec.py", line 963, in loadData
    setter(attr,value)
AttributeError: 'MreSoun' object has no attribute 'minDist1'

Note that getSlotsUsed of MelSounSndd returns () - so the min/max
distance stuff is from the SNDX record.

Reported:

http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/page-6#entry25214456

In ed5c017de7006de5a806cf9ef5f84982fc7ea1c4 by plugging the arrays from
4977f324773b892392f8665fbf992e37d0c29b54 more records are processed.
Before only the {'MGEF', 'ACTI', 'LIGH', 'WTHR', 'CONT', 'DOOR'} records
were included both in soundsLongsTypes and in recAttrs_class dict while
now also 'SOUN', 'CREA' and "WATR" are added to the recAttrs_class dict.
Note that however 'CREA' and "WATR" are not included in soundsLongsTypes
still - bug ? Note also that WEAP is added to soundsLongsTypes, but will
not be processed IIRC.

Because of the CREA and WATR records being added in recAttrs_class but
not in soundsLongsTypes I mark this commit as needing attention - !

See also:

https://github.com/Sharlikran/wrye-bash/issues/20

Renamed minDistance etc to minDist1/2 etc and included only those from
SNDX subrecord for clarity. I could fix it by just rewriting
"SOUN": ('soundFile', 'minDistance', 'maxDistance', 'freqAdjustment',
         'staticAtten', ...)
but I did it this way for making clear the SNDX subrecord is used.

Signed-off-by: MrD <the.ubik@gmail.com>