Fixup in FileInfos.refresh():
On a corrupted save it would try to access oldInfo which was None:

Traceback (most recent call last):
  ...
  File "bash\basher\__init__.py", line 3946, in RefreshData
    if not self.booting and bosh.saveInfos.refresh():
  File "bash\bosh\__init__.py", line 4834, in refresh
    return FileInfos.refresh(self)
  File "bash\bosh\__init__.py", line 3749, in refresh
    isUpdated = not isAdded and not fileInfo.sameAs(oldInfo)
  File "bash\bosh\__init__.py", line 2982, in sameAs
    return ((self.size == fileInfo.size) and
AttributeError: 'NoneType' object has no attribute 'size'

Mods were accidentally immune as they catch AttributeError for the
isGhost stuff (duh). Still they would always mark the corrupted as
updated (sameAs returns False on AttributeError) so they would always
getHeaderError()- I made saves also recheck.