Fixup for parsing archives that have attribute-less files:
Utumno:
See:
http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/page-4#entry25210808
and couple next pages for the confusion this caused.
Final explanation:
http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/page-6#entry25214028
My wip branch features 7-zip 16.02 - and the output of the archive
listing code changed in that version. So:

Attributes = ....A
Attributes = D....
Attributes = .....  # no attributes !

became:

Attributes = A
Attributes = D
Attributes =   # no attributes !

However if one had the file before installing latest version (as
Arthmoor presumably did) Bash would detect it's the same file (size,
mod time) so would not refresh it, just display the cached info.
If OTOH the file was added after upgrading to utumno-wip (not dev!) then
16.02 tried to parse it and encountered an empty string instead of
"....." - boom:

File "bash\basher\__init__.py 5411 _refreshSource: Unable to read \
archive 'C:\Games\...\Oblivion Mods\Bash Installers\Really AEVWD.7z'.
Traceback (most recent call last):
  File "bash\bosh\__init__.py", line 5407, in _refreshSource
    bolt.list_archive(tempArch, _parse_archive_line)
  File "bash\bolt.py", line 2072, in list_archive
    parse_archive_line(*(maList.groups()))
  File "bash\bosh\__init__.py", line 5397, in _parse_archive_line
    elif key == u'Attributes': _li.isdir = (value[0] == u'D')
IndexError: string index out of range

Traceback (most recent call last):
  File "bash\balt.py", line 2353, in __Execute
  File "bash\balt.py", line 1556, in _conversation_wrapper
  File "bash\basher\installer_links.py", line 728, in Execute
  File "bash\basher\__init__.py", line 2456, in rescanInstallers
  File "bash\bosh\__init__.py", line 5140, in refreshBasic
  File "bash\bosh\__init__.py", line 5146, in _refreshBasic
  File "bash\bosh\__init__.py", line 5412, in _refreshSource
bash.bosh.InstallerArchiveError: Unable to read archive \
'C:\Games\...\Oblivion Mods\Bash Installers\Really AEVWD.7z'.

Another case where archives handling needs centralizing - 7z no-docs
do not help - could not really find what the expected output should be -
maybe bug them ?

For some acceptable docs on the list command see:
https://sevenzip.osdn.jp/chm/cmdline/commands/list.htm
although the output format is nowhere to be seen

I edited the original commit by @llde for more pythonic style and took
the opportunity to specify what splitlines(True) could possibly mean.

Closes #322.