Several fixes & misc improvements
Mopy/bash/cint.py:
Drop CBash 0.5.0 support entirely

Still had a random try in the middle of cint, when there's absolutely no
point - we can't support CBash 0.5.0 anymore, since all of the functions
have been renamed to start with a cb_, so even the fallback functions
won't exist, leading to cryptic error messages.

Instead, we now check if the CBash DLL is too old with
env.get_file_version() and log a more informative error if that is the
case.

Was originally thought to be the solution for #457, but that issue
turned out to be unrelated. Still a worthwhile commit for dropping a
print and improving the error message.

Mopy/bash/bolt.py:
Mopy/bash/mods_metadta.py:
Fix WryeText display of new tab links

Previously, it kept the exclamation mark if no alternate title was
defined for the link. Also added a better name for the xEdit cleaning
link.

Mopy/bash/basher/dialogs.py:
Fix Import Face dialog crashing

Since this line is unchanged from 9e6bbd925308c1c008fee34d8981e6f8c50b579c,
I can only conclude that wxPython must have changed behavior somewhere
along the way without anyone noticing. The line is clearly incorrect
though, we were allocating a sizer with space for 6 elements and shoving
10 in.

Note that this is *not* due to wx3 - wx2.8 exhibits the same behavior.

scripts/mktaglist.py:
Regression fix for SSE taglist generation

The taglist dir for SkyrimSE was renamed from 'Skyrim Special Edition'
to 'SkyrimSE' in 35421946ed2a5818b6b0a05438f3e0a4b233bea1.

However, the mktaglist script was not updated to account for these
changes. Whoops.

Mopy/bash/bosh/cosaves.py:
cosaves: Fixup for pluggy cosaves

Missed this when I fixed the xSE ones not discarding their lightly
loaded chunks before loading the full cosave.

Threw in a minor formatting change right below it, wrapping those
comments properly.

Under #437

Mopy/bash/ScriptParser.py:
ScriptParser: Fix broken arg count errors

When redoing some screenshots, I tried to reproduce the following error message:

  An error occurred in the wizard script:
  Line 15:	    Else 'What am I doing here?'
  Error:	(Line 15, Column 33): Too many arguments to Keyword 'Else':  got 1, expected 0.

However, I only managed to create the following:

  An error occurred in the wizard script:
  Line 15:	    Else 'What am I doing here?'
  Error:	(Line 15, Column 33): Too many arguments to Keyword 'self.text':  got 1, expected 0.

Turns out that the error reporting here has been broken since
40e3faaba167c18d58531ba417c9fe769a445182 back in 2011.
Also wrapped the code I touched.

Under #446