Regression: defaultGroups should be a list:
Traceback (most recent call last):
  File "bash\balt.pyo", line 1798, in DoItemMenu
  File "bash\balt.pyo", line 2218, in PopupMenu
  File "bash\balt.pyo", line 2330, in AppendToMenu
  File "bash\balt.pyo", line 2362, in AppendToMenu
  File "bash\balt.pyo", line 2350, in _range
  File "bash\basher\mod_links.pyo", line 226, in items
AttributeError: 'tuple' object has no attribute 'sort'

cf 'bash.mods.ratings': ['+','1','2','3','4','5','=','~']

Introduced in 2cb422fc35aa0454fc0bb0a037e9b8df8220d55b:
-    'bash.mods.groups': [x[0] for x in bush.baloGroups],
+    'bash.mods.groups': bush.defaultGroups, # a tuple