Fix ScanPatcher.scanModFile:
From @sibir-ine:

I found a bug with the Import Inventory patcher, it doesn't appear to
work unless the Contents Checker patcher is also enabled. The source is
7f44f280b21679e65c3ee77b071c07e06047459f. This appears to be related
to the Remove Empty Sublists bug.

Turns out there was a fencepost in ScanPatcher.scanModFile. Contents
checker (which suffered from the same bug but is much more generous in
adding records to the patch) would add the record (in the test case from
Oblivion.esm) and the record would be picked in ScanPatcher.buildPatch
from id_deltas and patched.

Some nit while I was (re) figuring things out, will be revisited when
we start working on #312 again - see also next commits (I eventually
removed _add_to_patch base method).

Mopy/bash/brec/common_records.py: this can contain non printable chars
as in:

bash.exception.ModError: test_overwrite.esp: 'Unexpected subrecord: TES4.,\x00\x00\x00'

Mopy/bash/patcher/patchers/mergers.py: made id_deltas private and did
a get - the if check was there anyway - we were creating a list for
each block entry and probably this is why we felt compelled to clear -
consequently I removed that bit of logic too.

Mopy/bash/patcher/patch_files.py: move methods below __init__ - I tried
to make set_active_arrays one use only but that proved tricky.