Tracking refreshFile uses and fixups in saves details - WIP:
I introduced a lot of APIs and parameters just to realize we can't yet
use them - we need a new_info API and move the copy header inside it -
else ModInfos will blow on _refreshInfoLists (that use the header) and
SaveInfos details will blow too.

basher/__init__.py - save details fixups:
- fix for SaveDetails editing when editing fails - RefreshUI would blow
as info was removed from SaveInfos.
- copy_info was buggy for saves - would not set the header and blow when
duplicating. Solved this by setting load_cache to True, but the right
way is copying the header along.
- _refresh_detail_info should reread the header, it blew on saves when
changing masters

Common traceback would leave UI in inconsistent state:

Traceback (most recent call last):
  File "bash\balt.py", line 1730, in OnItemSelected
    self._select(modName)
  File "bash\balt.py", line 1731, in _select
    def _select(self, item): self.panel.SetDetails(item)
  File "bash\basher\__init__.py", line 158, in SetDetails
    def SetDetails(self, fileName='SAME'): self._setDetails(fileName)
  File "bash\basher\__init__.py", line 156, in _setDetails
    self.detailsPanel.SetFile(fileName=fileName)
  File "bash\basher\__init__.py", line 1920, in SetFile
    self.playerNameStr = saveInfo.header.pcName
AttributeError: 'NoneType' object has no attribute 'pcName'

Flipped load_cache to true - it's False on __init__. Note ModInfos had
it True so always rereading header (even for just changeDate). BSAs
should be OK.

Under #336 - copy_info API needs rewrite.