Unknown subrecord PACK.SCDA:
Traceback lines are inaccurate as this is backported.

record_structs.py  609 loadData: Error loading PACK record and/or subrecord: (Skyrim.esm, 01CB07)
  eid = AlvorWork8x12
  subrecord = SCDA
  subrecord size = 17
  file pos = 243749289
mod_links.py  114 Execute: Exception loading Skyrim.esm:
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 105, in Execute
    self._load_mod(dbg_inf, keepAll=False,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 86, in _load_mod
    modFile.load(True, **kwargs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 199, in load
    new_top = topClass(header, self.loadFactory, ins,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 675, in __init__
    super().__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 213, in __init__
    super().__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 160, in __init__
    super().__init__(loadFactory, ins, self._end_pos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 50, in __init__
    self._load_rec_group(ins, endPos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 226, in _load_rec_group
    grel = self._group_element(header, ins)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 233, in _group_element
    return None if rec_class is None else rec_class(header, ins,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 567, in __init__
    MreRecord.__init__(self, header, ins, do_unpack=do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 400, in __init__
    self.loadData(ins, ins.size, file_offset=file_offset)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 612, in loadData
    raise exception.ModError(ins.inName, error)
bash.exception.ModError: Skyrim.esm: Unexpected subrecord: PACK.SCDA

I thought I fixed it but needed:

@@ -2344,3 +2338,3 @@ def __init__(self, attr):
         b'POCA': {
-            b'INAM|SCHR|SCTX|QNAM|TNAM|PDTO': u'on_change',
+            b'INAM|SCHR|SCDA|SCTX|QNAM|TNAM|PDTO': u'on_change',
         },
too.

I added SCDA only 'on_change':

took it from the xEdit definitions - see:

https://github.com/TES5Edit/TES5Edit/blob/d971eb7112d8758b6327696754a61536ebb2a9d7/Core/wbDefinitionsTES5.pas#L11511-L11545

where SCDA only appears on_change.

Mopy/bash/brec/advanced_elements.py: added the exceptions explicitly as
I raised ModError from the KeyError and wanted it in one line :P

@@ -254,3 +254,6 @@ def load_mel(self, record, ins, sub_type, size_, *debug_strs):
         for signature in loader_state:
-            current_scope = current_scope[signature]
+            try:
+                current_scope = current_scope[signature]
+            except KeyError as e:
+                raise ModError(ins.inName, f'{self}: unknown subrecord') from e
             if isinstance(current_scope, tuple): # handle mixed scopes

Then I removed it - needsa a more systematic approach.

Mopy/bash/exception.py: some nit - would be nice to specify types but that
need importing bolt here - a nono

Infernio:

Might as well save a couple lines here, can't hurt to accept the extra
leftover subrecords when they don't exist.

See:
https://github.com/wrye-bash/wrye-bash/commit/0a171e8d2a2304cba004d06231138a1c14a0c65c