[!]Rounder(float) POC:
tl;dr
sticking an ! cause this changes *all* float comparisons in records and
parsers code - note that parsers compared in a different way before.
Note also float attrs were used in sets - that probably lead to ITMs.
TODO: rel_tol/abs_tol - what would the game use here?

Leveraging the MelStruct init refactoring, this was another reason for
it. I believe that MelFloat and MelStruct are the only ones handling
floats. This add some overhead (wrapping) but I believe negligible and
maybe evened out by the omission of if checks for every attribute (think
branch prediction).

Note:

- different idioms for rounding/comparing/dumping
- Rounder.__str__ dropped the special treatment of self._float_attrs -
that's the only place we need those serialized as str - records will
still see floats
- threw in some tests to get us started
- threw in some typing comments - I don't like implicitness here but
it's not as important as in the ci_ strings case. Renaming all float
attrs to start with an f (or smth) is out of scope

We need to decide among the different idioms (round vs isclose_) -

EDIT: went for isclose_ cause that's the correct one - so parsers
changed behavior - they use isclose_ too not round - they still round
on writing out. Now that everybody is using isclose_ I removed it :D

The difficulty here is __hash__ - rounding keeps it consistent,
while having another method to compare and to hash is a known source
of undefined behavior. However those floats are not used anywhere as
keys/set elements and the like (edit: wrong - but they shouldn't). If we
go down the rounding path note Mopy/bash/brec/basic_elements.py -> do we
want to round on dump?

Another issue is Rounder(1.0000017) != Rounder(1.0000014) if we go with
rounding - again a matter of what the game does

Meanwhile:

- _read_record does not need to round - comparisons will be wrapped and
dumping to csv is taken care of by Rounder.__str__
- more _float_attrs uses are dropped due to dropping special casing of
float comparisons - this is of course a much more important gain
- yet another _constants_members gone - this is exactly what means
transferring the de/serialization on records, which is the moral of
the parsers refactoring. There is currently not an elegant way to
transfer (most) of the rest in the records - without spreading it all
over the records files that is. That may be possible in the future but
at the very least the _constants_members will be of a simple kind -
mapping sigs to attrs of interest - config, not business logic.

Fix test (when I was using round(self, 6) in equals - another motivation
to go with is_close_) - was failing in CI but not on my local (windoz)
machine....

Run python -m pytest
============================= test session starts =============================
platform win32 -- Python 2.7.18, pytest-4.6.11, py-1.10.0, pluggy-0.13.1
rootdir: D:\a\wrye-bash\wrye-bash
collected 74 items

Mopy\bash\tests\test_bolt.py .........................................   [ 55%]
Mopy\bash\tests\test_bosh\test_cosaves.py F............................. [ 95%]
..                                                                       [ 98%]
Mopy\bash\tests\test_bosh\test_list_info.py .                            [100%]

================================== FAILURES ===================================
_______________________ TestxSECosave.test_write_cosave _______________________

self = <bash.tests.test_bosh.test_cosaves.TestxSECosave object at 0x0000000006C37808>

    def test_write_cosave(self):
        """Tests if writing out all cosaves produces the same checksum."""
        def _check_writing(curr_cosave): # type: (xSECosave) -> None
            temp_cosave_path = curr_cosave.abs_path.temp
            curr_cosave.write_cosave(temp_cosave_path)
            assert curr_cosave.abs_path.crc == temp_cosave_path.crc
            # write_cosave and write_cosave_safe should have the same behavior
            curr_cosave.write_cosave_safe(temp_cosave_path)
            assert curr_cosave.abs_path.crc == temp_cosave_path.crc
            # Cosave writing should not change mtime, since we use that to
            # detect desyncs between save and cosave
            assert Rounder(curr_cosave.abs_path.mtime) == Rounder(
                temp_cosave_path.mtime)
>       self._do_map_cosaves(_check_writing)

Mopy\bash\tests\test_bosh\test_cosaves.py:89:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Mopy\bash\tests\test_bosh\test_cosaves.py:74: in _do_map_cosaves
    _map_cosaves(map_func, self._cosv_exts, self._cosv_type)
Mopy\bash\tests\test_bosh\test_cosaves.py:53: in _map_cosaves
    map_func(cosv_type(c))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

curr_cosave = xSECosave<lightly_modded_2.skse>

    def _check_writing(curr_cosave): # type: (xSECosave) -> None
        temp_cosave_path = curr_cosave.abs_path.temp
        curr_cosave.write_cosave(temp_cosave_path)
        assert curr_cosave.abs_path.crc == temp_cosave_path.crc
        # write_cosave and write_cosave_safe should have the same behavior
        curr_cosave.write_cosave_safe(temp_cosave_path)
        assert curr_cosave.abs_path.crc == temp_cosave_path.crc
        # Cosave writing should not change mtime, since we use that to
        # detect desyncs between save and cosave
>       assert Rounder(curr_cosave.abs_path.mtime) == Rounder(
            temp_cosave_path.mtime)
E       AssertionError: assert Rounder(1618840002.5121067) == Rounder(1618840002.512106)
E        +  where Rounder(1618840002.5121067) = Rounder(1618840002.5121067)
E        +    where 1618840002.5121067 = bolt.Path(u'D:\\a\\wrye-bash\\wrye-bash\\Mopy\\bash\\tests\\test_resources\\saves\\enderal\\lightly_modded_2.skse').mtime
E        +      where bolt.Path(u'D:\\a\\wrye-bash\\wrye-bash\\Mopy\\bash\\tests\\test_resources\\saves\\enderal\\lightly_modded_2.skse') = xSECosave<lightly_modded_2.skse>.abs_path
E        +  and   Rounder(1618840002.512106) = Rounder(1618840002.512106)
E        +    where 1618840002.512106 = bolt.Path(u'c:\\users\\runner~1\\appdata\\local\\temp\\WryeBash_temp\\lightly_modded_2.skse.tmp').mtime

Mopy\bash\tests\test_bosh\test_cosaves.py:87: AssertionError
==================== 1 failed, 73 passed in 12.43 seconds =====================
Error: Process completed with exit code 1.

Infernio:

Drop sets in _AMerger

Definitely slower, but this class needs a rewrite anyways (only after
py3 though).

Under #312, #480