TES4: Fix PGRD not sorting correctly
Causes a traceback on dump since you can't iterate MelObject:

Traceback (most recent call last):
  File "bash\gui\events.pyo", line 177, in _post
  File "bash\balt.pyo", line 825, in _conversation_wrapper
  File "bash\basher\patcher_dialog.pyo", line 191, in PatchExecute
  File "bash\basher\patcher_dialog.pyo", line 281, in _save_pbash
  File "bash\mod_files.pyo", line 293, in safeSave
  File "bash\mod_files.pyo", line 325, in save
  File "bash\brec\record_groups.pyo", line 1739, in dump
  File "bash\brec\record_groups.pyo", line 1739, in <genexpr>
  File "bash\brec\record_groups.pyo", line 1501, in dump
  File "bash\brec\record_groups.pyo", line 1155, in getBsbSizes
  File "bash\brec\record_groups.pyo", line 846, in getSize
  File "bash\brec\record_groups.pyo", line 851, in getChildrenSize
  File "bash\brec\record_groups.pyo", line 867, in getTempSize
  File "bash\brec\record_structs.pyo", line 491, in getSize
  File "bash\brec\record_structs.pyo", line 625, in dumpData
  File "bash\brec\record_structs.pyo", line 198, in dumpData
  File "bash\brec\advanced_elements.pyo", line 1049, in dumpData
  File "bash\game\oblivion\records.pyo", line 1488, in <lambda>
TypeError: 'MelObject' object is not iterable