Tests - set_game to all supported games:
Try and load all games to test record definitions. Note:

- MelModel is not needed anymore - simplify game handling
- we used display name (_allGames is keyed by that)
- Mopy/bash/brec/complex_subrecords.py: added a comment - could not find
where those were set

tl;dr

This is the reason for parent commit that bins the dynamic import.

Gory details of re-setting the game:

Initially it failed (for Oblivion derived games for instance, after it
set it to the first one) with:

Unexpected game constant 'preservers', check for typos or update _constants_members

That's because of the dynamic_import_modules doing

    from .patcher import preservers # adds them to the package namespace

bypassing this:

@@ -111,7 +111,11 @@ def _dynamic_import_modules(cls, package_name):
         for k in dir(patchers_module):
-            if k.startswith(u'_'): continue
+            if k.startswith(u'_') or k == 'preservers' or  k == 'checkers':
+                continue

leads to even more weird (heisen)bugs:

Traceback (most recent call last):
  File "/Users/ubik-mac13/Dropbox (Personal)/eclipse_workspaces/python/wrye-bash/Mopy/bash/tests/__init__.py", line 120, in set_game
    bush.game = _game_cache[gm_displayName]
KeyError: 'Fallout 3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ubik-mac13/Dropbox (Personal)/eclipse_workspaces/python/wrye-bash/Mopy/bash/tests/__init__.py", line 126, in set_game
    new_game.init()
  File "/Users/ubik-mac13/Dropbox (Personal)/eclipse_workspaces/python/wrye-bash/Mopy/bash/game/fallout3/__init__.py", line 297, in init
    cls._dynamic_import_modules(__name__)
  File "/Users/ubik-mac13/Dropbox (Personal)/eclipse_workspaces/python/wrye-bash/Mopy/bash/game/patch_game.py", line 117, in _dynamic_import_modules
    setattr(cls, k, getattr(patchers_module, k))
TypeError: 'cell' object is not callable

Wrapping setattr(cls, k, getattr(patchers_module, k)) won't ever stop at
the breakpoint at except:

            try:
                setattr(cls, k, getattr(patchers_module, k))
            except:
                raise # breakpoint not reached!!!!

See also

https://github.com/wrye-bash/wrye-bash/issues/400#issuecomment-1268661816

for a discussion.