Regression: new mod would error if the column clicked was not the first:
Traceback (most recent call last):
  File "bash\basher\mods_links.py", line 248, in Execute
    mods = selected if selected else fileInfos.data
TypeError: 'int' object is not iterable
Introduced in 6723857e3d4f98f6cef5ab87e6720d8410b137d8
self.selected == column index in main menus