env.py - winreg import moved from bass - WIP:
In _get_game_path() I added:

                break
            else:
                continue
            break

so the path is detected once:

winreg.HKEY_CURRENT_USER Software\Bethesda Softworks\Oblivion Installed Path
winreg.HKEY_CURRENT_USER Software\Wow6432Node\Bethesda Softworks\Oblivion Installed Path
Found: winreg.HKEY_LOCAL_MACHINE Software\Bethesda Softworks\Oblivion Installed Path (u'C:\\GAMES\\TESIV\\Oblivion\\', 1)
winreg.HKEY_CURRENT_USER Software\Bethesda Softworks\Skyrim Installed Path
winreg.HKEY_CURRENT_USER Software\Wow6432Node\Bethesda Softworks\Skyrim Installed Path
Found: winreg.HKEY_LOCAL_MACHINE Software\Bethesda Softworks\Skyrim Installed Path (u'C:\\GAMES\\Skyrim\\', 1)

Will be improved in next commits (and prints removed). Commenting it
out:

            #     break
            # else:
            #     continue
            # break

leads to:

winreg.HKEY_CURRENT_USER Software\Bethesda Softworks\Oblivion Installed Path
winreg.HKEY_CURRENT_USER Software\Wow6432Node\Bethesda Softworks\Oblivion Installed Path
Found: winreg.HKEY_LOCAL_MACHINE Software\Bethesda Softworks\Oblivion Installed Path (u'C:\\GAMES\\TESIV\\Oblivion\\', 1)
Found: winreg.HKEY_LOCAL_MACHINE Software\Wow6432Node\Bethesda Softworks\Oblivion Installed Path (u'C:\\GAMES\\TESIV\\Oblivion\\', 1)
winreg.HKEY_CURRENT_USER Software\Bethesda Softworks\Skyrim Installed Path
winreg.HKEY_CURRENT_USER Software\Wow6432Node\Bethesda Softworks\Skyrim Installed Path
Found: winreg.HKEY_LOCAL_MACHINE Software\Bethesda Softworks\Skyrim Installed Path (u'C:\\GAMES\\Skyrim\\', 1)
Found: winreg.HKEY_LOCAL_MACHINE Software\Wow6432Node\Bethesda Softworks\Skyrim Installed Path (u'C:\\GAMES\\Skyrim\\', 1)

Test code for winreg exceptions etc:

@@ -92,44 +92,24 @@ def _get_game_path(submod): # maybe move to env.py
                 _registryGames[submod.fsName.lower()] = installPath
                 break
             else:
                 continue
             break

-junk = 'non-existent'
-try:
-    key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, u'SOFTWARE\\7-zip')
-    print 'Found:', d[winreg.HKEY_CURRENT_USER], u'SOFTWARE\\7-zip'
-    print 'Value:', winreg.QueryValueEx(key, 'Path')
-    value = winreg.QueryValueEx(key, junk)
-except Exception as e:
-    import traceback
-    traceback.print_exc()
-
 def _detectGames(cli_path=u'',bashIni=None):

blows with:

Traceback (most recent call last):
  File "bash\bush.py", line 116, in <module>
    key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, u'SOFTWARE\\7-zip')
WindowsError: [Error 2] The system cannot find the file specified

while:

+try:
+    key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, u'SOFTWARE\\7-zip')

reads the key normally:

Found: winreg.HKEY_CURRENT_USER SOFTWARE\7-zip
Value: (u'C:\\Program Files\\7-Zip\\', 1)
Traceback (most recent call last):
  File "bash\bush.py", line 108, in <module>
    value = winreg.QueryValueEx(key, 'non-existent')
WindowsError: [Error 2] The system cannot find the file specified

A permissions issue ?

Since however as seen in the debug prints the key is found in
LOCAL_MACHINE I inverted the tuple and corrected my previous silly
break:

@@ -78,3 +78,3 @@ def _get_game_path(submod): # maybe move to env.py
     if not winreg: return
-    for hkey in (winreg.HKEY_CURRENT_USER, winreg.HKEY_LOCAL_MACHINE):
+    for hkey in (winreg.HKEY_LOCAL_MACHINE, winreg.HKEY_CURRENT_USER):
         for wow6432 in (u'', u'Wow6432Node\\'):
@@ -98,6 +98,5 @@ def _get_game_path(submod): # maybe move to env.py
                 _registryGames[submod.fsName.lower()] = installPath
-                break
+                return
             else:
                 continue
-            break
winreg.HKEY_LOCAL_MACHINE Software\Bethesda Softworks\Fallout4 Installed Path
winreg.HKEY_LOCAL_MACHINE Software\Wow6432Node\Bethesda Softworks\Fallout4 Installed Path
winreg.HKEY_CURRENT_USER Software\Bethesda Softworks\Fallout4 Installed Path
winreg.HKEY_CURRENT_USER Software\Wow6432Node\Bethesda Softworks\Fallout4 Installed Path
Found: winreg.HKEY_LOCAL_MACHINE Software\Bethesda Softworks\Oblivion Installed Path (u'C:\\GAMES\\TESIV\\Oblivion\\', 1)
Found: winreg.HKEY_LOCAL_MACHINE Software\Bethesda Softworks\Skyrim Installed Path (u'C:\\GAMES\\Skyrim\\', 1)