Small fixups/cleanups from 190-pt1 merge:
Mopy/bash/gui/top_level_windows.py:
Regression - if balt.sizes was empty dialogs became non resizable

Mopy/bash/bash.py:
Regression - when wx fails to import, `_` is not yet defined (actually
was introduced in some earlier stage, probably locale changes)

Traceback (most recent call last):
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 89, in <module>
    bash.main(opts)
  File "bash\bash.py", line 200, in main
    _import_wx()
  File "bash\bash.py", line 89, in _import_wx
    but_kwargs = {'text': _(u"QUIT"),
NameError: global name '_' is not defined

190-pt1 leftovers:

Rearrange WithMouseEvents: cleaner to specify True for events we want to
bind
Wrap some more of UIListCtrl, although we should do this more
intelligently - that is we need a base class for ListCtrl components,
as we need to wrap INIListCtrl also - so a class variable for the
wx control we wrap.

Infernio:
Mopy/bash/basher/patcher_dialog.py: auto-close progress dialog

The patcher_dialog change looks weird, but mirrors PBash behavior -
without it, users have to *manually* close the BP progress dialog.