Fixups for CreateNewProject / export script:
- disable the button instead of canceling
- color the control red from the beginning if same name project exists
- drop self._native_widget.SetInitialSize() - use fit=true instead

- TODO:

tooltip is not set on first showing the dialog even though text box is
red (I have a project named u'New Project Name-#####' to test) !?

Mopy/bash/basher/mod_links.py: Fixups for export script

- if we created a subfolder in the defaultPath to store the scripts it
would blow with:

Traceback (most recent call last):
  File "bash\balt.py", line 2040, in __Execute
    self.Execute()
  File "bash\basher\mod_links.py", line 2079, in Execute
    defaultPath.removedirs()
  File "bash\bolt.py", line 730, in removedirs
    os.removedirs(self._s)
  File "C:\_\Python27\lib\os.py", line 170, in removedirs
    rmdir(name)
WindowsError: [Error 145] The directory is not empty: u'D:\\GAMES\\TESIV\\Oblivion\\Data\\Bash Patches\\ConjurationTomeOOO-OBSE.esp Exported Scripts'

I now delete only if folder did not exist before and is empty

- some wrapping