Regression (hitting enter in installers/screens dialogs), renames fix:
9d286e1b47017fc4842fbdb96e2196f6df7c5e2b introduced a regression, namely
hitting enter on "Move To" dialog would open the moved installer.
Turned out that what triggered this was unbinding the OnShow event via
the @balt.conversation in Installer_Move.

--------------------- Mopy/bash/basher/installer_links.py ---------------------
index 917a121..2d2337b 100644
@@ -616,3 +616,3 @@ class Installer_Move(_InstallerLink):

-    @balt.conversation
+    @balt.conversation ##: enter key is propagated to installer
     def Execute(self):

Which send me to a goose chase trying to "fix" balt.conversation (notice
the (wrong) comment above):

    def BindRefresh(self, bind=True, __event=wx.EVT_ACTIVATE):
        if bind: self.Unbind(__event)
        self.Bind(__event, self.RefreshData if bind else self._noop)
        if not bind: self.Bind(__event, self._noop)

    def _noop(self, event): pass # event.Skip or Veto won't do

which did nothing to prevent the enter keystroke being propagated.
What solved it was moving the enter handling in OnChar - explanation:
unbinding RefreshData made the operation fast enough for Bash window
to gain focus, so the Key Up event (on hitting enter in the move dialog)
was caught by it and fired its event handler (open the installer) !
Applied the same cure to screnshots, got me rid of rename opening those
(under #259). Yey ! This has tripped me too long - note that it was not
always reproducible (depending on how fast I hit enter...)

Fixed another regression introduced in same commit - passing an order
greater that installers data length would move to last but keep the
order to this large value.

Finally b05821bbc511494ec99131b5e2605ee266482065 made apparent a flaw
in renaming - installer markers would all have their archive set to
u'====' leading to:

Traceback (most recent call last):
  File "bash\balt.py", line 2354, in __Execute
    self.Execute()
  File "bash\balt.py", line 1574, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\installer_links.py", line 638, in Execute
    self.window.SelectAndShowItem(GPath(current_archive.archive), focus=True)
  File "bash\balt.py", line 1969, in SelectAndShowItem
    self.SelectItem(item, deselectOthers=deselectOthers)
  File "bash\balt.py", line 1933, in SelectItem
    dex = self.GetIndex(item)
  File "bash\balt.py", line 2065, in GetIndex
    return self._gList.FindIndexOf(item)
  File "bash\balt.py", line 1552, in FindIndexOf
    return self.FindItemData(-1, self._item_itemId[item])
KeyError: bolt.Path(u'====')

Fixed

Signed-off-by: MrD <the.ubik@gmail.com>