Several regression fixes, some miscellaneous fixes
This commit is a squashed version of several fixes that have been piling
up. A full list of the original commit messages follows:

-----------------------------------------------------------------------

Regression fix: Always fix active mods list

Fixes a regression introduced in 3214e6962093e770ec36dec43b315e05944f1bf6.

acti_filtered only contains those plugins from acti that are actually on
the disk. The previous code always ran

  acti[:] = acti_filtered[:max_espms]

while the new code only does the equivalent to that if more than 255
ESPs / 4096 ESLs are found. This causes an error and fails to sanitize
the plugins.txt file if an activated mod is manually deleted (i.e.
outside Wrye Bash) during runtime.

-----------------------------------------------------------------------

Set default Skyrim HEDR version to 1.7

The CK hasn't emitted entries with 0.94 since basically forever, so I
have no idea why Wrye Bash never got updated for this. This makes the
'New Mod' funcion create files with the correct 1.7 version (also
applies to empty Bashed Patch files).

-----------------------------------------------------------------------

Fix incorrect ConfigParser usage

This was causing a crash when the game's INI file is located inside the
game folder. The traceback looked like this:

Traceback (most recent call last):
  File "bash\bash.pyo", line 185, in main
  File "bash\bash.pyo", line 261, in _main
  File "bash\bash.pyo", line 383, in _detect_game
  File "bash\initialization.pyo", line 156, in init_dirs
  File "ConfigParser.pyo", line 242, in __init__
AttributeError: 'unicode' object has no attribute 'items'

The cause was that ConfigParser.__init__() doesn't actually take a
string - that string should be passed to ConfigParser.read() instead.

-----------------------------------------------------------------------

Also query string fields when retrieving exe versions

EXEs have two sets of fields from which metadata can be retrieved:
string fields and 'fixed' fields.
Wrye Bash was only reading data from the fixed fields - but SkyrimSE.exe
only has meaningful data in the string fields. This patch preserves old
behavior in all cases where a meaningful version (i.e. one that isn't
1.0.0.0 or 0.0.0.0) can be read from the fixed fields. If that is not
the case (e.g. SkyrimSE.exe), then the string fields are queried as
well.

With this change, the CompareGameVersion and RequireVersions wizard
functions as well as the game launch button version display in the
bottom left corner are fixed in SSE.

-----------------------------------------------------------------------

Regression Fix: Skip empty plugin dirs when checking mergeability

Those resolve to Data/PLUGIN_NAME.esp - which obviously always exists,
that's the plugin file! Whoops.

Also made the plugin dirs mergeability feedback much more readable.

-----------------------------------------------------------------------

Closes #436.
Closes #438.

Co-authored-by: Sharlikran <danielhmpdx16@gmail.com>