Fixup in cosaves refresh (and export scripts):
Turns out get_cosave_instances was called too late -
SaveInfos refresh runs high up in the boot order and would go ahead
and update the class variable having the cosaves been shared at random
- yak! The reason we had not seen that is that when clients used the
cosaves then we would see it was the __empty ones (now filled) and
assign to instance variable. The one part that was not thoroughly tested
in e4dc76995703f16ee97fb07d495b6db635a2c6a8 (that stayed in nightly for
aeons)
Well, so much the better - got rid of all this machinery and overrode
__init__ -> explicit. I left the _co_saves private till we make sure
all uses are with an updated cache.
Mopy/bash/parsers.py: deprefix was not case insensitive as claimed

Small stuff:

Mopy/bash/bosh/ini_files.py: omitted the default parameter, why
instantiate a DefaultIniFile without settings?

Mopy/bash/bash.py: panel -> scrl_win (UIList has a self.panel attr...)

Mopy/bash/balt.py: added deprint - prints:

balt.py 3212 OnDragEnd: Exception while handling mouse up on button
Traceback (most recent call last):
  File "bash\balt.py", line 3209, in OnDragEnd
    button.ReleaseMouse()
  File "C:\_\Python27\lib\site-packages\wx\_core.py", line 10646, in ReleaseMouse
    return _core_.Window_ReleaseMouse(*args, **kwargs)
PyAssertionError: C++ assertion "!wxMouseCapture::stack.empty()" failed at ..\..\src\common\wincmn.cpp(3319) in wxWindowBase::ReleaseMouse(): Releasing mouse capture but capture stack empty?

Mopy/bash/bosh/bain.py: Fix png progress - when running the debugger
the dialog would stay displayed (it would be killed afterwards, just
the debugger made me notice) -  not sure what is the correct fix
here - balt.Progress needs revisiting.

Mopy/bash/basher/__init__.py: Fix drag and drop tabs position.

Infernio: Make cosaves initialize before the save itself

Otherwise it crashes on SSE on FO4 which may need the
cosaves already initialized to determine their masters.