Fix Move To not working if first plugin inactive
Would fail with a traceback since it's querying the active index of an
inactive plugin:

Traceback (most recent call last):
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\balt.py", line 1806, in __Execute
    self.Execute()
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\basher\mod_links.py", line 243, in Execute
    default_index = (load_order.cached_active_index(self.selected[0])
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\load_order.py", line 221, in cached_active_index
    def cached_active_index(mod): return cached_lord.activeIndex(mod)
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\load_order.py", line 133, in activeIndex
    def activeIndex(self, mname): return self.__mod_actIndex[mname]
KeyError: FName('Cobl Main Copy.esp')