Fixup for wx3 - Dropping SetFocus calls from balt.Progress:
@Metallicow:
IMPORTANT FIX InstallersTab Progress freeze/crash

InstallersPanel when first clicking on it. Is this really needed?

Utumno:

Actually all progress dialogs were broken:

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 3610, in OnShowPage
    self.currentPage.ShowPanel()
  File "bash\basher\__init__.py", line 2646, in ShowPanel
    fullRefresh, scan_data_dir)
  File "bash\balt.py", line 1571, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\bosh\__init__.py", line 5806, in _projects_walk_cache_wrapper
    return func(self, *args, **kwargs)
  File "bash\basher\__init__.py", line 2670, in _refresh_installers_if_needed
    with balt.Progress(_(u'Refreshing Installers...'),u'\n'+u' '*60, abort=canCancel) as progress:
  File "bash\balt.py", line 1295, in __init__
    self.dialog.SetFocus()
  File "C:\_\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 10129, in SetFocus
    return _core_.Window_SetFocus(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "hWnd" failed at ..\..\src\msw\window.cpp(562) in wxWindow::SetFocus(): can't set focus to invalid window

Turns out that SetFocus on Windows is not a real call anymore cause
wxProgressDialog is not a "native" dialog anymore in wx3. As anyway
the SetFocus call won't do anything, due to wx.PD_APP_MODAL meaning the
progress has focus, I decided to drop them - see answer by @RobinD42:
http://stackoverflow.com/q/38012813/281545

Seems that installers loading got marginally faster too.

However there are still some issues with Bash installers refresh
progress dialog loosing focus on boot (when started from the debug
dat file). Annoying. In wx3 is even more pronounced but is not related
to this commit. It's the boot sequence that needs revisiting - we must
bind RefreshData and show its dialogs at the very end.

Under #11.