Fix for stale InstallerArchive in 'crc_installer':
That was brought to light cause one long ago deleted archive in
'crc_installer' values had a str (probably due to 543 __reduce__)
instead of a Path leading to:

Traceback (most recent call last):
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\basher\__init__.py", line 3795, in OnShowPage
    self.currentPage.ShowPanel(
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\balt.py", line 815, in _conversation_wrapper
    return func(*args, **kwargs)
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\basher\__init__.py", line 3246, in ShowPanel
    self._refresh_installers_if_needed(canCancel, fullRefresh,
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\balt.py", line 815, in _conversation_wrapper
    return func(*args, **kwargs)
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\bosh\bain.py", line 1695, in _projects_walk_cache_wrapper
    return func(self, *args, **kwargs)
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\basher\__init__.py", line 3281, in _refresh_installers_if_needed
    refreshui |= self.listData.irefresh(progress, what,
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\bosh\bain.py", line 1772, in irefresh
    changed = not self.loaded and self.__load(progress)
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\bosh\bain.py", line 1794, in __load
    self.dictFile.load()
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\bolt.py", line 1477, in load
    _perform_load() # new format, simply load
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\bolt.py", line 1460, in _perform_load
    self.pickled_data.update(pickle.load(ins, encoding='bytes'))
  File "F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\bosh\bain.py", line 325, in __init__
    self.archive = archive.stail
AttributeError: 'str' object has no attribute 'stail'

Fixed by removing the unused 'crc_installer' dict.

Note the not self.abs_path.exists() would also run for markers so their
keys would be never converted if it wasn't for the code in
InstallersData.__load. I moved the conversion before the check and
avoided the syscall for markers.

Fix for Installers hide checking non absolute paths