[!]Attempt to fixup yet another wx.locale error:
Points I am unsure about (!):
- what's the deal with restore_stdio/MainLoop resets stdio
- seems calling App.MainLoop twice is fine (?)
- _close_dialog_windows was always called before _show_boot_popup except
  once in the case `if len(game_infos) == 0` TODO: test if calling there
  also is ok? (maybe it solves some bugs even)

See #610 for the description of the bug - the crash occurred in
creating bitmaps:

https://discord.com/channels/537706885965676554/537710082755133460/890610560838823976

 File "bash\bash.py", line 273, in main
  File "bash\bash.py", line 449, in _main
  File "bash\basher__init.py", line 4249, in Init
  File "bash\basher__init.py", line 3858, in init
  File "bash\balt.py", line 2189, in init
  File "bash\basher__init__.py", line 3751, in UpdateIconSizes
  File "bash\balt.py", line 2205, in _addButton
  File "bash\basher\app_buttons.py", line 172, in GetBitmapButton
  File "bash\gui\base_components.py", line 502, in GetBitmap
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ....\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

I added some deprints:

@@ -495,2 +495,3 @@ def GetBitmap(self):
			 else:
+                deprint(f'Loading bitmap for {self._img_path}')
				 self.bitmap = _wx.Bitmap(self._img_path, self._img_type)

And initially I tried to move load_app_icons further down in the boot
sequence but that didn't do it.

Turns out the gamedialog was displayed, which created another wx.App
that did something strange - anyway I monkey patched wx.App based on:

https://github.com/wxWidgets/Phoenix/commit/040c59fd991cd08174b5acee7de9418c23c9de33

Initially I really monkey patched as in:

_wx.App = _LocaleApp

then dropped it in favour of instantiating the wx.App once.

We do not seem to have a reason to delay the creation of the wx App, and
this seems to be a singleton of sorts (?) so instantiating a bunch seems
not a standard way of doing wx - I dropped all these calls and seems the
wxAssertion is gone but still checking that the locale works, in all
combinations of user locales/cli language options/paths in boot/python
vs standalone, is needed.

Note I moved the versions checks earlier (!)

The sooner the better but always tricky to rearrange things here - note
I dropped a wx import

- show_frame override (I added a center param to show_frame)

Reduce _wx uses with a global

- Initially I was passing it as an argument but that was too noisy - _wx
is ugly 'nough.
Note we finally import wx *once* - yey (#190)

ImageWrapper/ImageBundle: do we need those? (#366)

Under #610