WIP testing OBME records:
I wanted to load in the command line so I did some #600 digging - not
sure about the localize change, WIP. _emulate_startup() as it is now
leaves the record system broken for 'Oblivion (Steam)' - more work is
needed to be able to reload the game records - what happens probably is
that record header variables are kept from some previously loaded
flavor, like ORE, so loading the TES4 record fails with:

from Mopy.bash.tests import *
from Mopy.bash.mod_files import *
from Mopy.bash.bosh import ModInfo
p = bolt.Path(r"D:\...\De Rerum Dirennis.esp")
m=ModFile(ModInfo(p), LoadFactory(True, by_sig=bush.game.top_groups))
loot_parser.py   55 <module>: Using LibYAML-based parser
m.load_plugin()
record_structs.py  570 loadData: Error loading TES4 record and/or subrecord: 0
  eid = <<NO EID>>
  subrecord = AM
  subrecord size = 1919252337
  file pos = 48
  header flags = 0x00000000 (None)
Traceback (most recent call last):
  File "C:\Users\MrD\AppData\Local\Programs\PyCharm Professional 2\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 179, in load_plugin
    with cont.from_info(self.fileInfo) as ins:
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\mod_io.py", line 394, in __enter__
    self.load_tes4()
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\mod_io.py", line 276, in load_tes4
    self.plugin_header = bush.game.plugin_header_class(tes4_rec_header,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 528, in __init__
    MreRecord.__init__(self, header, ins, do_unpack=do_unpack)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 334, in __init__
    self.loadData(ins, ins.size, file_offset=file_offset)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\common_records.py", line 264, in loadData
    super().loadData(ins, endPos, file_offset=file_offset)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 573, in loadData
    raise exception.ModError(ins.inName, f'{error!r}')
Mopy.bash.exception.ModError: De Rerum Dirennis.esp: 'Unexpected subrecord: TES4.AM\x07\x00'

Setting the game in Oblivion (Steam) loads the mod just fine with:

m=ModFile(ModInfo(p), LoadFactory(False, by_sig=bush.game.top_groups)) # note False!

bush: shortened a bit game detection printings (and the code that prints
them). This whole thing belongs to env.get_game_paths which will return
a simpler version of store_results (k: (mods, msg)) - done later.

oblivion/records.py: leftover from c49a5401d505eefc802b063d96dde6d337d84ebd