Regression: bsa redirection was enabled for Skyrim:
So switching to the installers tab would result in:

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 4218, in OnShowPage
    self.GetPage(event.GetSelection()).OnShow()
  File "bash\basher\__init__.py", line 3065, in OnShow
    if data.refresh(progress,what,self.fullRefresh):
  File "bash\bosh.py", line 7785, in refresh
    oblivionIni.setBsaRedirection(True)
  File "bash\bosh.py", line 2684, in setBsaRedirection
    source.mtime = aiBsaMTime
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\bolt.py", line 733, in setmtime
    os.utime(self._s,(self.atime,int(mtime)))
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\bolt.py", line 689, in atime
    return os.path.getatime(self._s)
  File "C:\_\Python27\lib\genericpath.py", line 59, in getatime
    return os.stat(filename).st_atime
WindowsError: [Error 2] The system cannot find the file specified: u'C:\\Dropbox\\eclipse_workspaces\\python\\wrye-bash\\Mopy\\templates\\Skyrim\\ArchiveInvalidationInvalidated!.bsa'

See: second post on #177.

good: 3d692800f7cf323061cc5414abbbb4a50c473897
bad: 4a24320b50f90888a0ced376500862b7d4a55200

Introduced in 682bf130b36866ce26983c204eef1ba4288cac53 (broken for TESV!).
Apparently, on rebasing on dev this:

     #--INI Entry to enable BSA Redirection
-    bsaRedirection = (u'sResourceArchiveList',u'sResourceArchiveList2')
+    bsaRedirection = (u'',u'')

was left out.
Went through the bad -> good diff. Notes:
Some of the namespace changes, such as bolt.Flags -> Flags, were not needed
and blurred the diffs - lesson: no namespace changes if it can be avoided.
Diffs were blurred also by warning fixes and the like - oh well.
Added back a couple comments that were clearer in good (a lot were clearer
in bad I must say).

Newlines nitpick.