Fixup for decoding errors in omods:
py3 bytes vs strings strikes again - not sure about the encoding - omods.py
seems to use utf-8 everywhere.

https://discord.com/channels/537706885965676554/537710082755133460/924459634578829332

localize.py  103 setup_locale: cli_lang='' - cli_target='' - falling back to (en_US, cp1252) from getdefaultlocale
localize.py  158 setup_locale: Set wxPython locale to 'en_US'
doc_viewer.py   38 <module>: pdfviewer using PyMuPDF (GPL)
bash.py  245 dump_environment: Using Wrye Bash Version 310.202112252111 (Standalone)
	OS info: Windows-10-10.0.19044-SP0, running on Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
	Python version: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
	Dependency versions:
	 - chardet: 4.0.0
	 - PyMuPDF: 1.19.3; bundled MuPDF version: 1.19.0
	 - python-lz4: 3.1.10; bundled LZ4 version: 1.9.3
	 - PyYAML: 6.0
	 - wxPython: 4.1.1 msw (phoenix) wxWidgets 3.1.5
	Input encoding: None; output encoding: utf-8
	Filesystem encoding: utf-8
	Command line: ['C:\\Games\\Modding\\Mopy_Temp\\Wrye Bash.exe']
bash.py  488 _import_bush_and_set_game: Searching for game to manage:
bush.py  144 _supportedGames: The following games are supported by this version of Wrye Bash:
  Enderal, Enderal Special Edition, Fallout 3, Fallout 3 (WS), Fallout
  4, Fallout 4 (WS), Fallout 4 VR, Fallout New Vegas, Fallout New Vegas
  (WS), Morrowind, Morrowind (WS), Nehrim, Oblivion, Oblivion (WS),
  Skyrim, Skyrim Special Edition, Skyrim Special Edition (WS), Skyrim VR
Wrye Bash looked for games in the following places:
 1. Windows Registry:
  The following installed games were found via the registry:
   - Fallout 3: D:\Games\SteamLibrary\steamapps\common\Fallout 3 goty
   - Fallout 4: C:\Games\Steam\steamapps\common\Fallout 4
   - Fallout New Vegas: D:\Games\SteamLibrary\steamapps\common\Fallout New Vegas
   - Morrowind: D:\Games\SteamLibrary\steamapps\common\Morrowind
   - Oblivion: C:\Games\Steam\steamapps\common\Oblivion
   - Skyrim: D:\Games\SteamLibrary\steamapps\common\Skyrim
   - Skyrim Special Edition: C:\Games\Steam\steamapps\common\Skyrim Special Edition
  Make sure to run the launcher of each game you installed through Steam
  once, otherwise Wrye Bash will not be able to find it.
 2. Windows Store:
  No installed games with modding enabled were found via the Windows Store.
  Make sure to enable mods for each Windows Store game you have
  installed, otherwise Wrye Bash will not be able to find it.
bush.py  205 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  211 _detectGames: Set game mode to Oblivion based on sOblivionPath setting in bash.ini:  C:\Games\Steam\steamapps\common\Oblivion
bush.py  227 __setGame: Using Oblivion game: C:\Games\Steam\steamapps\common\Oblivion
initialization.py  159 init_dirs: My Games location set to C:\Users\ph\Documents\My Games\Oblivion
initialization.py  172 init_dirs: LocalAppData location set to C:\Users\ph\AppData\Local\Oblivion
initialization.py  220 init_dirs: Game Mods location set to C:\Games\Modding\Wrye Bash Data\TES4\Temp
initialization.py  225 init_dirs: Bash Mod Data location set to C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Mod Data
initialization.py  229 init_dirs: Installers location set to C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Installers
initialization.py  231 init_dirs: Installers bash data location set to C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Installers\Bash
initialization.py  239 init_dirs: Checking if WB directories exist and creating them if needed:
initialization.py  243 init_dirs:  - C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Mod Data
initialization.py  243 init_dirs:  - C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Installers
initialization.py  243 init_dirs:  - C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Installers\Bain Converters
initialization.py  243 init_dirs:  - C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Installers\Bain Converters\--Duplicates
initialization.py  243 init_dirs:  - C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Installers\Bain Converters\--Corrupt
initialization.py  243 init_dirs:  - C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Installers\Bash
initialization.py  243 init_dirs:  - C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Installers\Bash\BSA Cache
loot_parser.py   48 <module>: Using LibYAML-based parser
loot_parser.py   83 __init__: Using these LOOT paths:
loot_parser.py   84 __init__:  Masterlist: C:\Users\ph\AppData\Local\LOOT\Oblivion\masterlist.yaml
loot_parser.py   85 __init__:  Userlist: C:\Users\ph\AppData\Local\LOOT\Oblivion\userlist.yaml
loot_parser.py   86 __init__:  Taglist (fallback): C:\Games\Modding\Mopy_Temp\taglists\Oblivion\taglist.yaml
__init__.py 3705 initBosh: Initialized loot_parser, compatible with libloot v0.16.x
__init__.py 3708 initBosh: Looking for main game INI at C:\Users\ph\Documents\My Games\Oblivion\Oblivion.ini
windows.py  967 testUAC: Testing if game folder is UAC-protected
__init__.py 1563 _initDB: Initializing BSAInfos
__init__.py 1564 _initDB:  store_dir: C:\Games\Steam\steamapps\common\Oblivion\Data
__init__.py 1565 _initDB:  bash_dir: C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Mod Data\BSA Data
__init__.py 1563 _initDB: Initializing ModInfos
__init__.py 1564 _initDB:  store_dir: C:\Games\Steam\steamapps\common\Oblivion\Data
__init__.py 1565 _initDB:  bash_dir: C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Mod Data
_games_lo.py  670 print_lo_paths: Using the following load order files:
_games_lo.py  677 print_lo_paths:  - Active plugins: C:\Users\ph\AppData\Local\Oblivion\plugins.txt
__init__.py 1563 _initDB: Initializing SaveInfos
__init__.py 1564 _initDB:  store_dir: C:\Users\ph\Documents\My Games\Oblivion\Saves
__init__.py 1565 _initDB:  bash_dir: C:\Users\ph\Documents\My Games\Oblivion\Saves\Bash
__init__.py 1563 _initDB: Initializing INIInfos
__init__.py 1564 _initDB:  store_dir: C:\Games\Steam\steamapps\common\Oblivion\Data\INI Tweaks
__init__.py 1565 _initDB:  bash_dir: C:\Games\Modding\Wrye Bash Data\TES4\Temp\Bash Mod Data\INI Data
base_components.py  499 get_bitmap: getting image C:\Games\Modding\Mopy_Temp\bash\images\checkbox_red_off.png
...
__init__.py 3599 __init__: Constructing panel 'Installers'
base_components.py  499 get_bitmap: getting image C:\Games\Modding\Mopy_Temp\bash\images\checkbox_green_off.png
...
__init__.py 3609 __init__: Panel 'Installers' constructed successfully
__init__.py 3599 __init__: Constructing panel 'Mods'
base_components.py  499 get_bitmap: getting image C:\Games\Modding\Mopy_Temp\bash\images\checkbox_purple_on.png
...
base_components.py  499 get_bitmap: getting image C:\Games\Modding\Mopy_Temp\bash\images\checkbox_red_imp.png
__init__.py 3609 __init__: Panel 'Mods' constructed successfully
__init__.py 2516 _extractOmods: Failed to extract 'Deadly Reflex 6 - Combat Moves 6.0.omod'.

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 2508, in _extractOmods
  File "bash\bosh\omods.py", line 139, in extractToProject
  File "bash\bosh\omods.py", line 211, in _extract_omod
  File "bash\bosh\omods.py", line 293, in extractFiles7z
  File "bash\bosh\omods.py", line 251, in splitStream
TypeError: can only concatenate str (not "bytes") to str

__init__.py 2516 _extractOmods: Failed to extract 'Ultimate 3rd Person Camera - RightSide and Close - Default 1.51.omod'.

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 2508, in _extractOmods
  File "bash\bosh\omods.py", line 139, in extractToProject
  File "bash\bosh\omods.py", line 211, in _extract_omod
  File "bash\bosh\omods.py", line 293, in extractFiles7z
  File "bash\bosh\omods.py", line 251, in splitStream
TypeError: can only concatenate str (not "bytes") to str

----

Some info on omods by AnyOldName in
https://discord.com/channels/537706885965676554/537710082755133460/925054352895402096

A lot of the data inside is binary, so obviously text encoding doesn't matter.
For the parts embedded in other files, usually they're intended to be read via
.NET's BinaryReader's ReadString method, documented here:
https://docs.microsoft.com/en-us/dotnet/api/system.io.binaryreader.readstring?view=net-6.0#System_IO_BinaryReader_ReadString. That's supposed to understand
things written by BinaryWriter.Write:
https://docs.microsoft.com/en-us/dotnet/api/system.io.binarywriter.write?view=net-6.0#System_IO_BinaryWriter_Write_System_String_. In the library the MO2
plugin uses, the BinaryReader is default-constructed, so it uses UTF-8, but
there's a possibility that's just because that was the default and no one's
tried it with an OMOD that used anything else yet.