Regression - renaming mods was broken - WIP:
Made apparent in 9428a03fd1c2c34ef327fe58d6d9d46812c389a7 but the roots
were deeper. The traceback reported in

https://github.com/wrye-bash/wrye-bash/issues/92#issuecomment-279340341

...
  File "bash\bosh\__init__.py", line 3510, in _rename_operation
    FileInfos._rename_operation(self, oldName, newName)
  File "bash\bosh\__init__.py", line 2534, in _rename_operation
    fileInfo.abs_path = self.store_dir.join(newName)
AttributeError: can't set attribute

was due to the peculiar override rules of properties:
http://stackoverflow.com/a/7020531/281545
But then the rename was broken for ghosts due to the newName being set
to the ghost one. Solved at the root by finally removing this
intentionally ugly piece of code (badly indented) from
FileInfos#_rename_operation.
I added todos for backups - under #292

WIP - I should drop tuples in _backup_infos

Under #259