Use callable(action) to check if action is present
FixedString inherits from unicode, and hence its __bool__ evaluates to
False when the wrapped string happens to be empty (i.e. the default).

Without this, non-ASCII description and author fields in Morrowind blow
up with a traceback like this:

Traceback (most recent call last):
  File "bash\bash.pyo", line 268, in main
  File "bash\bash.pyo", line 444, in _main
  File "bash\basher\__init__.pyo", line 4275, in Init
  File "bash\basher\__init__.pyo", line 4303, in InitData
  File "bash\bosh\__init__.pyo", line 2280, in refresh
  File "bash\bosh\__init__.pyo", line 2455, in _refresh_bash_tags
  File "bash\bosh\__init__.pyo", line 709, in reloadBashTags
  File "bash\bosh\__init__.pyo", line 695, in getBashTagsDesc
  File "bash\brec\common_records.pyo", line 105, in description
  File "bash\bolt.pyo", line 229, in to_unix_newlines
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 12: ordinal not in range(128)