Fix for _file_key not being set when calling repr early in init:
Compliments of fe29d7151f671d4468aad59db0514ba494f0c38f

Traceback (most recent call last):
  File "bash\bosh\__init__.py", line 219, in __init__
  File "bash\bosh\__init__.py", line 233, in set_table_prop
KeyError: 'mtime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bash\bash.py", line 526, in main
  File "bash\bash.py", line 690, in _main
  File "bash\basher\__init__.py", line 4263, in Init
  File "bash\bosh\__init__.py", line 3697, in init_stores
  File "bash\bosh\__init__.py", line 2157, in __init__
  File "bash\bosh\__init__.py", line 1596, in __init__
  File "bash\bosh\__init__.py", line 2336, in refresh
  File "bash\bosh\__init__.py", line 1786, in refresh
  File "bash\bosh\__init__.py", line 1621, in refresh
  File "bash\bosh\__init__.py", line 2623, in new_info
  File "bash\bosh\__init__.py", line 1649, in new_info
  File "bash\bosh\__init__.py", line 460, in __init__
  File "bash\bosh\__init__.py", line 260, in __init__
  File "bash\bosh\__init__.py", line 221, in __init__
  File "bash\bolt.py", line 1726, in __repr__
  File "bash\bosh\__init__.py", line 678, in abs_path
AttributeError: 'ModInfo' object has no attribute '_file_key'

It was mtime yes - went ahead and overrode the repr so it uses fn_key
but that was not defined at this point either - we definitely need to
set the table attributes before anything so time for a hack. Note that
setting _file_key would not be enough since for ModInfo needs also
isGhost for abs_path so I kept the repr override.

Nit:

- Mopy/bash/bosh/converters.py: we should decouple refreshConverters
from irefresh
- to_add is a precious RefrData attribute
- refresh: moved delete_refresh in the if True refactoring placeholder

Absorb ModInfo._reset_cache into readHeader:

readHeader is guarded by the same if kwargs['load_cache'] in super's
_reset_cache - WIP #336 for AFile and #353 - note the hopefully there.