Refresh fixups:
Mopy/bash/basher/files_links.py: seems we need to use rdata here as
load order of files above the ones added might change for instance.
That would also take care of the scenario where duplicated file is named
after a missing master to a higher loading plugin missing that master,
for a lower loading (going from missing -> delinquent) we would need
a reset status mechanism *for ModInfo also*.

Mopy/bash/basher/saves_links.py:

Traceback (most recent call last):
  File "C:\...\wrye-bash\Mopy\bash\balt.py", line 1720, in __Execute
    self.Execute()
  File "C:\...\wrye-bash\Mopy\bash\basher\saves_links.py", line 652, in Execute
    def Execute(self): _self.MoveFiles(profile=self._text)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\wrye-bash\Mopy\bash\basher\saves_links.py", line 670, in MoveFiles
    self.window.RefreshUI(RefrData(to_del=moved))
  File "C:\...\wrye-bash\Mopy\bash\balt.py", line 789, in RefreshUI
    self.__gList.RemoveItemAt(self._get_uil_index(d))
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\wrye-bash\Mopy\bash\balt.py", line 1325, in _get_uil_index
    return self.__gList.FindIndexOf(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\wrye-bash\Mopy\bash\gui\list_ctrl.py", line 279, in FindIndexOf
    return self._native_widget.FindItem(-1, self._item_itemId[item])
                                            ~~~~~~~~~~~~~~~~~^^^^^^
KeyError: SaveInfo<POST_MASTER Copy699966 Copy Rename2.ess>

I also renamed check_existence to check_removed (duh)

Mopy/bash/basher/__init__.py: Chop off a propagate_refresh(True). Note
unlock_lo == bush.game.using_txt_file here. More on DoSave in next
commits.

balt: MODS key could appear with an empty RefrData - oops.

Under #701