Regression: RefreshData > RefreshUI blows if ex mergeable were deleted:
Introduced in 176205861cbbe4a00df4ace4ac099644d3c93b3d - duh

Traceback (most recent call last):
  File "bash\balt.py", line 1575, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\__init__.py", line 3960, in RefreshData
    refreshSaves=False) # was True
  File "bash\basher\__init__.py", line 912, in RefreshUI
    super(ModList, self).RefreshUI(**kwargs)
  File "bash\balt.py", line 1772, in RefreshUI
    self.PopulateItem(item=file_)
  File "bash\balt.py", line 1724, in PopulateItem
    labelTxt = self.labels[col](self, item)
  File "bash\basher\__init__.py", line 789, in <lambda>
    ('Modified',   lambda self, path: formatDate(self.data[path].mtime)),
  File "bash\bolt.py", line 1222, in __getitem__
    return self.data[key]
KeyError: bolt.Path(u'Harvest [Flora] - Shivering Isles - Copy.esp')

I just hate this piece of code in RefreshData, for more than one reason
turns out.