[!]Rip off defaults MelOpt Float - change of behavior:
As discussed having "optional" elements turns out to be not such a good
idea:
- actually *most* of the elements should be optional. In fact this commit
works in this direction as flipping the default to None for _MelNum
(by deleting __init__ override and modifying pack_subrecord_data) makes
all those numbers optional. Note MelFid was already there. Might break
if we relied on 0 default for creating a record - we don't do this
much but still !
- so we should make some elements required (and supply defaults for
these) - this is quite some effort and seems that nobody is sure which
are those required elements - so better left for later (should be
handled at Mel level - so after having a mel hierarchy)
- some of the "optional" elements specified non zero (non None now)
defaults. Those would not be dumped if we did indeed load that value
and this is a change that might break stuff, if we relied on this to
drop records for some reason - a prominent case is MelOptFloat(b'XCLW'),
as discussed it's safe to nuke:

https://github.com/wrye-bash/wrye-bash/commit/0ec45db55d6a117105b0b433613c4a2160831ac0#commitcomment-47085582

- Mopy/bash/game/oblivion/patcher/special.py: default 0 was needed here
- the cases that we set the default to null are handled naturally

Net change:
- We don't omit the (few) elements if present and have 0 (or the handful
of non 0 MelFloats). We don't want to do this
- MelFloat (_Num later) won't be dumped if not present - we want this

Mopy/bash/bolt.py: Fix for passing None to isclose_

From Infernio:
traceback (most recent call last):
file "bash\gui\events.pyo",
line 165, in _post file "bash\balt.pyo",
line 884, in _conversation_wrapper file "bash\basher\patcher_dialog.pyo",
line 175, in patchexecute file "bash\patcher\patch_files.pyo",
line 290, in buildpatch file "bash\patcher\patchers\preservers.pyo",
line 589, in buildpatch file "bash\patcher\patchers\preservers.pyo",
line 573, in handle patch cellblock file "bash\bolt.pyo", line 1675,
in floatsequal file "bash\bolt.pyo",
line 1668, in isclose typeerror: unsupported operand type(s) for -: 'nonetype' and 'nonetype'

Edit: I assume this is because of the defaults now being None, so it's
trying to check some float against None?

Yep, and this is why this commits stays a proud [!] - we should keep an
eye for numerical record attributes that can now be None and treat those
specially - this will be easier the less this code is, so #312 and #480
(parsers abc) related.

Infernio: Mopy/bash/brec/advanced_elements.py

Fix MelLocation blowing up on mapFids

Reason was that MelUnion.setDefault left the record in an invalid state,
with the decider attr pointing to one variant, but the record actually
having types for a different variant. Sample traceback:

patcher_dialog.py  270 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 172, in PatchExecute
    patchFile.init_patchers_data(enabled_patchers, SubProgress(progress, 0, 0.1)) #try to speed this up!
  File "bash\patcher\patch_files.py", line 139, in init_patchers_data
    patcher.initData(SubProgress(progress, index))
  File "bash\patcher\patchers\preservers.py", line 167, in initData
    srcFile = self._mod_file_read(srcInfo)
  File "bash\patcher\base.py", line 329, in _mod_file_read
    modFile.load(True)
  File "bash\mod_files.py", line 261, in load
    if do_map_fids: self._convert_fids(to_long=True)
  File "bash\mod_files.py", line 361, in _convert_fids
    target_top.convertFids(mapper, to_long)
  File "bash\brec\record_groups.py", line 271, in convertFids
    record.convertFids(mapper,toLong)
  File "bash\brec\record_structs.py", line 516, in convertFids
    self.__class__.melSet.convertFids(self,mapper,toLong)
  File "bash\brec\record_structs.py", line 121, in convertFids
    element.mapFids(record,mapper,True)
  File "bash\brec\advanced_elements.py", line 855, in mapFids
    element.mapFids(record, function, save)
  File "bash\brec\basic_elements.py", line 668, in mapFids
    result = function(getattr(record, attr))
  File "bash\mod_files.py", line 330, in mapper
    mod,object = int(fid >> 24),int(fid & 0xFFFFFF)
TypeError: unsupported operand type(s) for >>: 'str' and 'int'

More detailed explanation from
https://github.com/wrye-bash/wrye-bash/commit/9303d0d67ffcf0928569ea425a9cb6eb98d13130#commitcomment-47271741

The situation looks like this:
- We load a `PACK` record (I used
`DA15StayAtCurrentLocationPelagiusFearful [PACK:00000E41]` for testing).
This one has three entries in the `Package Data\Data Input Values` list,
each of which is introduced by an `ANAM` subrecord.
- For each of those entries, we set defaults. This sets the defaults in
the MelUnion, which sets defaults for all alternatives since they may
have different attributes.
- For `PLDT`, this happens to set location_type to 0 and location_value
to `b'\x00\x00\x00\x00'`, the second coming from one of the alternatives.
- Now we have a case distinction:
  - If we hit a `PLDT` subrecord and load it (e.g. the first entry in
  the record mentioned above), everything is fine and we replace the
  defaults. `mapFids` works great, we can dump it, everything is peachy.
  - If we do *not* hit a `PLDT` subrecord (e.g. the second and third
  entries in the record mentioned above), then we keep the defaults so
  that `dumpData` will not write out a `PLDT` subrecord. But before that
  happens, we map the FormIDs to long FormIDs at the end of the load
  procedure.
    This is where the problem happens - the union is marked as
	containing FormIDs because one of its alternatives really does
	contain FormIDs. So when we map FormIDs for it, we check with the
	decider.
    The decider looks up based on location_type, which is 0. That just
	so happens to be one of the alternatives that contains FormIDs.
    So we map FormIDs, but the value of location_value (which is the
	attr that can be a FormID), is still the default
	(`b'\x00\x00\x00\x00'`) and so the FormID mapping blows.

-----
Ut:
This is gonna be solved at the root when we are gonna have JIT FormIds -
still far but not light years far.

Under #480

Co-authored-by: Infernio <infernio@icloud.com>