Regression: crash on Skyrim due to 'Skyrim.esm isn't active':
load_order.py  220 _updateCache: Error updating load_order cache from liblo
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 465, in main
    frame = app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4342, in Init
    self.InitData(progress)
  File "bash\basher\__init__.py", line 4373, in InitData
    bosh.modInfos.refresh()
  File "bash\bosh.py", line 4221, in refresh
    hasChanged += self.plugins.refreshLoadOrder(forceRefresh=hasChanged)
  File "bash\bosh.py", line 2947, in _plugins_cache_wrapper
    return lord_func(*args, **kwargs)
  File "bash\bosh.py", line 3029, in refreshLoadOrder
    if forceRefresh or hasChanged: self.lord = load_order.GetLo()
  File "bash\load_order.py", line 225, in GetLo
    if not cached or _current_lo is __empty: _updateCache()
  File "bash\load_order.py", line 212, in _updateCache
    lord = _getLoFromLiblo()
  File "bash\load_order.py", line 77, in _getLoFromLiblo
    __fixLoadOrder(lord)
  File "bash\load_order.py", line 136, in __fixLoadOrder
    __fixActive(_current_lo.activeOrdered, lord)
  File "bash\load_order.py", line 184, in __fixActive
    SetActivePlugins(actiSorted, lord, _fixed=True)
  File "bash\load_order.py", line 230, in SetActivePlugins
    _liblo_handle.SetActivePlugins(act)
  File "bash\liblo.py", line 361, in SetActivePlugins
    _Clo_set_active_plugins(self._DB, plugins, num)
  File "bash\liblo.py", line 209, in LibloErrorCheck
    raise LibloError(result)
bash.liblo.LibloError: LibloError: LIBLO_ERROR_INVALID_ARGS:Invalid active plugins list supplied. Details: Skyrim.esm isn't active.