Fixup for leveled lists:
Mopy/bash/brec/common_records.py: Those entries are MelObjects resulting
in:

TypeError: unhashable type: <class 'bash.brec.basic_elements.MelObject'>

Introduced in 84443645ed2d04122229208abb8eb5a01480dfd3 [!]

Mopy/bash/basher/gui_patchers.py: typing warnings as in "'None' object
is not callable" and shadowing. While at it I realized that
_AListsMerger in gui_patchers was actually a redundant level of nesting,
confusingly named as the one in mergers - dropped it but note it was
creating the tag_choices dict as a defaultdict(tuple) - unless I miss
something this looks like it should be a defaultdict(set).