copy_info API: fixups, dropping unneeded refreshes - notes:
Fixup (was in files_links.File_Duplicate, moved to copy_info):

@@ -3871,2 +3872,3 @@ def copy_info(self, fileName, destDir, destName=None, set_mtime=None):
         if not destName: destName = fileName
+        destName = GPath(destName)
         srcPath = self[fileName].getPath()

table was updated with __string__ path as key - so delete_Refresh would
blow:

Traceback (most recent call last):
  ...
  File "bash\bosh\__init__.py", line 4671, in delete_Refresh
  File "bash\bosh\__init__.py", line 2882, in removeMods
  File "bash\bosh\__init__.py", line 2872, in saveLoadAndActive
  File "bash\bosh\__init__.py", line 2825, in _plugins_cache_wrapper
  File "bash\bosh\__init__.py", line 2869, in saveLoadOrder
  File "bash\load_order.py", line 244, in SaveLoadOrder
  File "bash\load_order.py", line 257, in _reset_mtimes_cache
  File "bash\bolt.py", line 1222, in __getitem__
KeyError: u'Unofficial Oblivion Patch Copy.esp'

cause the (unicode) key was in mtimes (a table view) while not of course
modInfos.

Introduced Modinfos.copy_info() override: taken from
files_links.File_Duplicate. Not sure why updating the table and on the
`if fileInfos.table.getItem(fileName,'mtime')` condition. Related to
lockLO ? I dropped the condition and made sure we update the table
using a bolt.Path key.
Note that set_mtime is never None currently and should not be when
moving inside the Data/ dir - enforced.

Table deletion is taken care of in FileInfos.delete so below not needed:

-            if self.mtimes.has_key(name): del self.mtimes[name]

as mtimes is just a view of modInfos.table, updated in refresh() (if the
keys were right):

            for d in set(self.table.keys()) &  set(_deleted):
                del self.table[d]

Related to the eternal delete issue #172.

Last note: the bug was triggered if duplicating more than 1 mods - cause
one mod case asks for filename and converts to Path. Just so you know.


Mopy/bash/basher/files_links.py:
Change: saves/bsas times used to be increased on duplicating - dropped.


Mopy/bash/basher/mod_links.py:
- espm times now are counted from master file esm and up - see modtimes
notes
- below should be taken care of in copy_info - setType also resets it by
calling setmtime:

	-            newInfo.setmtime(newTime)

table handling moved inside copy_info()

Still copy_info/move should maybe not call refresh at all - just update
internal structures - they are FileInfos methods...
Also we need a policy for modtimes in modInfos. Currently BAIN and liblo
increase at one minute intervals while internal operations by the
second (the somewhat ugly '+1') but this is documented here basically
and I have not visited all cases. Should be in load_order.py, set
on import.


Refreshes:

Mopy/bash/basher/saves_links.py:
- copy path would refresh on each save copied (should not need to
refresh at all)
- RefreshData() was not needed - under #205
- refresh was not needed at all when copying to other profile
Had to introduce copy_info doRefresh parameter (as in move - should be
renamed).

The errors in table update and next commit make me think the code is
ripe now for introducing assert statements.