[!]WIP parser aliases:
Initial idea was _get_alias to encapsulate GPath for the rhole - then
_coerce_fid was a natural follow up - lots of slightly different code
smoothed out hence the !. Finally realized that we don't need to chop
off the 0x.

Note:
- the result of get was sometimes gpathed sometimes not (all possible
combinations) - kept the GPath should be dropped in #543.
- Wip in the sense that not sure if _AParser(_HandleAliases) is ok or
_HandleAliases must be kept a mixin. Further simplify/document.
- also defaultdict's should be added
- ScriptText does not use aliases?
- I also dropped a few _coerce calls as CsvReader should return unicode
- tiny fixup for readEffects/writeEffects probably introduced in
120234c8fe6be6fa9698ce26ef5e553349e71745

_coerce_fid:

Note:

@@ -523,5 +523,3 @@ def readFromText(self,textPath):
                     if fidMod.lower() == u'none': continue
-                    fidObject = _coerce(fidObject[2:], int, 16)
-                    if fidObject is None: continue
-                    fid = (self._get_alias(fidMod), fidObject)
+                    fid = self._coerce_fid(fidMod, fidObject)
                     offset = _coerce(offset, int)

_coerce would never return None for an int

More group/name renames

Squash _coerce_fid

Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)] on win32
>>> int('0x89', 0)
137
>>> int('0x89')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '0x89'
>>> int('89')
89
int('0x89', 16)
137
>>> int('89', 16)
137
>>> int('0x8f', 16)
143
>>> int('0x8f', 0)
143
>>> int('8f', 0)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: invalid literal for int() with base 0: '8f'

If all objectIndex fields are 0x prefixed we could:

@@ -63,9 +63,9 @@ def _get_alias(self, modname):
     def _coerce_fid(self, modname, hex_fid):
         """Create a long formid from a unicode modname and a unicode
         hexadecimal - it will blow with ValueError if hex_fid is not
         convertible."""
-        return self._get_alias(modname), int(hex_fid, 16)
+        return self._get_alias(modname), int(hex_fid, 0)

to get more errors - quite a few are 0x we even check for that

Fixup: sum

@@ -283,3 +300,3 @@ def _do_write_plugin(self, loaded_mod):
         # Check if we've actually changed something, otherwise skip saving
-        if sum(num_changed_records):
+        if num_changed_records:
             loaded_mod.safeSave()

c= Counter()
c['ACT']+=1
sum(c)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'