Fix regression on missing settings for screens - more prefixing:
Introduced in 4074824daf636886b138ea7611caa5e75e1b6370 due to some
wrong conflict resolution

- colReverse are booleans really

Add string prefixes to record_groups

Note stuff like:

-        while not insAtEnd(endPos,'Cell Block'):
+        while not insAtEnd(endPos, u'Cell Block'):

This is still sometimes bytes sometimes unicode - fix!

Mopy/bash/barb.py:

Fixup for command line backup ( -b -f "some_file.7z" )

Traceback (most recent call last):
  File "bash\bash.py", line 251, in main
    _main(opts, wx_locale)
  File "bash\bash.py", line 404, in _main
    backup.backup_settings(balt)
  File "bash\barb.py", line 161, in backup_settings
    self._backup_settings(temp_settings_backup_dir)
  File "bash\barb.py", line 182, in _backup_settings
    backup_dir, dest7z = self._backup_dest_file.head, self._backup_dest_file.tail
AttributeError: 'str' object has no attribute 'head'

Note it's str not unicode btw.

Mopy/bash/patcher: sigs are bytes

Add string prefixes to bosh

Mopy/bash/bosh/converters.py: backwards compat for allowing str/unicode
pickle keys - rest us ok, used in get/setattr

Note that for tables we need lots of backwards compat

@@ -2593,3 +2593,3 @@ def _remove_restore(self, removes, restores, refresh_ui, cede_ownership,
                         refresh_ui[0] = True
-                        modInfos.table.setItem(GPath(ci_dest), 'installer',
+                        modInfos.table.setItem(GPath(ci_dest), u'installer',
                                                installer)

but this will be taken care of in #543 (note that GPath there).
The rest are internal dict/function arguments - passes - omods seems ok -
prefixing was:

Co-authored-by : Daniel Nunes <daniel.henri.nunes@gmail.com>