Update loot api integration to loot api python v3.1.1:
What changed was the way loot_api is initialised and the
get_plugin_tags() and get_plugin_cleanliness() functions, which now need
to be passed True as a second argument to retain their previous
function.

Also updated the install_loot_api and mktaglist scripts. They both work
for me now out of the scripts folder. A bunch of file paths assumed the
scripts to be in the root directory (not in scripts). No idea when they
were last working.

Under #388.

Catch AttributeError from older loot api:

Wrye Bash encountered an error.
Please post the information below to the official thread at:
https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/& or
https://bethesda.net/community/topic/38798/relz-wrye-bash-oblivion-skyrim-skyrim-se-fallout-4/

Traceback (most recent call last):
  File "bash\bash.py", line 229, in main
    _main(opts)
  File "bash\bash.py", line 325, in _main
    bosh.initBosh(opts.personalPath, opts.localAppDataPath, bashIni)
  File "bash\bosh\__init__.py", line 3427, in initBosh
    initDirs(bashIni, personal, localAppData)
  File "bash\bosh\__init__.py", line 3239, in initDirs
    configHelpers = ConfigHelpers()
  File "bash\bosh\mods_metadata.py", line 230, in __init__
    loot_api.initialise_locale('')
AttributeError: 'module' object has no attribute 'initialise_locale'

@@ -232,3 +232,3 @@ def __init__(self):
                 lootDb = loot_game.get_database()
-            except OSError:
+            except (OSError, AttributeError):
                 deprint(u'The LOOT API failed to initialize', traceback=True)

Fix for refreshBashTags errors after loot api update:

The error itself should be benign. The `eval_lists()` command was
removed in the newer loot api versions. The loot api integration update
did make use of the new way of evaluating conditions (passing `True` as
a second argument to `get_plugin_tags()` and `get_plugin_cleanliness()`
but failed to removed the now unnecessary and failing `eval_lists()`
calls.

Apparently the error would only show for Skyrim/SSE, not for FO4 or
Oblivion.

Under #388.

Wrinklyninja:

Update to the LOOT API Python module  v3.1.0

@@ -10,4 +10,4 @@

-lootApiWrapperVersion = '3.0.0'
-lootApiWrapperRevision ='1275a11'
+lootApiWrapperVersion = '3.1.0'
+lootApiWrapperRevision ='a564f23'

Update to the LOOT API Python module v3.1.1

This includes a rollback of pybind11 to fix runtime crashing in
some environments.

@@ -10,4 +10,4 @@

-lootApiWrapperVersion = '3.1.0'
-lootApiWrapperRevision ='a564f23'
+lootApiWrapperVersion = '3.1.1'
+lootApiWrapperRevision ='f97de90'

For the gory details see #408

Utumno:

Taglist generated by the mktaglists script (on the f3/nv branch):

Using loot_api_python-3.1.0-4-gdaa3a49_relwithdebinfo-build-win32.7z

C:\Dropbox\eclipse_workspaces\python\wrye-bash\scripts>mktaglist.py
Loaded the LOOT API v0.13.2 using wrapper version 3.1.0
Oblivion masterlist converted.
Skyrim masterlist converted.
Skyrim Special Edition masterlist converted.
Fallout3 masterlist converted.
FalloutNV masterlist converted.
Fallout4 masterlist converted.
Taglist generator finished.
Done

Closes #388
Closes #408