Moving rename_info to gui WIP:
Note I inlined enable() and moved is_save_enabled to SaveInfo - will be
further worked on in next commits. Enable/disable save is still broken
when cosaves are present:

balt.py 1265 rename_info: Renaming TEST_rename (1).ess to TEST_rename (1).esr failed
Traceback (most recent call last):
  File "bash\balt.py", line 1262, in rename_info
    return self.data_store._rename_operation(oldName, newName)
  File "bash\bosh\__init__.py", line 3112, in _rename_operation
    super(SaveInfos, self)._rename_operation(oldName, newName)
  File "bash\bosh\__init__.py", line 1650, in _rename_operation
    super(FileInfos, self)._rename_operation(oldName, newName)
  File "bash\bosh\__init__.py", line 1558, in _rename_operation
    return super(TableFileInfos, self)._rename_operation(oldName, newName)
  File "bash\bosh\__init__.py", line 1424, in _rename_operation
    env.shellMove(*list(izip(*rename_paths)))
  File "bash\env\__init__.py", line 215, in shellMove
    renameOnCollision=autoRename, silent=silent)
  File "bash\env\__init__.py", line 148, in _fileOperation
    if aborted: raise SkipError()
SkipError: Action skipped by user.