Fixup for regression in saveSettings:
Traceback (most recent call last):
  File "bash\balt.py", line 2505, in __Execute
    self.Execute()
  File "bash\basher\installers_links.py", line 391, in Execute
    bosh.oblivionIni.setBsaRedirection(bass.settings[self.key])
  File "bash\bosh\ini_files.py", line 641, in setBsaRedirection
    self.saveSetting(u'Archive',u'sArchiveList',sArchives)
  File "bash\bosh\ini_files.py", line 569, in saveSetting
    self.saveSettings(ini_settings)
  File "bash\bosh\ini_files.py", line 299, in saveSettings
    _add_remaining_new_items()
  File "bash\bosh\ini_files.py", line 289, in _add_remaining_new_items
    del ini_settings[section]
  File "bash\bolt.py", line 452, in __delitem__
    return super(LowerDict, self).__delitem__(_ci_str(k))
KeyError: CIstr(u'General')

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 3514, in OnShowPage
    self.currentPage.ShowPanel()
  File "bash\balt.py", line 1605, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\__init__.py", line 2859, in ShowPanel
    scan_data_dir)
  File "bash\balt.py", line 1605, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\bosh\bain.py", line 1531, in _projects_walk_cache_wrapper
    return func(self, *args, **kwargs)
  File "bash\basher\__init__.py", line 2889, in _refresh_installers_if_needed
    refresh_info)
  File "bash\bosh\bain.py", line 1603, in irefresh
    oblivionIni.setBsaRedirection(True)
  File "bash\bosh\ini_files.py", line 641, in setBsaRedirection
    self.saveSetting(u'Archive',u'sArchiveList',sArchives)
  File "bash\bosh\ini_files.py", line 569, in saveSetting
    self.saveSettings(ini_settings)
  File "bash\bosh\ini_files.py", line 299, in saveSettings
    _add_remaining_new_items()
  File "bash\bosh\ini_files.py", line 289, in _add_remaining_new_items
    del ini_settings[section]
  File "bash\bolt.py", line 452, in __delitem__
    return super(LowerDict, self).__delitem__(_ci_str(k))
KeyError: CIstr(u'General')

Reported by @Infernio at Discord, probably introduced in
797af92e5b361cc42dd8d8470565d1a496e31acc

Mopy/bash/parsers.py:
Took the opportunity to throw in a no-op change in imports -
collections.defaultdict -> defaultdict, it's too verbose and leads to
long lines - will come handy soon

Mopy/bash/bosh/_mergeability.py: _pbash_mergeable_no_load is only used
here