game/oblivion/patcher package - notice specific game import in basher.py
Under #124

I had to rename the module to 'patcher' - good name ?

    Wrye Bash starting
    Using Wrye Bash Version 306
    Python version: 2.7.8
    wxPython version: 2.8.12.1 (msw-unicode)
    input encoding: None; output encoding: None; locale: ('el_GR', 'cp1253')
    Searching for game to manage:
    bush.py   81 detectGames: Detected the following supported games via Windows Registry:
    bush.py   83 detectGames:  oblivion: C:\GAMES\TESIV\Oblivion
    bush.py   95 detectGames: Detecting games via relative path and the -o argument:
    bush.py  144 setGame: No preferred game specified.
    bush.py   81 detectGames: Detected the following supported games via Windows Registry:
    bush.py   83 detectGames:  oblivion: C:\GAMES\TESIV\Oblivion
    bush.py   95 detectGames: Detecting games via relative path and the -o argument:
    bush.py  133 setGame: Specified game "oblivion" was found: C:\GAMES\TESIV\Oblivion
    testing UAC
    bosh.py 5542 __init__: Using libbsa API version: 2.0.0
    bosh.py 5548 __init__: Using libloadorder API version: 4.0.1
    bosh.py 5554 __init__: Using LOOT API version: 0.6.0
    C:\GAMES\TESIV\Oblivion
    basher.py  139 <module>: Comtypes is missing, features utilizing HTML will be disabled
    Traceback (most recent call last):
      File "Wrye Bash Launcher.pyw", line 87, in <module>
        bash.main()
      File "bash\bash.py", line 573, in main
        basher.InitSettings()
      File "bash\basher.py", line 17746, in InitSettings
        initPatchers()
      File "bash\basher.py", line 8129, in initPatchers
        globals()[x]() for x in bush.game.patchers
    TypeError: 'module' object is not iterable

--------------------------------------------------------------------------------
Notice: bush detection goes in cycles - at some point I got:

Wrye Bash starting
Using Wrye Bash Version 306
Python version: 2.7.8
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('el_GR', 'cp1253')
Searching for game to manage:
bush.py   81 detectGames: Detected the following supported games via Windows Registry:
bush.py   83 detectGames:  oblivion: C:\GAMES\TESIV\Oblivion
bush.py   95 detectGames: Detecting games via relative path and the -o argument:
bush.py  144 setGame: No preferred game specified.
bush.py   81 detectGames: Detected the following supported games via Windows Registry:
bush.py   83 detectGames:  oblivion: C:\GAMES\TESIV\Oblivion
bush.py   95 detectGames: Detecting games via relative path and the -o argument:
bush.py  133 setGame: Specified game "oblivion" was found: C:\GAMES\TESIV\Oblivion
testing UAC
bush.py   81 detectGames: Detected the following supported games via Windows Registry:
bush.py   83 detectGames:  oblivion: C:\GAMES\TESIV\Oblivion
bush.py   95 detectGames: Detecting games via relative path and the -o argument:
bush.py  101 detectGames:  oblivion: C:\GAMES\TESIV\Oblivion
bush.py  144 setGame: No preferred game specified.
bush.py  151 setGame:  Using oblivion game: C:\GAMES\TESIV\Oblivion
bush.py   81 detectGames: Detected the following supported games via Windows Registry:
bush.py   83 detectGames:  oblivion: C:\GAMES\TESIV\Oblivion
bush.py   95 detectGames: Detecting games via relative path and the -o argument:
bush.py  101 detectGames:  oblivion: C:\GAMES\TESIV\Oblivion
bush.py  144 setGame: No preferred game specified.
bush.py  151 setGame:  Using oblivion game: C:\GAMES\TESIV\Oblivion
fail bash\game\oblivion\patchers\special.py
fail bash\basher.py
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 87, in <module>
    bash.main()
  File "bash\bash.py", line 484, in main
    raise e
bash.bolt.BoltError: Error creating required Wrye Bash directories.  Please check the settings for the following paths in your bash.ini, the drive does not exist:

[General] sOblivionMods
    F:\Oblivion Mods2