Re-add compat code for bash.tabs.order:
Removed in 5e1acb6ac3417f2541049adb3ffc378155b2eb40 seems needed till
this day:

Traceback (most recent call last):
  File "bash\bash.py", line 425, in main
  File "bash\bash.py", line 573, in _main
  File "bash\basher\__init__.py", line 4349, in Init
  File "bash\basher\__init__.py", line 3928, in __init__
  File "bash\basher\__init__.py", line 3798, in __init__
TypeError: list indices must be integers or slices, not str

Rest is some nit from debugging refreshTracked:

Remove mismatchedEspms

No uses - this will add some tiny performance to refreshStatus - some
borderline EAFP

Renames

Iteration variables like this should have the same name - one less
variable in the debugger.

Some more EAFP

Nit is under #219.