_saves: Fix Statistics command throwing TypeError
Traceback (most recent call last):
  File "*****\bash\balt.py", line 1582, in __Execute
    self.Execute()
  File "*****\bash\basher\saves_links.py", line 811, in Execute
    saveFile.logStats(log)
  File "*****\bash\bosh\_saves.py", line 449, in logStats
    'next_obj_id': f'{__unpacker(self.preGlobals[:4]):%08X}'})
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported format string passed to tuple.__format__

There were two issues: the erroneous %, & passing a tuple without
unpacking it. Broke in 307576872023b542f4be903ff4601cd240456250.

TES5/SSE: Add EXPL\VMAD

Matches xEdit defs, apparently works, & isn't removed by CK.