C/P MultiTweakItem got methods from C/P Patcher classes
Still same questions as in patchers/base - would it make any sense to make
 getRead/WriteClasses() into classmethods ?

 # This is the 2nd commit message:

apply(self,modFile,record,bashTags) -> (self,modFile,record)

 # This is the 3rd commit message:

Revert "apply(self,modFile,record,bashTags) -> (self,modFile,record)"

This reverts commit e0504690814051ed4d2175d0b6a20c8010b2f424.
Can't readily find where apply() is called - I want apply to have 3 arguments
(since the fourth is never used) but it'll have to wait

Traceback (most recent call last):
  File "bash\basher.py", line 6958, in Execute
  File "bash\bosh.py", line 11024, in buildPatch
TypeError: apply() takes exactly 3 arguments (4 given)