Make renaming operations refresh-atomic
When renaming a newly created project under wine, this stack trace would
greet you:

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 2208, in OnLabelEdited
    self.data_store.rename_info(package, name_new))
  File "bash\bosh\__init__.py", line 1129, in rename_info
    return self._rename_operation(oldName, newName)
  File "bash\bosh\bain.py", line 1678, in _rename_operation
    return self[oldName].renameInstaller(newName, self)
  File "bash\bosh\bain.py", line 1532, in renameInstaller
    return self._installer_rename(data, name_new)
  File "bash\bosh\bain.py", line 982, in _installer_rename
    del data[g_path]
  File "bash\bolt.py", line 1254, in __delitem__
    del self.data[key]
KeyError: bolt.Path(u'test')

Upon restarting, things would become even worse, with the entire
Installers tab whited out. A different stack trace occured:

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 3553, in OnShowPage
    self.currentPage.ShowPanel()
  File "bash\balt.py", line 1796, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\__init__.py", line 2898, in ShowPanel
    scan_data_dir)
  File "bash\balt.py", line 1796, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\bosh\bain.py", line 1552, in _projects_walk_cache_wrapper
    return func(self, *args, **kwargs)
  File "bash\basher\__init__.py", line 2928, in _refresh_installers_if_needed
    refresh_info)
  File "bash\bosh\bain.py", line 1636, in irefresh
    progress, fullRefresh, refresh_info, deleted, pending, projects)
  File "bash\bosh\bain.py", line 1552, in _projects_walk_cache_wrapper
    return func(self, *args, **kwargs)
  File "bash\bosh\bain.py", line 1774, in _refreshInstallers
    _index=index, _fullRefresh=fullRefresh)
  File "bash\bosh\bain.py", line 1790, in refresh_installer
    installer.refreshBasic(progress, recalculate_project_crc=_fullRefresh)
  File "bash\bosh\bain.py", line 859, in refreshBasic
    return self._refreshBasic(progress, recalculate_project_crc)
  File "bash\bosh\bain.py", line 866, in _refreshBasic
    self._refreshSource(progress, recalculate_project_crc)
  File "bash\bosh\bain.py", line 1432, in _refreshSource
    recalculate_project_crc)
  File "bash\bosh\bain.py", line 1364, in _refresh_from_project_dir
    max_mtime = apRoot.mtime
  File "bash\bolt.py", line 778, in _getmtime
    return int(os.path.getmtime(self._s))
  File "C:\Python27\lib\genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
WindowsError: [Error 2] File not found: u'\\home\\infernio\\.wine-bash\\drive_c\\Program Files\\Steam\\steamapps\\common\\Skyrim Mods\\Bash Installers\\test'

This is not just limited to new projects though, it happens for all tabs
that allow you to create new files (e.g. on the Mods tab, making a new
plugin and renaming it via the top right box will cause the same
problem).

Took a long time to figure out what's going on. It seems this happens
because we carry out the shell move first, then hit a refresh for some
reason (FS timing differences between Windows and wine?), and that
refresh removes the old installer from the BAIN data store and creates
a new one for whatever you renamed it to before the renaming operation
can finish. This is essentially a race condition.

It could, in theory, affect Windows as well. Probably depends on the
timing of FS/CPU interactions.