env.get_default_app_icon, get_***_path, testPermissions (disabled !):
When I imported in bosh:

from env import ... # instead of the relative import from ..env import..

bolt.Path and bash.bolt.Path were both imported !

C:\_\Python27\python.exe "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw"
# ...
testing UAC
Traceback (most recent call last):
fail bash\load_order.py
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 364, in main
    opts.oblivionPath, bashIni)
  File "bash\bosh\__init__.py", line 10080, in initBosh
    from .. import load_order ##: move it from here - also called from restore settings
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/Mopy/Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\load_order.py", line 329, in <module>
    if bosh.dirs['saveBase'] == bosh.dirs['app']:
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\bolt.py", line 1022, in __cmp__
    return cmp(self._cs, Path.getCase(other))
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\bolt.py", line 515, in getCase
    return os.path.normcase(os.path.normpath(name))
  File "C:\_\Python27\lib\ntpath.py", line 419, in normpath
    if path.startswith(('\\\\.\\', '\\\\?\\')):
ImportError: caused by AttributeError("'Path' object has no attribute 'startswith'",)
[2015-11-14 01:07:50.876392] [0xc00000c3] [trace]   Getting path to %LOCALAPPDATA%.

Process finished with exit code 1

This puzzled me a bit till I pinned it.

------------------------------------------------------------------------
Removed debug prints:

 # This is the 2nd commit message:
-d= {winreg.HKEY_CURRENT_USER: 'winreg.HKEY_CURRENT_USER',
     winreg.HKEY_LOCAL_MACHINE: 'winreg.HKEY_LOCAL_MACHINE'}

@@ -45,8 +45,4 @@ def get_game_path(submod):
                     value = winreg.QueryValueEx(key, entry)
-                except OSError: # WindowsError, OSError ? http://stackoverflow.com/questions/5227107/python-code-to-read-registry
-                    print 'Failed:', d[hkey], u'Software\\%s%s' % (wow6432, subkey), entry
-                    # import traceback
-                    # traceback.print_exc()
+                except OSError:
                     continue
-                print 'Found:', d[hkey], u'Software\\%s%s' % (wow6432, subkey), entry, value
                 if value[1] != winreg.REG_SZ: continue