Regression - non CBash games would crash on importing bosh:
If CBash is not present or not detected, the if CBash doesn't trigger
and none of the symbols is initialized.

Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 365, in main
    import bosh
  File "Wrye Bash Launcher.pyw", line 76, in load_module
    exec compile(code, initfile, 'exec') in mod.__dict__
  File "bash\bosh\__init__.py", line 51, in <module>
    from .mods_metadata import ConfigHelpers
  File "Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\bosh\mods_metadata.py", line 32, in <module>
    from ..cint import ObBaseRecord, ObCollection
  File "Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\cint.py", line 358, in <module>
    class CBashApi (object):
  File "bash\cint.py", line 361, in CBashApi
    VersionMajor = _CGetVersionMajor()
ImportError: caused by ImportError(u'caused by ImportError(u\'caused by NameError("name \\\'_CGetVersionMajor\\\' is not defined",)\',)',)

Introduced in 50c5aaa79ea74987e2fb5214945dacf8625f63ca.

Closes #333 (again).