WIP: fleshing out the caches
Fix for Plugins cache not being updated correctly:

Deleting mods outside Bash and then running Bash would crash.
Long story short: KeyError in LoadOrder.__init__ cause I passed an
empty loadOrder and tried to order active with it. It would raise
causing plugins.lord never being set in plugins.refresh() leading to
AttributeError:

Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
	bash.main()
  File "bash\bash.py", line 465, in main
	frame = app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4339, in Init
	self.InitData(progress)
  File "bash\basher\__init__.py", line 4370, in InitData
	bosh.modInfos.refresh() #
  File "bash\bosh.py", line 4220, in refresh
	hasChanged += self.plugins.refresh(forceRefresh=hasChanged)
  File "bash\bosh.py", line 2948, in wrapper
	args[0].lord.loadOrder), list(args[0].lord.activeOrdered)
AttributeError: 'NoneType' object has no attribute 'loadOrder'

This was masking the original exception hence the added e variable.

Test with:

def GetLo(cached=False):
+    raise Exception('TEST')
     if not cached or _current_lo is __empty: _updateCache()

Added comments.