[!]Unused 'readMe' Installer persistent attribute -> 'extras_dict':
Tricky, I have to reason carefully - this is the only chance to hack in
more attributes to address design flaws (like the wizard images bug,
- 'extras_dict' sounds like a good name to me - extras is already there,
plus it is not really descriptive.
- Dropped `if self.dirty_sizeCrc is None` - under settings cruft (#253).
- reverting to older versions won't hurt as 'readMe' was unused - we
just set it, never used it.
- upgrading however needs hacking `__setstate__`

The rest is for fixing the bug reported here:
http://forums.bethsoft.com/topic/1602198-wrye-bash-thread-109/#entry25145760
and brought to light by a34b27aea5ab8a726bc5911ee1a26ff9db8a31df,
whereupon on a layout like:

Project\
  some_folder\
    some.espm etc
  fomod\
    some_document.xml

the root index would be calculated as len(r'some_folder\') as fomod\
was skipped but then refreshDataSizeCrc would add file 'ocument.xml'
leading to file not found tracebacks and perpetual missing files (and
whatnot). I say "brought to light" and not "introduced", cause the same
would happen with files/folders starting with u'--' - just not as
common (I however remember some user having problems with
--packages).

Now _find_root_index updates extras_dict with the full path of the root,
will come handy in the wizards bug too - but I have to test all paths
self.fileSizeCrcs is used.

 # This is the 2nd commit message:

'root_path' -> 'root_path_lower':

I said this code is tricky - turns out it's best to keep the case
sensitive version - look what this entails. However most of the fixup
code will be dropped, just useful for people on my dev branch.

 # This is the 3rd commit message:

Fixup for bug reported by zilav:

http://forums.bethsoft.com/topic/1602198-wrye-bash-thread-109/page-5#entry25159260

Traceback (most recent call last):
  File "bash\basher\__init__.py", line 3633, in OnShowPage
    self.currentPage.ShowPanel()
  File "bash\basher\__init__.py", line 2648, in ShowPanel
    fullRefresh, scan_data_dir)
  File "bash\balt.py", line 1573, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\bosh\__init__.py", line 5849, in _projects_walk_cache_wrapper
    return func(self, *args, **kwargs)
  File "bash\basher\__init__.py", line 2675, in _refresh_installers_if_needed
    refreshui[0] |= data.irefresh(progress, what, fullRefresh, refresh_info)
  File "bash\bosh\__init__.py", line 5911, in irefresh
    changed = not self.loaded and self.__load(progress)
  File "bash\bosh\__init__.py", line 5931, in __load
    self.dictFile.load()
  File "bash\bolt.py", line 1472, in load
    self.data.update(cPickle.load(ins))
  File "bash\bosh\__init__.py", line 4668, in __setstate__
    bolt.Progress(), recalculate_project_crc=False)
  File "bash\bosh\__init__.py", line 5161, in refreshBasic
    return self._refreshBasic(archive, progress, recalculate_project_crc)
  File "bash\bosh\__init__.py", line 5167, in _refreshBasic
    self._refreshSource(archive, progress, recalculate_project_crc)
  File "bash\bosh\__init__.py", line 5403, in _refreshSource
    self.size, self.modified = archive.size_mtime()
  File "bash\bolt.py", line 761, in size_mtime
    lstat = os.lstat(self._s)
WindowsError: [Error 2] : u'E:\\Games\\Skyrim Mods\\Bash Installers\\Detailed Terrain and Tree LoD 2_5-17984-2-5.zip'

We have to test if the pickled file still exists as refreshBasic will
blow (we should have been doing this anyway, no use running
refreshDataSizeCrc for non existing packages).