Fixups for doc browser - refresh lists on activation:
When Doc Browser was shown on creating a new BP it would try to SetMod to
it and failed:

Traceback (most recent call last):
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\events.py", line 181, in _post
    result = listener(*listener_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\balt.py", line 720, in _handle_select
    self._select(item_key)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\__init__.py", line 1178, in _select
    Link.Frame.docBrowser.SetMod(modName)
  File "D:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\frames.py", line 325, in SetMod
    self._plugin_dropdown.set_selection(self._lower_lo[plugin_lower])
                                        ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'bashed patch, 2.esp'

The easy way would be to drop the _select override of modInfos but I
wanted to make sure that no other cases like this would fail. I noticed
this while trying to add detection of new docs while DB was shown. Note:

- _clear_doc calls DoSave so cleaned up a bit the flow (would be called
twice - no-op on boot or if mod_name is empty, but I needed to move
_search call after the attrs creation)
- this remains a hack but no need to pursue it further - we would need
event based refreshes and it would still not worth the hassle. For now
the new BP doc is detected and added automatically and deleted mods
are removed (the doc file is still there by the way).

Note in the beginning I tried inserting:

@@ -152,6 +152,4 @@ def _update_docs_list(self):
                         self.SetMod('') # needed
-        if added_mods := set_mods - documented:
-            for mod_dex, mod in enumerate(sorted(documented)):
-                if mod in added_mods:
-                    self._mod_list.lb_insert(mod, mod_dex)
+        for mod in documented - set_mods:
+            self._mod_list.lb_append(mod)

to be greeted with:

Traceback (most recent call last):
  File "D:\...\Mopy\bash\gui\events.py", line 181, in _post
    result = listener(*listener_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\...\Mopy\bash\basher\frames.py", line 245, in _do_select_existing
    self.SetMod(lb_selection_str)
  File "D:\...\Mopy\bash\basher\frames.py", line 328, in SetMod
    self._init_controls()
  File "D:\...\Mopy\bash\basher\frames.py", line 139, in _init_controls
    self._update_docs_list()
  File "D:\...\Mopy\bash\basher\frames.py", line 156, in _update_docs_list
    self._mod_list.lb_insert(mod, mod_dex)
  File "D:\...\Mopy\bash\gui\multi_choices.py", line 142, in lb_insert
    self._native_widget.Insert(str_item, lb_selection_dex)
wx._core.wxAssertionError: C++ assertion "!IsSorted()" failed at D:\a\1\s\ext\wxWidgets\include\wx/ctrlsub.h(148) in wxItemContainer::InsertItems(): can't insert items in sorted control

@@ -142,15 +142,14 @@ def _update_docs_list(self):
         sel = self._mod_list.lb_get_selected_strings()
-        mods = self._mod_list.lb_get_str_items()
-        documented = sorted(mod_name for mod_name, mod_inf in
-            self._mod_infos_singl.items() if mod_inf.get_table_prop('doc'))
-        if documented != mods:
-            self._mod_list.lb_set_items(documented) # todo would lb_delete_at_index/insert keep selection?
-            if sel:
-                for dex, mod_name in enumerate(documented):
-                    if mod_name in sel:
-                        self._mod_list.lb_select_index(dex)
-                        break # one selection right?
-                else: # deselect previous plugin - deleted or docs removed
-                    self._mod_list.lb_select_none()
-                    self.SetMod('') # needed
+        sel = sel[0] if sel else None # one selection right?
+        mods = [*map(FName, self._mod_list.lb_get_str_items())]
+        documented = {mod_name for mod_name, mod_inf in
+            self._mod_infos_singl.items() if mod_inf.get_table_prop('doc')}
+        if del_mods := (set_mods := {*mods}) - documented:
+            for mod_dex, mod in enumerate(reversed(mods)):
+                if mod in del_mods: # deleted or docs removed
+                    self._mod_list.lb_delete_at_index(len(mods) - mod_dex - 1)
+                    if sel == mod: # deselect previous plugin
+                        self.SetMod('') # needed
+        for mod in documented - set_mods:
+            self._mod_list.lb_append(mod)