Fixup for steam vdf file containing str when we expected dict:
Not sure if the right fix

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bash.py", line 424, in main
    _main(opts, wx_locale, wxver)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bash.py", line 482, in _main
    bush_game, game_ini_path = _detect_game(opts, bash_ini_path)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bash.py", line 591, in _detect_game
    bush_game = _import_bush_and_set_game(opts)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bash.py", line 610, in _import_bush_and_set_game
    game_infos = bush.detect_and_set_game(opts.oblivionPath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bush.py", line 275, in detect_and_set_game
    foundGames_, gname, gm_path = _detectGames(cli_game_dir)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bush.py", line 215, in _detectGames
    foundGames_ = _supportedGames(skip_new_ws)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\bush.py", line 105, in _supportedGames
    steam_paths = get_steam_game_paths(game_type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\env\windows.py", line 1065, in get_steam_game_paths
    _parse_steam_manifests(submod, _get_steam_path())]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\env\common.py", line 161, in _parse_steam_manifests
    steam_manifests = _get_steam_manifests(steam_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\env\common.py", line 143, in _get_steam_manifests
    lf_path = library_folder_info.get('path')
              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

from pprint import pprint
pprint(lf_dict)
{'0': {'apps': {'228980': '160133214'},
       'contentid': '-8764781366088934374',
       'label': '',
       'path': 'C:\\Program Files (x86)\\Steam',
       'time_last_update_corruption': '0',
       'totalsize': '0',
       'update_clean_bytes_tally': '0'},
 '1': {'apps': {'292030': '53483389454', '489830': '13628807699'},
       'contentid': '8986505443999158815',
       'label': '',
       'path': 'I:\\GAMES\\SteamLibrary',
       'time_last_update_corruption': '0',
       'totalsize': '1000202039296',
       'update_clean_bytes_tally': '0'},
 'contentstatsid': '-8764781366088934374'}  <--- this

SaveInfo.getStatus -> _masters_order_status:

_masters_order_status is the last step in base getStatus.
Note the len check was redundant (since we just checked for equality).