Fix get_file_version on Linux
Broke in 6506c3e3252bb6361b1fc332648d09ed4b9ae7d1:

Traceback (most recent call last):
  File "bash/bash.py", line 267, in main
    _main(opts, wx_locale)
  File "bash/bash.py", line 435, in _main
    frame = app.Init() # Link.Frame is set here !
  File "bash/basher/__init__.py", line 4236, in Init
    frame = BashFrame() # Link.Frame global set here
  File "bash/basher/__init__.py", line 3849, in __init__
    self._native_widget.SetStatusBar(BashStatusBar(self._native_widget))
  File "bash/balt.py", line 2285, in __init__
    self.UpdateIconSizes()
  File "bash/basher/__init__.py", line 3729, in UpdateIconSizes
    self._addButton(link)
  File "bash/balt.py", line 2301, in _addButton
    gButton = link.GetBitmapButton(self)
  File "bash/basher/app_buttons.py", line 173, in GetBitmapButton
    window, self.images[idex].GetBitmap(), onRClick)
  File "bash/basher/app_buttons.py", line 90, in GetBitmapButton
    btn_tooltip=self.sb_button_tip)
  File "bash/basher/app_buttons.py", line 478, in sb_button_tip
    tip_ = self._tip + u' ' + self.version if self.version else self._tip
  File "bash/basher/app_buttons.py", line 515, in version
    version = self._version_path.strippedVersion
  File "bash/bolt.py", line 688, in strippedVersion
    version = list(self.version)
  File "bash/bolt.py", line 683, in version
    return get_file_version(self._s)
  File "bash/env/linux.py", line 155, in get_file_version
    f.seek(_read(_DWORD, f, offset=60))
  File "bash/env/linux.py", line 122, in _read
    result = [_struct_unp(file_obj)[0] for x in xrange(count)] ##: array.fromfile(f, n)
TypeError: unpack_from() argument 1 must be string or buffer, not file