Some wx3 compatibility changes:
Mopy/bash/basher/settings_links.py: shadowing, Settings_Language button
should be disabled on current language (chops off one use of ugly
_bassLang) and rename encodings to more private _plugin_encodings.
Moved the init of bolt.pluginEncoding out of UI code (duh).
Needs work
Mopy/bash/bash.py: changed the message to reflect this is the default
user locale
Mopy/bash/bolt.py: use function - adds some overhead due to isDir call,
but I'd rather have this (hacky) code centralized.

More wx3 compatibility changes:

Those are wx2/3 valid

FlexGridSizer changed signature

Traceback (most recent call last):
  File "bash\bash.py", line 193, in main
    _main(opts)
  File "bash\bash.py", line 371, in _main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4038, in Init
    frame.RefreshData(booting=True)
  File "bash\balt.py", line 1623, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\__init__.py", line 3819, in RefreshData
    self.warn_corrupted()
  File "bash\basher\__init__.py", line 3901, in warn_corrupted
    message, liststyle='list', canCancel=False)
  File "bash\balt.py", line 1047, in Display
    with cls(*args, **kwargs) as dialog:
  File "bash\balt.py", line 2809, in __init__
    sizer = wx.FlexGridSizer(len(lists) + 2, 1)
TypeError: FlexGridSizer(): arguments did not match any overloaded call:
  overload 1: not enough arguments
  overload 2: argument 2 has unexpected type 'int'
  overload 3: not enough arguments
  overload 4: not enough arguments

nycz:

Bin the SetUAC function in patcher_dialog

As far as I can tell this was only used in one place, and the argument
was always the same thing rendering the whole function entirely
pointless. Also, dumping this function gets rid of a pesky wx
dependency in patcher_dialog too.