Complain about patches with >255 masters
Otherwise blows up during dumping with a cryptic error message once it
hits the first FormID that happens to be large enough:

Traceback (most recent call last):
  File "bash\brec\record_structs.pyo", line 103, in dumpData
  File "bash\brec\basic_elements.pyo", line 465, in dumpData
  File "bash\brec\basic_elements.pyo", line 465, in dumpData
  File "bash\brec\common_subrecords.pyo", line 226, in dumpData
  File "bash\brec\common_subrecords.pyo", line 157, in dumpData
  File "bash\brec\advanced_elements.pyo", line 864, in dumpData
  File "bash\brec\advanced_elements.pyo", line 491, in dumpData
  File "bash\brec\basic_elements.pyo", line 575, in dumpData
  File "bash\brec\mod_io.pyo", line 364, in packSub
error: integer out of range for 'I' format code

A nice-to-have would be automatically splitting the BP into multiple
files instead of just telling the user that that's the workaround, see
issue linked below.

Under #533