[RH]Plug in FName:
A rabbit hole in its habitat. The notes of an unfortunate engineer who
fell into the collapsing RH were reconstructed from the hole's radiation
and are presented below.

------------------------------------------------------------------------
Pruning .s needs rest of the branch

Explicit is better than implicit yes, but those .s were just *too*
explicit - too much visual clutter and the real implicitness was there
anyway so we don't loose anything, apart the .s

I especially like join(x.s for x in li) -> join(li)

Note comparison with self_installer used to be case insensitive in bosh.

GPath hunting

Mopy/bash/basher/mods_links.py:
Note (pl_name := FName(pl_name)) in bosh.modInfos - FNDict always calls
FName.__new__ - is it cheaper to not-FName before?

_games_lo:
- What I like about map(FName, ...) is that we avoid the iteration
variable - cleaner. Happens to be faster too (by a 10% in my machine -
even faster for bigger lists)
- note also str(modname, encoding) - I finally decided not to allow
bytes in FName constructor

loot_parser use FNDict - bye plugin_s :)

'name' is gone for good:
(?<!(os|sys|fileInfo|modInfo|saveInfo|mod_info|effect|file_info|_bsa_info|patchInfo|newInfo|self)\.)
actually plain 'name' search in py files yields a single result

    os_name = os.name

More FName in records code

ci_body and ci_soul - more .s / moving from name -> ci_key

[!]Mopy/bash/bosh/save_headers.py:

Note we find the length of the str while we should find the len of the
encoded str - this will be addressed as part of the 480 refactoring
but _encode_masters does the right thing for now

Move __str__ to ListInfo / plugin to FileInfo

Finally the super slow ci_key property is gone along with self.name

Screen_ConvertTo: some tiny refactoring (lower not needed, just pass the
extension in lower case)

Drop GPath from patch config keys TTT ci_aliases

Mopy/bash/basher/patcher_dialog.py: strings should compare fine with
FName keys
- docsDir is GPath'ed in bolt.WryeText.genHtml()

Mopy/bash/bosh/__init__.py: note that is the only actual use of
ImportedMods
TODO: configItems are redundant we should leverage ordered dicts

Mopy/bash/basher/gui_patchers.py: _ci_aliases

Note I do not reassign the self.configChecks/Choices in saveConfig -
maybe this filtering belongs on load?

Mixing strings with FName in getSemiActive went down very badly >>>>

@@ -2541,3 +2541,3 @@ def getSemiActive(self, patches=None, skip_active=False):
                 for modName, is_merged in forward_compat_path_to_fn(
-                        config_checked, ret_type=dict).items(): ## todo check
+                        config_checked).items():
                     if is_merged and modName in self:

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\list_ctrl.py", line 286, in <lambda>
    self._native_widget.SortItems(lambda x, y: bolt.cmp_(sortDict[x], sortDict[y]))
KeyError: 453

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_pydevd_bundle\pydevd_cython_win32_39_64.pyx", line 1528, in _pydevd_bundle.pydevd_cython_win32_39_64.ThreadTracer.__call__
SystemError: _PyEval_EvalFrameDefault returned a result with an error set
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\list_ctrl.py", line 286, in <lambda>
    self._native_widget.SortItems(lambda x, y: bolt.cmp_(sortDict[x], sortDict[y]))
KeyError: 454

...

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_pydevd_bundle\pydevd_cython_win32_39_64.pyx", line 1528, in _pydevd_bundle.pydevd_cython_win32_39_64.ThreadTracer.__call__
SystemError: _PyEval_EvalFrameDefault returned a result with an error set
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\list_ctrl.py", line 286, in <lambda>
    self._native_widget.SortItems(lambda x, y: bolt.cmp_(sortDict[x], sortDict[y]))
KeyError: 458

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\list_ctrl.py", line 286, in <lambda>
    self._native_widget.SortItems(lambda x, y: bolt.cmp_(sortDict[x], sortDict[y]))
SystemError: _PyEval_EvalFrameDefault returned a result with an error set

The above exception was the direct cause of the following exception:

..........

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\list_ctrl.py", line 286, in <lambda>
    self._native_widget.SortItems(lambda x, y: bolt.cmp_(sortDict[x], sortDict[y]))
SystemError: _PyEval_EvalFrameDefault returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\events.py", line 178, in _post
    result = listener(*listener_args)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\__init__.py", line 1152, in _handle_key_up
    self._toggle_active_state(*toggle_target)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\balt.py", line 808, in _conversation_wrapper
    return func(*args, **kwargs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\__init__.py", line 1276, in _toggle_active_state
    self.RefreshUI(redraw=self._lo_redraw_targets(touched),
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\__init__.py", line 1068, in RefreshUI
    super(ModList, self).RefreshUI(**kwargs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\balt.py", line 1069, in RefreshUI
    self.SortItems()
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\balt.py", line 1336, in SortItems
    self.__gList.ReorderDisplayed(items)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\list_ctrl.py", line 286, in ReorderDisplayed
    self._native_widget.SortItems(lambda x, y: bolt.cmp_(sortDict[x], sortDict[y]))
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\gui\list_ctrl.py", line 286, in <lambda>
    self._native_widget.SortItems(lambda x, y: bolt.cmp_(sortDict[x], sortDict[y]))
SystemError: _PyEval_EvalFrameDefault returned a result with an error set

------------------------------------------------------------------------

Path.list pruning -> Path.ilist

Mopy/bash/basher/saves_links.py:
I dropped items.sort(key=lambda a: a.lower()) - getLocalSaveDirs is
already sorted. Note we list a dir whenever we display the saves menu

getGhosted:
- note all those fnames will be cached as FName - no matter were cached
like Paths (by list) - need to return a LowerDict - need revisit (but
that's BAIN)
- norm_ghost_get is almost always used in conjunction with
dirs['mods'].join - not easy to absorb this,  `norm_ghost_get` is for
nailing the pattern
- rpFile = ghost_norm_get(sFile, sFile) is the exception - here we get
a str and do stuff with it - cache? Maybe not - BAIN may need to cache
many files too much memory. A PathDict?
- rpFile - note str(x) because of:

@@ -2150,3 +2155,3 @@ def _process_data_dir(self, dirDirsFiles, progress):
                     try:
-                        modInfo = modInfos[GPath(rpFile)]
+                        modInfo = modInfos[rpFile]
                         new_sizeCrcDate[rpFile] = (modInfo.fsize,

- also mostly we do check for plugins after - follow 'removes' param -
replace with some structure? (inis/bsas/mods)
- avoid using list as in list(x fox in li) - list is a super reserved
keyword - prefer [*li]

Mopy/bash/basher/dialogs.py:
- walk is slower than listdir but clearly faster than calling isdir after

Mopy/bash/basher/settings_dialog.py: Note we really need strings here as
those are for a listbox - all_l10n_files.append(f.tail) tail was not
needed? f.ci_body[-3:].lower() is a bit ugly but performance is of no
importance here

Mopy/bash/basher/__init__.py: note _refresh_installers_if_needed I have
to convert to Path for omods API - it's actually failedOmods that must
become Set[FName]

Went for list returning a generator - no need to create a list in most
cases.

Mopy/bash/bosh/bain.py: the emptyDirs calculation needs reworking

Prune abs_path

@@ -1298,3 +1298,3 @@ def is_save_enabled(self):
         """True if I am enabled."""
-        return self.abs_path.cext == bush.game.Ess.ext
+        return self.ci_key.ci_ext == bush.game.Ess.ext

Mopy/bash/bosh/converters.py:

-                if GPath_no_norm(fileName).cext in readExts:
+                if fileName.endswith(__read_ext):

could use some timings but goal is of course to extinguish GPath_no_norm

Mopy/bash/basher/frames.py: for lb_index_for_str_item see
e008b1714160b19ab15ef85298c83cedf28a98b5

Mopy/bash/balt.py: TreeCtrl -> always FName. watch out for the deprints
and eventually remove them.

------------------------------------------------------------------------

Mopy/bash/bosh/__init__.py:

Note I use forward_compat_path_to_fn*** in move_infos for instance -
those also must go eventually

Note:

@@ -2164,3 +2164,4 @@ def cached_lo_insert_after(self, previous, new_mod):
             self[new_mod].setmtime(set_time)
-        self._lo_wip[previous_index + 1:previous_index + 1] = [new_mod]
+        self._lo_wip[previous_index + 1:previous_index + 1] = [
+            self[new_mod].ci_key]

due to:

             last_selected = load_order.get_ordered(selected)[
                 -1] if selected else self._lo_wip[-1]
-            self.cached_lo_insert_after(last_selected, new_mod_name)
+            self.cached_lo_insert_after(last_selected, newName)
             self.cached_lo_save_lo()

newName not always an FName. Similar issues with new_info - getting
there.

Mopy/bash/balt.py: some more fixups

On nightly the Installer labels (get_table_prop('installer')) return
strings, but on 543 they seem to return Paths, which blows on boot.

Mopy/bash/basher/bsa_links.py: pathlib: name is back. This worried me
a bit so started chopping off `tail`s

Infernio: bosh.py: Handle cosaves correctly in 543

------------------------------------------------------------------------
Master info renames:

disable_master(self): note I added setting mod_info to None
set_name was always called in the same pattern, encapsulated in
MasterInfo.rename_if_present. No need to use unique_key here so I
removed the comment.

belt espms: c55b60dfee2cb4337ddbcb056075d0cb76ee818b

------------------------------------------------------------------------
BAIN self.archive -> ci_key Note todos

Installer_Duplicate.Execute: project names with dots would mess up here
but anyway the split should be moved in the infos (unique_name ?)
Prune rest of archives - none left in the code!

compressionSettings takes an FName now

search for  ##: ci comparison!:

Note comparison became case insensitive in renameInstaller (old_key is
an FName now). We are accessing the table directly here (we should make
sure infos exist at this point and use those).

_is_ini_tweak was doing all the string operations to get the ini_name
but we needed the walrus here to use the return value ;)

espms/espmNots - note fixmes

hilfe - fortunately espmMap is volatile but still more code needed for
backwards and forward compat

Note that:
- had to add disallowed_exts in _askFilename maybe drop it?
We should not rely on checking extension for telling apart
InstallerProject/Archive so why are we disallowing read extensions for
projects.
- espm_checklist_fns - last time (of many) I try to discern espms from
espms
- gEspmList further encapsulated and common ugly code like ...
- ...replace(u'&&', u'&') centralized - should we move this to lb_ ?
- we should also override set_all_items_keep_pos(names_, vals)/lb_get_str_items

TODOs:
- lb_get_str_items FIXME shouldn't we chop off the * (see
idetails.get_espm)
- Installer_Espm_List -> was not doing any get_espm (&& -> &, chop off
the star) I added it -> correct ?

Mopy/bash/basher/installer_links.py: the `or bool(set.add(...))` is
to get me rid of an occurrence of an extra lb_check_at_index

BAIN WIP

A glimpse on some data structures in need of change/ gui logic
encapsulation // .replace(u'&', u'&&') in set_all_items_keep_pos, that
one sure should be there -> renames only in plugins though not on subs
ofc

Note we can now flesh out more rename_operation under #580

'installer' table prop was stored as FName -> __reduce__ -> Path -> boom

@@ -1584,3 +1584,3 @@ def new_info(self, fileName, *, _in_refresh=False, owner=None,
         if owner is not None:
-            info.set_table_prop('installer', owner)
+            info.set_table_prop('installer', '%s' % owner)
         if notify_bain:

The somewhat ugly `'%s' %` means we should be passing another type - in
this case I need a string here for backwards compatibility.

cls.file_pattern.search(u'%s' % fileName) shouldn't be needed - use
endswith here instead of regex here?

- don't mind the u'' - remember this is pre 460 (!) work - better chop
off all u''  at once - blurs an already complex diff

------------------------------------------------------------------------
Ok the dicts in DataDict __init__ and backwards compat

Much going on here:
- DataDict._data finally defined in init - comes at a price: this was
meant to be final - it wasn't anyway since long ago, but has rough edges
- note DataStore instantiates an FNDict :)
- turns out we need to init FName from CIstr in BAIN (todo)  - see
modInfos.table.setItem(ci_dest.
- we don't want to pickle FNames - see notes in init

As usual we should keep the backwards compat for a couple releases and
then bump the settings version up (still keep the forward compat code
for a couple more releases) - would be nice to have this in 310 we can
drop in 311.

Say thanks to  __reduce__ for doing the backwards compat for us:

@@ -1774,31 +1773,2 @@ class DataTable(DataDict):

-    def __drop_paths(self #, nested_dict=None
-                     ):
-        # if nested_dict is None:
-        #     nested_dict = self.dictFile.pickled_data
-        deprint(f'pruning paths from '
-          f'{dict(x for x in list(self.dictFile.pickled_data.items())[:10])}')
-        copy_data = list(self.dictFile.pickled_data.items())
-        self.dictFile.pickled_data.clear()
-        lo_dict = FNDict()
-        for k, v in copy_data:
-            # if isinstance(v, dict):
-            #     v = self.__drop_paths(v)
-            if isinstance(k, Path):
-                k = k.s
-            lo_dict[k] = v
-        return lo_dict
-
-    def __backwards_comp(self, nested_dict=None):
-        if nested_dict is None:
-            nested_dict = self._data
-        print(f'restoring paths in {nested_dict}')
-        builtin_dict = dict()
-        for k, v in nested_dict.items():
-            k = GPath_no_norm('%s' % k)
-            # if isinstance(v, dict):
-            #     v = self.__backwards_comp(v)
-            builtin_dict[k] = v
-        return builtin_dict
-
     def __init__(self,dictFile):
@@ -1808,3 +1778,5 @@ def __init__(self,dictFile):
         self.vdata = dictFile.vdata
-        super(DataTable, self).__init__(self.__drop_paths())
+        self.dictFile.pickled_data = _data = forward_compat_path_to_fn(
+            self.dictFile.pickled_data)
+        super(DataTable, self).__init__(_data)
         self.hasChanged = False ##: move to PickleDict
@@ -1815,3 +1787,3 @@ def save(self):
         if self.hasChanged and not dictFile.readOnly:
-            dictFile.pickled_data = self.__backwards_comp()
+            dictFile.pickled_data = self._data # todo decide on pickle data final
             self.hasChanged = not dictFile.save()

Fix for creating new BP

all these methods need typing - we should pass FName around there may be
more bugs lurking (note Mopy/bash/basher/installer_links.py)

Duplicate file fixups

- took the opportunity to add the filename validation at the expense of
a few more parameters. FileInfos  filesystem apis need more work but we
are near. FileInfo.dir seems to imply that we  can create those
anywhere though this is far from tested. Still a few fixmes gone (among
which isMod)

Fix for Paths in good/bad dlls:

See:

https://discord.com/channels/537706885965676554/537710082755133460/980329565408866354

Search for archiveRoot in refreshDataSizeCrc - used to be a Path

Traceback (most recent call last):
  File "bash\bolt.py", line 1141, in __eq__
AttributeError: 'FName' object has no attribute '_cs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bash\balt.py", line 1806, in __Execute
  File "bash\basher\installer_links.py", line 660, in Execute
  File "bash\basher\installer_links.py", line 641, in _try_installer
  File "bash\balt.py", line 815, in _conversation_wrapper
  File "bash\basher\installer_links.py", line 609, in Execute
  File "bash\bosh\bain.py", line 2497, in bain_install
  File "bash\bosh\bain.py", line 2441, in __installer_install
  File "bash\bosh\bain.py", line 1152, in install
  File "bash\bosh\bain.py", line 826, in refreshDataSizeCrc
  File "bash\bosh\bain.py", line 590, in __skipExecutable
  File "bash\bolt.py", line 1148, in __eq__
TypeError: Comparing Path with <class 'bash.bolt.FName'> not supported: FName('DisableVampRace0_4b-15697')

Judging from _init_executables_skips _good/badDlls should not be
reassigned - so I rewrote the functions. Now given there are only two
uses we might want to inline.

Thanks @Infernio for fixups among which:

Clean up some minor issues around _ask*

One usage of _askSave was not checking the return value, leading to a
traceback when canceling the dialog.

Fix Duplicate on Screenshots tab

root will be empty for the default copied filename, self is not a GUI
element, we need to add the extension in validate_filename_str and that
method needs to return FNames.