IMGS.DNAM:
See:
https://github.com/wrye-bash/wrye-bash/commit/f42d52664e267ca862fc48471b538a1be6d4dc3a#commitcomment-89968682

record_structs.py  609 loadData: Error loading IMGS record and/or subrecord: (Skyrim.esm, 0CE16C)
  eid = AbandonedShackImagespace
  subrecord = DNAM
  subrecord size = 12
  file pos = 244138147
mod_links.py  122 Execute: Exception loading Skyrim.esm:
Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 599, in loadData
    loader.load_mel(self, ins, sub_type, sub_size,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 664, in load_mel
    unpacked = ins.unpack(self._unpacker, size_, *debug_strs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\mod_io.py", line 374, in unpack
    return struct_unpacker(self.ins.read(size))
struct.error: unpack requires a buffer of 16 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 113, in Execute
    self._load_mod(dbg_inf, keepAll=False,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 86, in _load_mod
    modFile.load(True, **kwargs)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\mod_files.py", line 199, in load
    new_top = topClass(header, self.loadFactory, ins,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 678, in __init__
    super().__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 218, in __init__
    super().__init__(header, loadFactory, ins, do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 160, in __init__
    super().__init__(loadFactory, ins, self._end_pos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 50, in __init__
    self._load_rec_group(ins, endPos)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 231, in _load_rec_group
    grel = self._group_element(header, ins)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_groups.py", line 238, in _group_element
    return None if rec_class is None else rec_class(header, ins,
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 567, in __init__
    MreRecord.__init__(self, header, ins, do_unpack=do_unpack)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 400, in __init__
    self.loadData(ins, ins.size, file_offset=file_offset)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 613, in loadData
    raise exception.ModError(ins.inName, f'{error!r}') from error
bash.exception.ModError: Skyrim.esm: error('unpack requires a buffer of 16 bytes')