Fixup for dialog being destroyed twice in some cases:
I just knew there was something rotten there.
Repro: Mods > Load > Edit Lists... - just close the edit list dialog.
Then Mods > Load > Save List... save the list and get:

Traceback (most recent call last):
  File "bash\basher\mods_links.py", line 102, in Execute
    def Execute(self, event): _self.DoEdit(event)
  File "bash\basher\mods_links.py", line 177, in DoEdit
    balt.ListEditor.Display(self.window, _(u'Load Lists'), data)
  File "bash\balt.py", line 1166, in Display
    """Instantiate a dialog, display it and return the ShowModal result."""
  File "C:\_\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_windows.py", line 738, in __exit__
    self.Destroy()
  File "C:\_\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 14619, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
wx._core.PyDeadObjectError: The C++ part of the ListEditor object has been deleted, attribute access no longer allowed.

Added Destroy() where there wasn't any and removed the Destroy() call in
Dialog.OnCloseWindow().
Took the opportunity to wrap a bit in patcher dialog (and removed
pacthDialog=None which served no purpose whatsoever).