writeToMod chain fixups:
Was broken since 1330850b72eb12ff88b2ba9fbe7738706bad1c0b ? Note there
_load_plugin is called with keepAll False in

+    def writeToMod(self, mod_info):
...
+        return self._do_write_plugin(self._load_plugin(
+            mod_info, self.id_stored_info.keys()))

Of course real broken stuff is parsers ravioli which is addressed anew
leveraging 426db77ee71c939bb785b94eab7d4281f0f1fa26

Happened while testing - I had picked import factions to mod (they're
_AParser - Oblivion ofc):

Traceback (most recent call last):
  File "bash\balt.py", line 1827, in __Execute
    self.Execute()
  File "bash\basher\mod_links.py", line 1812, in Execute
    changed = self._import(ext, textDir, textName, textPath)
  File "bash\basher\mod_links.py", line 1774, in _import
    changed = parser.writeToMod(self._selected_info)
  File "bash\parsers.py", line 326, in writeToMod
    mod_info, self.id_stored_info))
  File "bash\parsers.py", line 279, in _do_write_plugin
    loaded_mod.safeSave()
  File "bash\mod_files.py", line 274, in safeSave
    self.save(filePath.temp)
  File "bash\mod_files.py", line 285, in save
    if not self.loadFactory.keepAll: raise StateError(u"Insufficient data to write file.")
bash.exception.StateError: Insufficient data to write file.

the fix is:

index ff834ecf3..22696c75d 100644
@@ -379,2 +379,2 @@ def writeToMod(self, mod_info):
-        return self._do_write_plugin(self._load_plugin(mod_info, keepAll=False,
-            target_types=self.id_stored_info))
+        return self._do_write_plugin(
+            self._load_plugin(mod_info, target_types=self.id_stored_info))

but this now blows with:

Traceback (most recent call last):
  File "bash\balt.py", line 1827, in __Execute
    self.Execute()
  File "bash\basher\mod_links.py", line 1811, in Execute
    changed = self._import(ext, textDir, textName, textPath)
  File "bash\basher\mod_links.py", line 1773, in _import
    changed = parser.writeToMod(self._selected_info)
  File "bash\parsers.py", line 380, in writeToMod
    self._load_plugin(mod_info, target_types=self.id_stored_info))
  File "bash\parsers.py", line 130, in _load_plugin
    mod_file.load(do_unpack=True)
  File "bash\mod_files.py", line 273, in load
    if do_map_fids: self._convert_fids(to_long=True)
  File "bash\mod_files.py", line 350, in _convert_fids
    target_top.convertFids(mapper, to_long)
  File "bash\brec\record_groups.py", line 155, in convertFids
    raise AbstractError(u'convertFids not implemented')
bash.exception.AbstractError: convertFids not implemented

Fixed by making MobBase pass - after all MobBase could be a
"keepAll=True/do_unpack=False" alias - hope this works, not the right
moment to rewrite. Import Factions works (that is not blows) but
Editor Ids not:

Traceback (most recent call last):
  File "bash\balt.py", line 1827, in __Execute
    self.Execute()
  File "bash\basher\mod_links.py", line 2287, in Execute
    changed = editorIds.writeToMod(self._selected_info)
  File "bash\parsers.py", line 587, in writeToMod
    oldEid = record.eid
AttributeError: 'MreRecord' object has no attribute 'eid'

fix in Mopy/bash/parsers.py (again doesn't blow at least) - this generic
puzzled me - one remains

Took the opportunity to make some of ModImport links static -
_AParser API leak but essentially just for typing - it's ok, we're on
dev :P

- parsers.ActorFactions._parse_line - was 8 fields here
- some more types should eventually become _fp/sp_types -> sigs