WIP Subrecords:
WIP refactoring of the MelBase hierarchy. Needs for sure next commit and
perhaps couple next but kept separate to review (it's already huge).
Evolved from an attempt to define packers and unpackers statically to an
attempt to define a clean dumping/loading API to an attempt to
encapsulate plugin strings handling, and the battle goes on. Still,
there is already much goodness in here so some random notes:

- dumpData overrides went down. Now we actually override the part of the
behavior we need - we can further centralize/optimize etc
- ModWriter is gone - another level of function calls, another API for
new (and seasoned) devs to grok, and most importantly packing/loading
logic all around the place
- strings handling is centralized - defining packSub0 and co away from
the usages was difficult to follow. Plus this is a part of the code that
needs work - for instance we recently (re)realized decoder() is (too)
slow, the encodings handling/naming is difficult to follow and rework
for py3 plus cstrip must disappear
- packSub does not do this weird "call me in two ways" - this is handled
by pack_subrecord_data
- used some itertools and comprehensions to avoid copying data, drop
inlines etc. I did use some `map`s here
- note _collect_array_data was already pack_subrecord_data - we now
don't need the sio however :) Plus to me it's much easier to reason
about a function than to reason about the stream that I write on -
seeing:

-    def _collect_array_data(self, record):
+    def pack_subrecord_data(self, record):
		 """Collects the actual data that will be dumped out."""
-        array_data = MelArray._DirectModWriter(sio())
-        if self._prelude:
-            self._prelude.dumpData(record, array_data) <-- HERE

I already wonder how come dumpData does not write headers in line 3 -
cause the definition of _DirectModWriter two lines above does not help
much. All this is past - only real complication is the strings one -
the packSub0 (...) is replaced with _dump_bytes and pack_subrecord_data.
It was doing too much (actually data was always encoded (see usages) no
need for if checks) and too little (copy/pasting packSub and buggily at
that, note the < 0xFFF check)
- I threw slots in but don't feel we should go and slot all subclasses -
this is still WIP
- subrecords attribute removed from MelRecord, making all instances
lighter - more to follow

------------------------------------------------------------------------

Limits of the current refactoring are things like:

- MelUInt32('INDX', '').packSub(out, struct_pack(u'=I', part_attr))

meaning some of the behavior should be static. We are still far from
that but not too far: MelAbc come in two flavors: subrecords and
collections of subrecords but this is pt4. The __slots__ attribute and
init overrides should be used as guides (hint `mel_sig` does not make
sense for MelGroups for instance, see also MreHeaderBase.MelMasterNames
__init__ comments). The attr being '' (EEE rename to u'unused') is just
exposing our current model a bit too bluntly: records are *not* composed
of MelBase instances - those just set/dump the attributes of the records
passed in from/to the stream they are passed in. I guess this was done
to save memory and it's probably a good idea - but defining the records
as sets of MelBase instances might also be a good idea - that's pt4+.

- strings handling. This is a mess that led me to an (as yet)
unsuccessful attack starting with PluginStr - so don't spend much brain
power on this, more to follow. Note however the problem was there from
packSub0 - at least all this now is limited to MelString
loaders/dumpers. Note also subtleties like:

@@ -525,3 +525,3 @@ def __init__(self, mel_sig, attr, default=None, maxSize=0):
		 self.maxSize = maxSize
-        self.encoding = None # None == automatic detection
+        self.encoding = None # will default to bolt.pluginEncoding

We really need to centralize - see also #544

_MelSimpleStruct(MelStruct) -> _MelField(MelBase)

get rid of quite some processing - further reworked in next commits
(look at the merge diff, this one will only confuse you)

Mopy/bash/brec/basic_elements.py: avoid concatenating strings

More comments on packSub0:

- if data is None: was never (see also rewrite later)
- data was always encoded (see usages) no need for if checks
- comparison was wrong? if lenData < 0xFFFF: vs if lenData <= 0xFFFF:
in packSub - note lenData = len(data) + 1, so the null terminator length
was already added
- note subheader format was hardcoded there

_MelField/MelStruct._packer

less function calls and more local scope, but importantly stop thinking
in terms of format and think in terms of operations. struct_pack uses
are a nice metric (less is better :P)

_MelField(MelBase):

Is this override needed? -> see following commits (and branches, this is
actually the tip of the 'default' iceberg)

	 def pack_subrecord_data(self,record):
		 try:
			 return super(MelFid, self).pack_subrecord_data( # pack an u'=I'
-                record.__getattribute__(self.attr))
+                record)
		 except AttributeError:
			 return None

Further fixups for MelFid: default (duh) must be None here - not sure
why it does not dump it though

But then:

Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 185, in PatchExecute
    self._save_pbash(patchFile, patch_name)
  File "bash\basher\patcher_dialog.py", line 276, in _save_pbash
    patchFile.safeSave()
  File "bash\mod_files.py", line 282, in safeSave
    self.save(filePath.temp)
  File "bash\mod_files.py", line 312, in save
    selfTops[rsig].dump(out)
  File "bash\brec\record_groups.py", line 254, in dump
    size = self.getSize()
  File "bash\brec\record_groups.py", line 245, in getSize
    (hsize + record.getSize()) for record in self.records)
  File "bash\brec\record_groups.py", line 245, in <genexpr>
    (hsize + record.getSize()) for record in self.records)
  File "bash\brec\record_structs.py", line 426, in getSize
    self.dumpData(out)
  File "bash\brec\record_structs.py", line 510, in dumpData
    self.__class__.melSet.dumpData(self,out)
  File "bash\brec\record_structs.py", line 136, in dumpData
    element.dumpData(record,out)
  File "bash\brec\basic_elements.py", line 175, in dumpData
    value = self.pack_subrecord_data(record)
  File "bash\brec\basic_elements.py", line 786, in pack_subrecord_data
    record)
  File "bash\brec\basic_elements.py", line 239, in pack_subrecord_data
    return self._packer(value.dump() if self.action else value)
error: cannot convert argument to integer

Hence except (AttributeError, struct.error) -> defaults...

Dropped some more dumpData for pack_subrecord_data - not always evident.

MelXXXX (sic)

Note again need for static unpacker in

+            MelXXXX(lenData).dumpData(out, u'record')

Search with Mel[A-Za-z0-9_]+\(.+\)\.

Inf fixups (thanks!):

@@ -769,3 +768,3 @@ def __init__(self, int_size):
     def loadData(self, record, ins, sub_type, size_, readId):
-        self.int_size = ins.unpack(self._unpacker, size_, readId)
+        self.int_size = ins.unpack(self._unpacker, size_, readId)[0]

Shouldn't actually do anything since MelXXXX isn't loaded yet. unpack
returns a tuple, we only want the int.

Under #480